### ISSUE TITLE
Bug: Explore block needs more margin

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-macktrucks-com#103]
Explore block needs a bit of vertical space to breathe at the top and the bottom
<img width="1050" alt="Screenshot 2023-05-23 at 12 13 39" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/fc629d10-a74a-4a56-b55c-f7bdb92a3a50">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
