### ISSUE TITLE
Bug: Mack-news Desktop view - Performance is low due to long CLS

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#105]
The list of links in the news sidebar is not filtered by any date therefore list of links is quite long and make CLS being not acceptable and bad UX.
<img width="1369" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/dcab9e8a-a845-452d-8518-584b2436b5bd">
<img width="1363" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/7569e241-4988-4ed5-a2a4-62a4053b4daf">

**Comment by girishdigrajkar** [comment]
Validated desktop view and able to see correct results hence, agree to closure of the defect:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/65c8923a-082f-414a-8cd3-87430b9ac85d">
