### ISSUE TITLE
Carousel Columns

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#11]
<img width="1572" alt="Carousel-Columns" src="https://user-images.githubusercontent.com/116451851/220729564-a633a2d5-2730-43fb-a979-616edd048145.png">
Can include video.

https://www.macktrucks.com/trucks/anthem/
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/trucks/anthem/?view-doc-source=true (work in progress content example).

**Comment by girishdigrajkar** [comment]
Validated and raised https://github.com/hlxsites/vg-macktrucks-com/issues/153 issue

**Comment by girishdigrajkar** [comment]
Defect 153 is closed hence, this issue could be closed
