### ISSUE TITLE
Bug: Major: News RSS xml does not have all the details

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#113]
Steps:
1. Navigate to https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-news/2022/
2. Validate the news rss feed

Actual:
Not all feed contents available 

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/2f0882b3-2f68-4f5e-8db6-f64af9324e5e">

[feed.docx](https://github.com/hlxsites/vg-macktrucks-com/files/11553250/feed.docx)

**Comment by Joesturbo** [comment]
This looks to be corrected? https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-news/feed.xml

**Comment by girishdigrajkar** [comment]
Validated with https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-news/ ,   https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-news/feed.xml   pages and able to see correct content ( As all 118 news are present in both pages) and hence, closing the defect.
