### ISSUE TITLE
Bug: Major - Mobile view - Block with hotspot points - The second block with hotspot points is not visible in Mobile view

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#114]
On https://28-hotspots-v3--vg-macktrucks-com--hlxsites.hlx.page/drafts/wingeier/hotspots3 there are two Blocks with hotspot points - the second block is not visible in Mobile view

**Steps to reproduce:**
1. Go to https://28-hotspots-v3--vg-macktrucks-com--hlxsites.hlx.page/drafts/wingeier/hotspots3 and open on Mobile view
2. Notice that the second Block with hotspot points

**Expected result**
second Block with hotspot points is not visible or scrollable in Mobile view

**Actual result**
the second Block with hotspot points below the first one on the above link is not visible or scrollable in Mobile view

<img width="1892" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/eb4f6b7a-c040-4871-8e7f-8694a3f1cca0">

**Comment by jonatan-lledo-netcentric** [comment]
have you tried to press the button below to swap between each of them?
<img width="575" alt="Screenshot 2023-06-02 at 10 13 29" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/fa27dac0-3222-448b-a505-283b20d453ed">

**Comment by girishdigrajkar** [comment]
**Validated and able to see correct result for 'Driver Environment' tab as below:**
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/c40041dc-8316-41d5-b7ba-81272420abf4)

**However, the extra blank space need to be fixed:**
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/c5876913-c3d8-43d6-9a48-70b7d05bfc8e)

**Comment by jonatan-lledo-netcentric** [comment]
use this [url](https://114--hotspot-points-not-visible--vg-macktrucks-com--hlxsites.hlx.page/trucks/anthem/features/) instead, because the other one is a demo page by aravindo

**Comment by girishdigrajkar** [comment]
Confirmed with Jonathan and its content due to which this blank space issue,  Confirmed as fixed.
