### ISSUE TITLE
Change the 'Submit' button to arrow button in the footer form

### ISSUE THREAD

**Issue by TomaszDziezykNetcentric** [hlxsites/vg-macktrucks-com#115]
Currently, there is a 'Submit' button in the footer subscribe form. It is displayed below the email input field. The button should be replaced with an arrow button and displayed on the right side of the input (inside the input).

The checkbox should not be visible on init. It should appear when the user tries to type the email.

Current version:
<img width="458" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/e7b18656-9147-4b5f-852f-a92dfb78e57c">

Expected:

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/bc41bd40-e2bd-4e3e-9016-d8c67988eed2)

**Comment by girishdigrajkar** [comment]
Validated and able to see correct results hence, agree to ticket closure.
