### ISSUE TITLE
Specs block

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [hlxsites/vg-macktrucks-com#116]
Specifications block

<img width="1128" alt="Screenshot 2023-05-24 at 15 30 10" src="https://github.com/hlxsites/vg-macktrucks-com/assets/103571932/97ae0510-305b-49a5-b626-03fab21b4ed7">

**Comment by girishdigrajkar** [comment]
Validated and noticed below defect related to links to pages and thus, this specs blocks needs below defect fix before proceeding: 
https://github.com/hlxsites/vg-macktrucks-com/issues/148

**Comment by girishdigrajkar** [comment]
Defect #148 is still outstanding

**Comment by girishdigrajkar** [comment]
All outstanding defects are closed and hence, marking this block to done.
