### ISSUE TITLE
Bug: Comfort section cards wrong displyed on mobile

### ISSUE THREAD

**Issue by TomaszDziezykNetcentric** [hlxsites/vg-macktrucks-com#119]
Currently, on the mobile version, there is only 1 item visible by default. The rest of the items are visible outside the page (it's possible to scroll right to see them - they are out of the page).

![Image](https://user-images.githubusercontent.com/125962117/240819638-31b899e2-b33d-40dd-8708-f50bcdd00e9b.png)

Expected results:
On mobile view, all the items should be visible one below the other like this:

![Image](https://user-images.githubusercontent.com/125962117/240819838-8d3dd3d5-8fd4-4fa0-8234-57ef8257442d.png)

**Comment by girishdigrajkar** [comment]
Able to see correct results and hence, agree to defect closure.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/954c79f3-c974-4e9c-bb9b-89c9b9b7aa58">
