### ISSUE TITLE
Inventory page (embed html in block)

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-macktrucks-com#127]

**Comment by girishdigrajkar** [comment]
[Manuel: ] Inventory block merged, Anthem and Granite inventory pages are now there (still some configuration required, but you can see main content):
https://main--vg-macktrucks-com--hlxsites.hlx.live/trucks/anthem/inventory/
https://main--vg-macktrucks-com--hlxsites.hlx.live/trucks/granite-series/inventory/
Block is removing all CTAs other than ‘View Details’, as requested.

**Comment by girishdigrajkar** [comment]
Validated above Inventory pages and raised Medium Bug https://github.com/hlxsites/vg-macktrucks-com/issues/179.

**Comment by shirin27** [comment]
Close the feature, and convert the leftover items to a new bug.
