### ISSUE TITLE
Material Safety SDS Info page

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-macktrucks-com#128]

**Comment by manuel-vara** [comment]
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/95145f79-6627-4841-8bf7-d1da326492cc)

**Comment by girishdigrajkar** [comment]
Validated and raised below Major defect :
https://github.com/hlxsites/vg-macktrucks-com/issues/176

**Comment by jonatan-lledo-netcentric** [comment]
#176 now ready for testing

**Comment by girishdigrajkar** [comment]
Outstanding bug 176 is now closed and this ticket could be marked to done.
