### ISSUE TITLE
Review: Embed all forms & test

### ISSUE THREAD

**Issue by verareljic** [hlxsites/vg-macktrucks-com#129]
Be ensure that the forms are working well. Please cross check all the forms.

**Comment by girishdigrajkar** [comment]
Below forms are in the scope of this ticket and testing is in progress: 

1. https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-connect/connected-support/ota-registration/
2. https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/support/body-builders/request-for-assistance
3. https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/request-a-quote/
4. https://main--vg-macktrucks-com--hlxsites.hlx.page/about-mack/contact-us/contact-us-form/
5. https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/mack-leasing-system/
6. https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/lr-electric/Vehicle-as-a-service/
7. https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/uptime-solutions/diagnostic-tools/diagnostic-subscriptions/
