### ISSUE TITLE
Bug: Minimal - Font Styling differences on blocks

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#137]
This ticket includes minimal Font Styling differences on blocks still present after #53 Replace Fonts

01. on #18  Fragment block - RSS News article content

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/4fe87e10-1fb8-459e-b99b-74e07f95890f)

02. on #43  Teaser grid layout

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/391614b5-072f-4693-b52a-4f2e32dd66ec)

03. on #70  Download blocks

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/5c0e21f2-40cc-4ec8-a094-939b01a14462)

04. on #42  Blocks with Tabs for different type of content

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/c2493b32-e8b3-4143-89b4-90f0cd7cec1e)

05. on Find a Dealer section

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/845ac304-9828-4e07-b37b-0dd000deb8df)

06. on Find a Dealer locator section

 
<img width="1252" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/ec0cbc4c-d50e-4c9b-8e38-616f3e7d9e75">

07. on #126  Search-results page

<img width="1886" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/467b6410-8e34-4e82-beff-b4047cdd43f5">

**Comment by girishdigrajkar** [comment]
As discussed in call with Joe, it is decided to close the bug as the text is readable /no overlap so no major issue observed.
