### ISSUE TITLE
Bug: Major - Mobile View - Find a Dealer Locator - There is an extra padding on top of the search bar

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#139]
On the Mobile view for the Find a Dealer page - an incorrect extra padding is displayed on top of the Search bar

**Steps to reproduce:**
1. Go to Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/find-a-dealer/ and open in Mobile view
2. Click on the Filter button next to the Search button
3. Notice the extra padding on top of the Search bar

**Expected result**
There should be no extra padding on top of the Search bar in the Mobile view of the Find a Dealer locator

<img width="798" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/0247d92d-c354-4062-81a6-017c1592f65d">

**Actual result**
There is extra padding on top of the Search bar of the Find a Dealer Locator in Mobile view

<img width="798" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/32ab2aff-8f2c-4859-ad75-fc459ddf7fec">

**Comment by girishdigrajkar** [comment]
Validated and no extra padding on top of search is noticed and hence, confirmed as fixed:

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/5d9149d3-13e3-4a13-954f-c686e5bfc131)
