### ISSUE TITLE
Post GoLive: Integrate OneTrust policy + cookie consent modal page

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#14]
- [ ]  Integrate OneTrust cookie policy js
- [ ]  inject the cookie content into the cookies page via the integration
- [ ]  validate that the cookie policy button appears and functions on every page

<img width="620" alt="Cookie-Consent-Modal" src="https://user-images.githubusercontent.com/116451851/221908656-e174d041-a25e-4038-88e5-4b8ca6d3523a.png">

**Comment by verareljic** [comment]
Needs to be considered after the GoLive.
