### ISSUE TITLE
Bug: Critical - Search bar - Search icon from the Search bar is oversized

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#150]
When clicking on the Search button to expand the Search button - the Search icon from the Search bar is oversized and spills out of frame

**Steps to reproduce:**
1. Go to https://131-aem-franklin-connector--vg-macktrucks-com--hlxsites.hlx.page/ and click on the Search button
2. Notice the Search icon from the Search bar

**Expected result**
Search icon from the Search bar should be smaller and not spill out of frame

**Actual result**
Search icon from the Search bar is oversized and spills out of frame

<img width="1408" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/bf4af6de-d3a5-4cee-abf6-b4e14faf3199">

**on Mobile** is too oversized and covers the search bar text field

<img width="471" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/a2d1de0a-43f1-4aa9-b0ec-646b872b568f">

**Note:**: Issue changed to Critical as the ovsersized Search icon is blocking the user from performing a Search in the Search bar in the Mobile view

**Comment by jonatan-lledo-netcentric** [comment]
will be fixed with #171

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1787" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/7bb1f064-6dd0-4957-9644-9e7d66a99f73">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/06d1c93a-cd3a-4bda-b7af-b6a72502ce1d">
