### ISSUE TITLE
Bug: Major: Mobile: Extra space observed in Carousal block & other observations

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#153]
**Steps:**

1. In Mobile Viewport, Navigate to https://11-carousel--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/carousel
2. Validate the Carousal block

**Expected vs Actual:**
1. Extra space has been observed at the bottom of Carousal block <- NOT FIXED. NEW ISSUE FOR IT IS NEEDED
2. Image/Video placement is not as expected as in earlier implementation all text was prior video
3. Extra space on right side has been noted
4. _Play button is not similar aligned as that of earlier site_ <- NOT FIXED. IT WAS DECIDED TO LEAVE IT AS IT IS

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/dd6de202-39bf-4965-8be1-83a2977c3252)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e33995a8-9ff2-4e94-9769-8f5bf741f99f)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/c8ab9903-0267-42e0-a749-594e0ea6637f)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/916eb1db-3c8a-4984-9893-ebc968a57a35)

**Comment by TomaszDziezykNetcentric** [comment]
@girishdigrajkar 
I change the content of the bug.
1. point will not be fixed now - we need a new bug only for it. As we discussed on yesterday daily.
4. Won't fix. The play button should be on the right column's center as it is now.

**Comment by girishdigrajkar** [comment]
Confirmed as fixed for below points : 
1 :Extra space has been observed at the bottom of Carousal block <- NOT FIXED. NEW ISSUE FOR IT IS NEEDED  **Raised  https://github.com/hlxsites/vg-macktrucks-com/issues/232**
2: Image/Video placement is not as expected as in earlier implementation all text was prior video : **Confirmed as Fixed**
3:Extra space on right side has been noted :  **Confirmed as Fixed**
4: Play button is not similar aligned as that of earlier site <- NOT FIXED. IT WAS DECIDED TO LEAVE IT AS IT IS : **Wont Fix so no QA**

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e8a79ed5-edbc-41ca-9641-22a62e4cb5e6">
