### ISSUE TITLE
Bug: Major - Mobile view - Search results page - The Scroll up button is missing from the Search results page in Mobile view

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#159]
On the Search results page in Mobile view - the Scroll up button that takes to the user directly to the top of the page is missing while scrolling through Search results

**Steps to reproduce:**
1. Go to macktrucks.com and click on the Search button and perform a Search (for example with the word "truck" )
2. Scroll down through the Search results and notice the Scroll up button taking you to the top of the page
3. Repeat steps 1 and 2 for https://main--vg-macktrucks-com--hlxsites.hlx.page/
4. Notice that the Scroll up button is missing

**Expected result**
Scroll up button should be present when scrolling down on Search results and clicking it should take the user to the top of the Search results page

**Actual result**
When scrolling down on Search results - the Scroll up button is missing 

<img width="1254" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/6a4fb271-9d03-4884-b8bf-73f981163d71">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/dc26e6cb-0b40-4440-93bc-5cd30c899d6f">
