### ISSUE TITLE
Bug: Minor - Mobile view - Search results page - Clicking on Sort by opens the dropdown in an incorrect position

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#160]
On the Mobile view of the Search results page - clicking the Sort by dropdown menu will display the dropdown menu in a misplaced position

**Steps to reproduce:**
1. Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/ in Mobile view and perform a Search (for example for the words "truck" )
2. Click on the Sort by drodpown menu
3. Notice where the dropdown menu for Sort by is displayed

**Expected result**
Sort by dropdown menu should be displayed under the Sort by button

**Actual result**
Sort By dropdown menu is displayed in an incorrect position on Mobile view

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/847c035f-8b29-42cd-a968-27a9d0ad9174)

**Comment by jonatan-lledo-netcentric** [comment]
will be fix with issue #171

**Comment by girishdigrajkar** [comment]
Bug is still present for mobile:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/1e6c0b04-8143-45b1-b948-bce795b4076f">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e6a486cc-cb50-4c23-a319-5f27892eaa39">
