### ISSUE TITLE
Bug: Minor: Registered / Trademark icon is bigger than expected 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#167]
Steps: 
1. Navigate to https://cards--vg-macktrucks-com--hlxsites.hlx.page/drafts/lakshmi/cards/
2. Validate the Registered / Trademark icon on cards

Expected vs Actual:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/61d16121-4356-4237-a894-131fb829b36d)

**Comment by KJohnsn** [comment]
Spotted a smaller than usual registration mark (R) in this page: https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-news/2023/mack-trucks-features-mack-md-electric-and-lr-electric-trucks-at-act-expo-2023

**Comment by KJohnsn** [comment]
Noticed the registration mark being placed in a higher position next to the word Anthem in the Specs page.
https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/anthem/specs/


![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/e2d92592-2e34-45ae-b85d-ed6e7e52ffc3)

**Comment by shirin27** [comment]
Should fix #430

**Comment by markovukiceviccn** [comment]
This is a content issue, the code responsible for superscript is in place and working.
Anytime you notice a trademark or registered icons check are they actually suoer-script or just a part of Heading or any other type of text elements.

**Comment by markovukiceviccn** [comment]
I would close this, any objection?

**Comment by shirin27** [comment]
@girishdigrajkar could you re-test it?

**Comment by markovukiceviccn** [comment]
It was a publishing issue, sorry for the inconvenience. 
Changes has been published now https://www.macktrucks.com/

**Comment by girishdigrajkar** [comment]
Validated by marking  ®  & ™  as superscript in  https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/ and published ; Able to get the correct results:

@Kannan-CM , @Varunvolvo : Please note for the content update in macktrucks.com for all Registered and Trademark icons.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/bb81fd22-4347-4448-9de2-511e0c8bcaf4">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/1787ff35-99f9-407e-85da-b2f4895c5b73">

**Comment by manuel-vara** [comment]
@Kannan-CM please consider this one for this sprint.

**Comment by Kannan-CM** [comment]
We have a CSS applied for the Hero to add the registered mark:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/126496977/027e3a27-be48-40cc-a986-64ed2d22abdf)

**Comment by girishdigrajkar** [comment]
As discussed on call,  @manuel-vara to validate the above scenario mentioned by Kannan.

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG This one has not been resolved. Please add to the next sprint. Thanks!

**Comment by markovukiceviccn** [comment]
@Gonzalo-CG @BeckyMedlin 

This is the content issue.
The trademark and registered symbols **MUST** be marked as superscript text element.
That will output the `<sup>TM</sup>` in our markup which is a prerequisite for registered and trademark symbols to be styled properly.

**Comment by Joesturbo** [comment]
@Kannan-CM  - can you please validate any other placeholders with @Varunvolvo

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG @Kannan-CM  Can this one be closed now?

**Comment by Kannan-CM** [comment]
Hi Becky,

Yes, we are done with the Registered mark and working on and off updating the Trade mark.

Since it is a content issue we can talk through the progress with Teams ticket.


Kind regards,
Kannan C
CMS Services
