### ISSUE TITLE
Implement search UI to integrate new search API

### ISSUE THREAD

**Issue by Lakshmishri** [hlxsites/vg-macktrucks-com#171]
This is to get rid of search stax and implement from scratch the search UI.
This PR will include only search results and search in header without pagination and filters

**Comment by manuel-vara** [comment]
Writing down granular tasks defined by Lakshmi for reference: 
1. Search without filters and pagination (this includes connecting to API open search using graphQL)
2. Search in header
3. Pagination
4. Filters
5. Auto suggest

**Comment by girishdigrajkar** [comment]
Summary:
Bug #150 , #159 , #279 , #281 , #158 , #160  were raised as part of testing.
Major bug 281 is outstanding, other are already closed.
