### ISSUE TITLE
Bug: Minor : Bulldog Magazine listing page has extra blank space in between cards 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#174]
Steps:
1. Navigate to https://85-bulldog-magazine-listing-page--vg-macktrucks-com--hlxsites.hlx.page/drafts/andrei.balanescu/magazine/bulldog-magazine
2. Validate the page

Expected vs Actual:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/d93a14b0-5b86-4f52-ac08-13f6cc13ad54)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
