### ISSUE TITLE
Bug: Major: material safety sds info block does not have all language MSDS files

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#176]
**Steps**:
1. Navigate to https://128-material-safety-sds-info--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/parts/mack-parts/material-safety-data-sheets
2. Validate the MSDS files column 
3. Validate the Product name column

**Expected :**
1.  All the three languages should be displayed in MSDS files section:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4cf04864-9b04-47da-8232-868a1c03f2c4">

2. The Product Name should be inline and should not span on second line

**Actual:**
1. Not all language files are displayed
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/1d74cc53-cb8c-4c8b-a746-e5d1539c5325">

2. Product Name is not in single line which adds confusion along with parts numbers
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/ee64f1b6-ccda-4a80-8b1e-0e57e55164ac)

**Comment by jonatan-lledo-netcentric** [comment]
partially fix: I add the remaining _English_, _Spanish_ or _French_ words to be displayed. But because there are no more links, they won't become buttons

**Comment by girishdigrajkar** [comment]
Confirmed as fixed
