### ISSUE TITLE
Carousel card variants has white background for every item

### ISSUE THREAD

**Issue by TomaszDziezykNetcentric** [hlxsites/vg-macktrucks-com#177]
The Carousel block with the `card` variant has a white background for every item and arrow buttons if the page contains a card block.

<img width="1445" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/c5c36a81-2810-49e3-bd4e-0c5abc23d7a9">

Expected solution:
Carousel's items and arrows  should not have any background color

<img width="1359" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/f0a28c33-1365-44de-a310-da96018b34b2">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
