### ISSUE TITLE
Bug: footer links are missing

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-macktrucks-com#183]
For SEO reasons, the footer titles are changed from h1 to h3, because of that the footer.js script is broken now.
just needs to update the script to be able to find the titles again

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result hence, agree to the defect closure:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/30fb891b-155c-489e-81e1-28f2608ff6ed">
