### ISSUE TITLE
Bug: Major: Truck Features pages - Navigation icons not reachable

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#191]
It seems to be an issue with the path to locate icons folder.
<img width="1664" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/46764f20-9e73-491d-8e15-274f3e520c02">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/6c877b6f-d1e1-4f07-811e-0712d3ca7f4a">
