### ISSUE TITLE
Bug: Minor - Magazine articles template - Styling on Categories tagging button on hover is absent

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#193]
On the Magazine Articles template, when hovering over the Categories tagging button from the Magazine article - there is no styling

**Steps to reproduce:**
1. Go to on of the Magazine article templates on the live website ( for ex https://www.macktrucks.com/magazine/articles/2023/january/crmp-inc/ )
2. Hover over the Categories tagging button on the template ( for ex on Customer Profiles on the article) 
3. Go to https://41-magazine-articles-template--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/magazine/articles/demo-110523/bulldog-bits-gold-rush and repeat steps 2 and 3
4. Notice that the styling over the Categories tagging button when hovering is missing

**Expected result**
Categories tagging button should have a different styling on hover (see left side of the screenshot)

<img width="1602" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/a76dc26b-ebd5-4937-82c6-916ec1cce4a3">

**Actual result**
Hover styling is lacking over the Categories tagging buttons (see right of the screenshot)

<img width="1602" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/e5c3153e-684f-405a-8fcd-2ab0544dbe0f">

#41

**Comment by jonatan-lledo-netcentric** [comment]
in main branch is already working
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/magazine/articles/demo-110523/bulldog-bits-gold-rush

**Comment by girishdigrajkar** [comment]
Validated on main branch and it is working fine so closing the defect :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/cabb91bc-9372-4048-866b-b6045989cd30">
