### ISSUE TITLE
Bug: Major - Magazine article template - Categories tag button does not work

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#194]
On the Magazine article template, clicking on the Categories tag button does not open anything

**Steps to reproduce:**
1. Go to https://41-magazine-articles-template--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/magazine/articles/demo-110523/bulldog-bits-gold-rush
2. Click on the In The Know button
3. Notice that nothing happens

**Expected result**
Clicking on the Categories button should open the page with the list of Magazine articles from that respective category
<img width="1261" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/385bbba5-e974-4cbd-bc5b-f9b57ba3b044">

**Actual result**
Clicking on the Categories button does not open any page

#41

**Comment by jonatan-lledo-netcentric** [comment]
in main branch is working
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/magazine/articles/demo-110523/bulldog-bits-gold-rush

**Comment by girishdigrajkar** [comment]
Validated on main branch and able to get the correct results and hence, closing the defect.
