### ISSUE TITLE
Bug: Major - Magazine Article template - Social media toolbar from the bottom of the Article template do not work

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#195]
On the bottom of the Magazine Article template - the buttons on the Social media toolbar (Email, Tweet, Like) from the bottom of the page do not work

**Steps to reproduce:**
1. Go to https://41-magazine-articles-template--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/magazine/articles/demo-110523/bulldog-bits-gold-rush
2. Scroll down to the Social media toolbar to the bottom of the article and click on the buttons
3. Notice that it does not open anything

**Expected result**
The Social media toolbar buttons (Email, Tweet, Like) should open their respective sharing platforms
OR
remove the social media toolbar buttons from the bottom of the Article as we already have one at the beggining of the Article that it is working (?) (added question label )

**Actual result**
The buttons on the Social media toolbar from the bottom of the Article do not work

<img width="1261" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/a27bb79b-6362-4940-89c4-83c5ebe05595">

#41

**Comment by jonatan-lledo-netcentric** [comment]
in main is working
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/magazine/articles/demo-110523/bulldog-bits-gold-rush @Andrei-Boiangiu

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
