### ISSUE TITLE
Bug: Minor - Magazine article template - Recommendations (based on your reading) blocks are displayed vertically not horizontally

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#196]
On the bottom of the article page, the Recommendations section (based on your reading) has the blocks arranged vertically instead of horizontally

**Steps to reproduce:**
1. Go to https://www.macktrucks.com/magazine/articles/2023/january/crmp-inc/ and scroll down to Recommendations (Based on your readings, you might like this)
2. Repeat step 1 for https://41-magazine-articles-template--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/magazine/articles/demo-110523/bulldog-bits-gold-rush
3. Notice that the blocks are arranged differently

**Expected result**
The blocks should be arranged horizontally (? question label added ) - see left side of screenshot

<img width="1840" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/c106af76-f1b2-4b33-ba78-4d0c757a5653">

**Actual result**
The blocks are arranged vertically - see right side of screenshot

<img width="1840" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/801773c0-1398-4af8-953f-69880cd3a688">

#41

**Comment by BeckyMedlin** [comment]
This will change with redesign work. This can be closed per @WendyKruger

**Comment by Andrei-Boiangiu** [comment]
closing as per above comment
