### ISSUE TITLE
Dealer locator block: trigger search from url with zipcode parameter

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#206]
When Dealer Locator url is called with the `l` parameter as zip code the map search should be triggered. Currently the input field is populated but search is not launched.
http://localhost:3000/buy-mack/find-a-dealer/?l=27045
<img width="1549" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/2761a37e-710f-4542-ba12-44103fafef4e">

**Comment by girishdigrajkar** [comment]
Bug 224 is closed now and hence, this ticket 206 could be marked to done.
