### ISSUE TITLE
Find a Mack Dealer section

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#21]
Find a Mack Dealer section with background that includes an input field to call Dealer Locator with postal code as param.
<img width="1576" alt="FindMackDealerSectionForm2" src="https://user-images.githubusercontent.com/116451851/225297403-e68d7588-b706-4f5a-be49-10358f29e2b4.png">

**Comment by synox** [comment]
btw, the dealer page does not currently use the zip code https://www.macktrucks.com/buy-mack/find-a-dealer/?l=94103
