### ISSUE TITLE
Bug: Major: Mobile: Extra space observed in Carousal block for mobile viewport

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#232]
Steps:
1. In Mobile Viewport, Navigate to https://153-carousel-fixes--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/carousel 
2. Validate the Carousal block

Expected vs Actual:
Extra space has been observed at the bottom of Carousal block

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/a40c4df5-88b9-477b-ab26-4e16cf7e52fb)

**Comment by jonatan-lledo-netcentric** [comment]
in main branch is already fixed
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/carousel

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed on both
 https://153-carousel-fixes--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/carousel
 and
 https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/tdziezyk/carousel
