### ISSUE TITLE
Bug: Firefox doesn't load the dealer list

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-macktrucks-com#235]
open a Firefox browser
go to https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/find-a-dealer/
input a zipcode: 10001 e.g.

expected:
show the spot in the map and fill in the list

current:
console logs an error and stops the code, nothing happens in the map and no list also

![Screenshot 2023-06-14 at 17 55 16](https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/990dee6e-76fc-4b4a-ac6a-2393353211b8)

![Screenshot 2023-06-14 at 17 58 42](https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/10d4c122-2a9d-457f-bed0-c0564af55ab0)

**Comment by shirin27** [comment]
@Joesturbo @ZoeBeykirch @Kannan-CM retest the issue, and if fixed, we can close the ticket

**Comment by BeckyMedlin** [comment]
@ZoeBeykirch Please validate. Thank you!

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG Is this still an issue? Zoe is unable to validate using Firefox. Thank you!

**Comment by Gonzalo-CG** [comment]
I couldn't validate it either, works fine for me. @jonatan-lledo-netcentric could you try it again just to be sure? I'll close it if it works ok now 😃

**Comment by jonatan-lledo-netcentric** [comment]
even if the error is partially fixed, it also doesn't work in Firefox. But if a minority of users use this browser, we can say that it is not supported
<img width="1790" alt="Screenshot 2023-10-03 at 11 12 20" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/6e96ee3c-6df7-4869-9fa5-391c550605fe">
