### ISSUE TITLE
Bug: Major - Columns (Promo) - Adding more than one URL on the Columns block text section will cause the other URLs to be displayed in an incorrect styling

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#238]
When creating a Columns (Promo) block and adding more than one URL 
<img width="1622" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/1c2b933f-3f33-49b6-aae7-e6d842a1e9ce">

then the other URL will be displayed in an incorrect styling without the button margin, just red text on the black background that becomes invisible on mouse hover

<img width="1622" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/5d16d3e9-6d9c-487a-ae86-1437acb5e003">

<img width="1622" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/f362b048-801e-4b9b-a371-e47a4fe29f95">

**Steps to reproduce:**
1. Create and configure a Columns (promo) block that has more than one URL in the text field
( for example the first column from the Columns Promo block here: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B72E28F82-75D5-409A-96E4-F913F309A134%7D&file=index.docx&action=default&mobileredirect=true )
2. Preview and notice the styling of the URLs on the Column

**Expected result**
URLs should be correctly styled and displayed as buttons

 **Actual result**
 At least one URL is incorrectly displayed as red text that becomes invisible on mouse hover when more than one URL is added to the Columns (Promo) text section 
 
 - see above screenshots

**Comment by jonatan-lledo-netcentric** [comment]
How I fixed it:
1- I previewed the document
2- I opened the inspector to check how it looks the HTML
3- I found a _br_ tag
4- I went back to the document
5- I removed the space between the links to check the new result
6- It's already fixed, because "magic" 🤷🏻‍♂️
