### ISSUE TITLE
CR: Bulldog Magazine Truck model is empty in magazine categories (Blank)

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-macktrucks-com#241]
on the bug #216 there was a gap in the display of an article if it was not tagged to a truck model. A blank placeholder was being put in place to address this issue.

Change request:
Add a default "Mack Trucks" tag for an article: 
Icon will be a small bulldog (need dimensions for icon).

**Comment by ZoeBeykirch** [comment]
Closing ticket as it is no longer needed with redesign changes, as the truck model tag will not be visibly displayed - now will only be a backend filter functionality.
