### ISSUE TITLE
Custom select

### ISSUE THREAD

**Issue by TomaszDziezykNetcentric** [hlxsites/vg-macktrucks-com#25]
Currently, the default browser select is used. To consider if the custom one is needed.

<img width="899" alt="obraz" src="https://user-images.githubusercontent.com/125962117/225829581-ba4bd287-bacc-4a54-9cc7-a5128324f56f.png">

**Comment by girishdigrajkar** [comment]
As discussed with  Tomasz, this is still in development so, assigning it back to dev.

**Comment by verareljic** [comment]
Please confirm that this ticket can be in the backlog for now. @ZoeBeykirch
