### ISSUE TITLE
Fix: title in magazine categories hero

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [hlxsites/vg-macktrucks-com#256]

**Comment by girishdigrajkar** [comment]
The title in magazine categories hero n mobile viewport looks correct now and hence, this bug is confirmed as fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/8a2d5ee5-7c44-4c58-b202-5560891cc907">
