### ISSUE TITLE
Bug: Major: Mobile The 'Uptime Preferences & Contacts' form i.e. ota-registration iframe is not displayed in case of mobile/tablet however is displayed in case of desktop 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#261]
Steps:
1. Navigate to https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-connect/connected-support/ota-registration/
2. Validate the same URL in mobile/Tablet view port
3. Also validate the fonts

Expected vs Actual:
1. The iframe is not displayed on mobile/tablet    2. Font is not correct for form title
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/0729911c-4e62-478e-9897-35c54eabcfc2)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4a2dbe43-399b-439d-aaf4-bcc7a10c2720)

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/189f2a2d-a7ce-43c9-af92-63506de39b8d">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/5e0097ca-0995-4e5b-945e-8f0dcfa0d56a">

**Comment by TomaszDziezykNetcentric** [comment]
@girishdigrajkar 

1. As discussed the problem with rendering the form on mobile is on the Alchemer side. It looks like they prevent rendering the form on mobile. The fix should be done by somebody who is responsible for the Alchemery form creation/configuration.
2. We are using the newest font version for the heading. The latest version doesn't contain a bolder option so the one that is displayed now is the best that we have. We are using this heading style for all H1 headings in the whole app.

**Comment by girishdigrajkar** [comment]
Hi @ZoeBeykirch,
As discussed on call yesterday, could you please see above comment and confirm.

**Comment by ZoeBeykirch** [comment]
@girishdigrajkar Confirming this is not Go-Live critical as the form doesn't work with mobile on production today. I will work with our internal teams to correct the form on our side.

**Comment by Joesturbo** [comment]
@girishdigrajkar  @ZoeBeykirch  - can you re validate on the testing tool. It had a setting that was not responsive. I have adjusted and it should work ok overall.

**Comment by ZoeBeykirch** [comment]
Validated the form is now working as expected on mobile view for production and pre-production sites!

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
