### ISSUE TITLE
Bug: Minor - Columns (info) - Franklin is not able to check if the titles are links and is unable to add the underline and a console error is displayed

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#263]
When configuring the titles as links on the info variant of the Columns block, there is no underline or ability to check if the titles are links and a console error is displayed

example of such a configuration on the Columns (info) block on the following page (with anchor links)
https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BFFB83094-E49B-407E-AE8E-6812C22F96E4%7D&file=index.docx&action=default&mobileredirect=true&cid=3e2266f6-229d-447b-b355-9dec8da54db8

https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/sustainability 

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/10baa924-44e3-4b09-bc1d-1cfd63a96843)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/e40a60de-2b8f-429a-a3a8-af3a32cc2a0c)

**Comment by ZoeBeykirch** [comment]
Confirmed with Product Owner this is not Go-Live critical. Can add this to the backlog as a low priority for potentially being developed in the future, but the re-designs should be prioritized over this.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
