### ISSUE TITLE
Bug: Major: Mobile: The 'contact-us-form'  iframe is not displayed in case of mobile/tablet however is displayed in case of desktop

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#265]
**Steps:**
1. Navigate to https://main--vg-macktrucks-com--hlxsites.hlx.page/about-mack/contact-us/contact-us-form/
2. Validate the same URL in mobile/Tablet view port
3. Also validate the fonts

**Expected vs Actual:**
1. The iframe is not displayed on mobile/tablet 2. Font is not correct for form title & description / not bold styled

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/567f9818-c36a-4bba-a0d5-48c9cd8253fc)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e7563a50-f218-4cf4-aac9-1302df722188)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/aac234d1-acd2-43eb-9b67-8a8663f463d3)

**Comment by TomaszDziezykNetcentric** [comment]
1. Fixed - the form should be displayed now
2. We are using the newest font version for the heading. The latest version doesn't contain a bolder option so the one that is displayed now is the best that we have. We are using this heading style for all H1 headings in the whole app.

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
