### ISSUE TITLE
Create all missing subnavs and keep in sync metadata file 

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#268]

**Comment by andreibalanescu** [comment]
This has been done.

**Comment by Andrei-Boiangiu** [comment]
04. trucks -> lr-series -> specs
https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA366CAF4-F7B3-460D-B596-5C762DF2D4AA%7D&file=index.docx&action=default&mobileredirect=true

has a wrong metadata that seems to be for Powertrain Engines

**Comment by andreibalanescu** [comment]
This has been fixed and published. Ready to be tested.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
