### ISSUE TITLE
Bug: Medium: Update body-builder-news index

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#269]
Need to update helix-query.yaml file with:

- og:description instead of summary
- lastModifiedDate instead of publicationDate metadata not currently available in this type of new

Related with #63

**Comment by girishdigrajkar** [comment]
Confirmed with Manuel for latest implementation and LastModifiedDate & Description content is used in feed.
Confirmed as Fixed

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/9eb43056-8548-424d-911b-b8807ed40221)
