### ISSUE TITLE
Bug: Minor: Extra label is displayed in humberger menu for Subscribe to Bulldog magazine 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#271]
Steps:
1. Navigate to https://209-bulldog-modal--vg-macktrucks-com--hlxsites.hlx.page/magazine/
2. Click on humberger menu 
3. Validate the screen

Expected vs Actual:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/2d06bf75-95ae-411c-a8b6-396c3e78000e)

**Comment by TomaszDziezykNetcentric** [comment]
@girishdigrajkar the fix is ready to test here: https://main--vg-macktrucks-com--hlxsites.hlx.page/magazine/

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
