### ISSUE TITLE
Improve contact-us app buttons

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-macktrucks-com#275]
there is no way to convert the image buttons so I tested how to implement and fix the current behavior
<img width="1044" alt="Screenshot 2023-06-21 at 17 07 36" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/096aabe0-ced2-4547-8723-31b4c2800568">

NOTE: This is a screenshot of how will look after some tests in my local

I already add a theme medatada and the only remaining thing is add the icons and a few CSS lines to do the trick

**Comment by girishdigrajkar** [comment]
confirmed as fixed :
Links works fine .. 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/89bf9d11-df23-483d-9852-93abf10140ff">
