### ISSUE TITLE
FR: Cards Block - Remove deprecated variation from the Library

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#277]
**Description**
As a content editor, I want to only be able to select from the library the cards variations that are in line with the business needs and the design of the website.

**Acceptance criteria**

- **Editor AC**
-- The Cards(rise-on-hover) variation can no longer be visible in the Library.

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/135319298/b64aa0ac-98d9-4a46-b557-8048c5ca3642)

**Comment by ZoeBeykirch** [comment]
Yes - confirmed that we can remove deprecated variation from library for the cards rise on hover feature.

**Comment by Andrei-Boiangiu** [comment]
it is still present in the Library

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/5845f2a1-6362-4b72-9851-a2a677954dc7)

**Comment by ZoeBeykirch** [comment]
@Andrei-Boiangiu Can you remove this block from the library, or assign to someone else who can? I'm not sure how to do this, but have confirmed with our team we can remove this. Thanks

**Comment by Andrei-Boiangiu** [comment]
confirmed by @SantiagoHomps-NC  as removed from Library

**Comment by andreibalanescu** [comment]
I already did the change by removing this one and adding the available variations and published. Should be fine now. 
<img width="902" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126146302/e3edcd46-01b9-4bc0-9a1e-ee183db052b7">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/4f953c02-5be9-4c21-acc7-da74456ead2a)
