### ISSUE TITLE
Bug: Major: User is unable to navigate through all searched records in case of multipage results

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#281]
**Steps:**
1. Navigate to https://main--vg-macktrucks-com--hlxsites.hlx.page/
2. Click on search icon and enter 'Mack Trucks EV' 
3. Click search 
4. On the displayed results page, scroll down and try to navigate through results until end

**Expected vs Actual:**
Not able to go beyond second page;  URL parameter start is set to 25 incorrectly which prevents further navigation.

**Note:** Additionally, delete the keyword and search again; The results page still has record number displayed in pagination link.

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/a8a27dac-cb7e-4dee-bdab-8554b6c9f441)

**Comment by jonatan-lledo-netcentric** [comment]
will be fixed in PR #283

**Comment by girishdigrajkar** [comment]
The pagination navigation still has issues as on last page of results the 'Next' link is not disabled and thus, it hinders the count of results displayed.
Reopening the defect.

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
