### ISSUE TITLE
Bug Minor - Cards wrong rendition 

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#289]
I've found an issue where Cards blocks doesn't render properly:
1. Go to https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B92F5C909-3337-433C-BC1C-67ABBAC846B1%7D&file=index.docx&action=default&mobileredirect=true&cid=91ffadda-9913-4ef9-9af0-271ae8495595
2. Preview page
3. Scroll to Cards and observe the issue
4. Refresh the page and observe the issue is temporary fixed. 

<img width="1462" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126146302/f9467c81-f1a1-4c6e-92ca-30f78ba5f858">

**Comment by verareljic** [comment]
Fixed since behaviour is not happening anymore.
