### ISSUE TITLE
Accordion block variation

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#29]
There is a need of an accordion block variation which should contain columns and specifications like here:
https://www.macktrucks.com/parts-and-services/parts/mack-parts/transmission/
![image](https://user-images.githubusercontent.com/126146302/226948017-556c2c68-8a9f-4dad-acce-23ab54a30241.png)

**Comment by Andrei-Boiangiu** [comment]
tested with no outstanding issues
