### ISSUE TITLE
Spec Table Full Width

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#290]
We have an issue, where Spec table won't be full width if is not part of Accordion block.
1. Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/suspensions/twin-y-air/ 
2. Check the table at the bottom
3. It needs to be full width
<img width="1359" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126146302/7f1e6fcd-41ff-4eb8-bed0-aa049a14607e">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed

<img width="1535" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/ac9d4ac1-909e-4a7d-8a5c-9206c16354fe">
