### ISSUE TITLE
Bug: Major: Cards CTA block cards are overlapping each other and the next block

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#292]
Steps:
1. Navigate to https://main--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/engines/
2. Validate the cards section

Expected vs Actual:
Cards CTA block cards are overlapping each other and the next block :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/aa06f278-eabf-4f32-9b8c-fea47e5adc0a">

**Comment by jonatan-lledo-netcentric** [comment]
test page:
https://292-cards-block-overlapping--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/engines/

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/0f9a248e-27c9-428f-a08b-565bd823f93d">
