### ISSUE TITLE
Use Element.closest() instead of getTargetParentElement()

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-macktrucks-com#294]
I saw your [getTargetParentElement = (el, option) ](https://github.com/hlxsites/vg-macktrucks-com/blob/d48ba0c44b73ba2ea9baaf1a3f335d68bec57793/scripts/scripts.js#L468-L484)function. I did not study it in detail, but it sounds a lot like [Element.closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest). closest() is probably more efficient and well documented. 

There are 2 similar functions:
-  getTargetParentElement, used in hero.js & columns.js
-  getParentSection, used in cards.js
both can be removed and changed by its equivalent closest()

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed;
