### ISSUE TITLE
Testing: Site testing

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#296]
Task for all the testing activities related to the go-live of macktrucks.com

**Comment by shirin27** [comment]
Sample pages (more would be nice, but highest prio):

- Homepage
- Trucks section
- Powertrain pages
- Dealer locator

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd Does this one need to be moved to a future sprint? backlog?

**Comment by girishdigrajkar** [comment]
This task is completed except for outstanding defects which will be tracked individually hence, marking this to done.
