### ISSUE TITLE
Accordion block

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#30]
There is a need for an Accordion Block for FAQ
![image](https://user-images.githubusercontent.com/126146302/226972070-7cc07a31-15da-4f5b-8c20-cfeb6585b768.png)

https://www.macktrucks.com/parts-and-services/support/faqs/

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result hence, agree to closure.
