### ISSUE TITLE
Bug: Medium. Anthem Features Hotspot config content missing

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#302]
<img width="1665" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/b08f8bdd-340d-459d-9ef0-284ca10a6995">
Clicking into this one will not work, seems some content is missing.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
