### ISSUE TITLE
Bug: Minor: H2 Title is Misaligned on Home Page 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#308]
Minor misalignment on the Community H2 title on the bottom of the home page. In production the Community H2 title comes right above the first Read Magazine tile image, however on the pre-production it's awkwardly placed all the way to the left. If we can't move it to be above the first image block, I think it would look better completely centered as a title. 

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/e91be13e-691a-4bef-8406-81cdeb0a9940)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/a2518677-70cf-4b3f-b0a6-d5975351f419)

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4bff8428-c6bc-4052-8b4a-56a2ed4675e6">
