### ISSUE TITLE
Bug Minor: Footer is Missing a link, some info needs to be re-ordered

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#309]
There's a minor difference between the information displayed in the footer comparing UAT to production. In production, it's ordered to the first picture and includes Mack Contests which is missing from the UAT site - https://www.macktrucks.com/contests/

The order links displayed under the Discover Mack should be:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/aa615bd7-8008-41b0-b921-e08592183d92)

Compared to UAT:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/8b854b21-46da-495c-91a3-ccd51c9130a7)

**Comment by manuel-vara** [comment]
Removed to avoid 404 error because it seems this page has not be migrated according to the migration list. Please let us know otherwise.

<img width="381" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/de2a8aeb-4df1-4b97-ad55-eb998739762d">

**Comment by jonatan-lledo-netcentric** [comment]
I rearranged the link list to match the production
<img width="722" alt="Screenshot 2023-06-28 at 09 26 47" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/ce96f1a5-c08f-4e28-965d-eca2f72f8d24">
maybe also need a little bit of extra spacing between the items, but is an easy styling fix

**Comment by SantiagoHomps-NC** [comment]
Done

**Comment by KJohnsn** [comment]
Seeing 404 issues with other footer links. The names in the footer which have broken links are: Mack Contests, SDS Info, and Events.
<img width="915" alt="Mack Footer" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/a5b475b2-19e8-4ac1-a966-a3541a7117dd">
<img width="925" alt="404-contests" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/a95d601c-8148-49a1-8def-bb0732b16f0c">

**Comment by Andrei-Boiangiu** [comment]
404 pages are still displayed when clicking on the SDS Info and Mack Contests links from the Footer

**Comment by jonatan-lledo-netcentric** [comment]
except for /contest folder, the other links are working, because contest folder was not migrated, so if we want to avoid a broken link is better if we remove that link, or create the contest page

**Comment by Andrei-Boiangiu** [comment]
Mack Contests link is working and opens https://www.macktrucks.com/contests/
but SDS Info link from footer still displays 404 page missing

**Comment by Andrei-Boiangiu** [comment]
SDS Info now opens https://www.macktrucks.com/parts-and-services/parts/mack-parts/material-safety-data-sheets

confirmed as fixed
