### ISSUE TITLE
Bug Minor: Font size and type inconsistencies

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#310]
There are inconsistencies on the font sizes for the main navigation bar and hero text components. The Mack Trucks digital product owner confirmed that we need to match what is live on production today on the font sizes for Go-Live - just keeping the size matched to what's on production. 

Here's the Mack Core Design Kit to reference - https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=6-1556&mode=design&t=xHGobqwvRNPHFoLw-0

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/f3de1092-c7f6-4575-bd99-cb830eefb146)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/fc918cfa-38dd-41fa-bc3e-ef6d06b3cd2d)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/3033c8e8-3fb3-4f0b-9ce1-bf0302c6e3d8)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/6a4ebbdf-39a9-4c1f-afbe-24a014feb2e3)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/b8ae2b87-2a8a-4424-8c1c-6240b261e815)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/6b4a7516-5a06-4240-8d3a-9d7563489acb)

**Comment by Andrei-Boiangiu** [comment]
partially fixed

font size and type in the Header main navigation bar is fixed

but the font for Hero images is different

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/0b2bf9e3-fe98-4b90-962c-5e28d7b1007d)

**Comment by Andrei-Boiangiu** [comment]
As discussed with @jonatan-lledo-netcentric , the font size is not change as to keep to consistency on the website - just the font family

but

the Font family in the Header navigation bar is _Helvetica Neue 85 Heavy_ **instead of** _Helvetica Neue 75 Bold_ as displayed in the Description

**Comment by jonatan-lledo-netcentric** [comment]
<img width="1241" alt="Screenshot 2023-07-17 at 18 01 33" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/f4288ecc-d39a-4847-b85d-b9380d906a28">
<img width="1253" alt="Screenshot 2023-07-17 at 18 01 48" src="https://github.com/hlxsites/vg-macktrucks-com/assets/117984204/3a103b27-0118-4764-8838-696c42625e20">

as you can see, legacy site and production share the same font files (with a little naming difference). maybe you mean the mobile version @Andrei-Boiangiu ?
