### ISSUE TITLE
Bug: Medium: Search results page shows incorrect pagination in case there are no search results 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#314]
Steps:
1. Navigate to https://main--vg-macktrucks-com--hlxsites.hlx.page/
2. Click on search icon and try to search "random" and validate the result page
3. On the displayed page with no results the pagination should be correctly displayed  ( e.g.      < Previous]1 — 0 of 0     i.e. same as legacy site)

Expected vs Actual:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/867d3206-d459-4f3b-84e8-fb6b0233525b)

Legacy site :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/cf0dd48a-ab2a-4d08-b17d-c4bbe0adb281">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
