### ISSUE TITLE
BUG: Mack SUB NAVIGATION NOT WORKING

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-macktrucks-com#316]
I found two pages (that actually work in preview) but the sub navigation bar (going to the proper page) does not wrk it displays a 404

. located here - diagnostic tools and also uptime dealers. https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/uptime-solutions/

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/122567401/d5ca07b7-895e-455e-9978-0d872925a945)

**Comment by manuel-vara** [comment]
Fixed. Please retest. 
Sub navigation in Coverage Plans visible as well.

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
