### ISSUE TITLE
Bug: Major: Hero image does not scale

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#317]
<img width="388" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/f93752a6-a9b5-4b27-8734-e5f5a8a1a0dc">

**Comment by girishdigrajkar** [comment]
For many instances the image is scaled yet the text is not scaled accordingly  : 
1. For https://317-hero-image-does-not-scale--vg-macktrucks-com--hlxsites.hlx.page/trucks/md/ 
Text in Hero video/animation is not correctly displayed: 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/5df63997-9108-4d98-b685-a01083efb6f1">

2. For https://317-hero-image-does-not-scale--vg-macktrucks-com--hlxsites.hlx.page/mack-connect/   observed text related issues:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/91343ec8-39c1-46b0-8a80-6f0643c33c7d">

3. For https://317-hero-image-does-not-scale--vg-macktrucks-com--hlxsites.hlx.page/mack-connect/connected-business/ :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/2d448831-cc82-43a3-9ece-dc8bd8708563">

4.  For https://317-hero-image-does-not-scale--vg-macktrucks-com--hlxsites.hlx.page/mack-connect/connected-driving/ :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/559845e2-1031-4e56-9d65-e197870c428f">

5.  for https://317-hero-image-does-not-scale--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/exhaust-aftertreatment-systems/cleartech-system/ :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/94486d1f-1595-44df-b938-f94ef4edfec2">

6. For https://317-hero-image-does-not-scale--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/suspensions/ :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e4366cf3-a80d-41a8-b150-3f778aac7990">

7. For https://317-hero-image-does-not-scale--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/suspensions/mride/ :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b4d07308-a3ea-4d51-ab19-dc7e84dbc0e2">

**Comment by Andrei-Boiangiu** [comment]
07. Powertrain and Suspension -> Overview
https://www.macktrucks.com/powertrain-and-suspensions/

<img width="862" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/4fafa66c-49e7-4c46-bd02-4b4fdda51cf4">

**Comment by Andrei-Boiangiu** [comment]
08. Powertrain: Engines: MP7
https://www.macktrucks.com/powertrain-and-suspensions/engines/mp7/ 

<img width="1282" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/73a94a3e-1456-42e3-9dde-d013b3ce2147">

09. Powertrain: Engines: MP8
https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8/

<img width="1282" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/3bc3724d-e913-42ab-b189-d99209706678">

**Comment by TomaszDziezykNetcentric** [comment]
Pages that will need republish after the PR merge (the part of the fix was updating the content):

    https://main--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/exhaust-aftertreatment-systems/cleartech-system/
    https://main--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/suspensions/mride/
    https://www.macktrucks.com/powertrain-and-suspensions/engines/mp7/
    https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8/
    https://www.macktrucks.com/powertrain-and-suspensions/engines/cummins-l9/

**Comment by girishdigrajkar** [comment]
Summary:
1 to 8 :  Confirmed as Fixed
9, 10 :  Retest Failed ;  " Power Train > Engines"   pages except the 'MP7' needs a fix as titles are not as expected legacy site behavior  

Hence, Reopening the defect.

**Comment by manuel-vara** [comment]
I've republished pages:
https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8/
https://www.macktrucks.com/powertrain-and-suspensions/engines/cummins-l9/

Please retest them.

**Comment by girishdigrajkar** [comment]
Hi @manuel-vara :  Thanks for re publishing pages it works fine now.
However, As mentioned in latest comment  Powertrain's remaining pages i.e. mp8he, scr needs a fix, please see below:

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/d9df1725-6cfb-4062-9e5d-78a6570360e9">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/116df3d7-c9bf-491f-8823-47c85d62a8a4">

**Comment by TomaszDziezykNetcentric** [comment]
@girishdigrajkar the https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8he/ is fixed
On the https://www.macktrucks.com/powertrain-and-suspensions/engines/scr/ page, there is no hero banner to fix. There is just a text so it is out of the scope of this issue.

**Comment by girishdigrajkar** [comment]
Thanks @TomaszDziezykNetcentric for the update.
Confirmed as Fixed;  Closing the defect as now Hero image scale works fine.

SCR page issue will be tracked in separate bug.
