### ISSUE TITLE
Bug Minor: iPad - Homepage text

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-macktrucks-com#322]
on the homepage the section for the truck listing has a text issue on a tablet device.

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/122567401/966240ee-2e49-40b3-aefb-6f4656a82034)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
 
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/c916a203-0fc4-43b2-837e-c745668d55bd)
