### ISSUE TITLE
Bug: Minor: Null Error Message on Transmission page

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#324]
At the bottom of the page where it should say Download Additional Information, it only shows "Null". 
https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/parts/mack-parts/transmission/
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/b61b1df3-9add-441c-8ff1-14b0f049e571)

Compared to production: 
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/a6a3a859-ae28-42ba-9549-722615f4adfd)

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/5e8a92c2-6120-40a0-9e8c-09329712cdda">
