### ISSUE TITLE
Content Missing: Software Options Block on Transmission Page 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#325]
The Software Options Block is missing from the Transmission Page, seen in the below screen shot of production. 

https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/parts/mack-parts/transmission/
https://www.macktrucks.com/parts-and-services/parts/mack-parts/transmission/

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/18abde24-fd66-4550-a70c-6716e0bd0b1c)

**Comment by andreibalanescu** [comment]
This has been done
