### ISSUE TITLE
Post GoLive Bug Critical: Card stack overlap on Mack Certified Used Trucks page

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#326]
**URL:** https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/mack-certified-used-trucks/
Tested on BrowserStack on iPhone 13

**Steps to test**
- Go to Chrome browser on the latest iOS on iPhone 13
- Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/mack-certified-used-trucks/
- Scroll down the page

**Expected behavior**
The cards on the page are separated and stacked vertically with proper spacing and font styling.

**Actual behavior**
The cards appear to overlap and the copy isn't visible to the user

Screenshot
![Card overlap on Mobile](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/3278b9ec-ef22-4be8-b3f1-69b20383bcb3)

**Comment by KJohnsn** [comment]
On mobile view, the Powertrain section has some card overlap issues, text overlap issues, and page width issues.
URL: https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8/

![MicrosoftTeams-image (1)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/26f2a89d-53a8-476d-9a1e-c0b7135b09ce)
![MicrosoftTeams-image (2)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/415e0600-7248-4cfc-bff4-3eb298043a14)
![MicrosoftTeams-image (3)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/0e5b797f-3bd5-42a2-ba17-53d955ef2c5f)
![MicrosoftTeams-image (4)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/b192ebc5-cec4-4a8d-beea-4c0482773a72)
![MicrosoftTeams-image (5)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/4dee81c2-0a94-4360-8bed-a07f39d108ff)
![MicrosoftTeams-image (6)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/b8f459ec-4630-40af-aa95-1cbb42127f86)

Text overlap of hero image: https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8he/
![MicrosoftTeams-image (7)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/3eb2835a-0433-4b59-90b6-aedf4caf19a6)

**Odd page width overlap**
![MicrosoftTeams-image (8)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/5fe24768-1de3-4f5f-9cd4-8dfebe170378)

**Comment by KJohnsn** [comment]
The above tests were done on Edge on iOS. In Safari, the pages render a bit better.

**Comment by Andrei-Boiangiu** [comment]
partially fixed

Cards stack are correctly displayed now but the issues pertaining the Powertrain: Engines: MP8 page are still present

see also

**Comment by girishdigrajkar** [comment]
Reopening the defect as this defect is partially fixed :
Issues observed are blank space, card overlap
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b1171a08-a88c-444b-8426-3fc835836ecb">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/77a4aa2e-ce49-4acb-aec1-53c5c8f6fad5">
=======================================================================

Below issues are fixed successfully :
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/bf53dd77-45fe-40b3-be22-116dff960e4f">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e2f2c57a-4d9a-46a8-bf47-18ba79f667fa">

**Comment by girishdigrajkar** [comment]
This bug is open for only below outstanding issue, rest all the issues are closed already:
Blank space noted :
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/426822e6-0c1b-41f1-bc55-560123a88951">

**Comment by Andrei-Boiangiu** [comment]
Minor issue #418 has been opened separately for the remining item
