### ISSUE TITLE
Bug Major: Content - Overhaul CTA opens a 404 page

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#327]
**URL:** https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/parts/mack-parts/engine/
**Browser:** Chrome v.114.0

**Steps to test**

1. Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/parts/mack-parts/engine/
2. Scroll down the page to "Overhaul"
3. View the "Learn More" CTA
4. Click on it
5. Wait for the page to load

**Expected results**
The CTA opens the Overhaul page

**Actual results**
The CTA opens a 404 page

**Screenshots**
![Mack-Engine page](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/4f1a1bd8-e023-450d-ae1d-6c072d325c2e)
![Mack - Overhaul - 404](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/830cb27c-0393-4eb6-b3e7-365fc787346b)

**Comment by andreibalanescu** [comment]
This has been fixed,.
