### ISSUE TITLE
Bug: Hotspots are misaligned

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#328]
**URL:** preview: https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/md-electric/
Live: https://www.macktrucks.com/trucks/md-electric/
**Browser:** Chrome v.114.0

**Steps to reproduce:**
Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/md-electric/
View MD Electric hero
Review the hotspots around or on the vehicle

**Expected results**
The hotspots are lined up specifically in the areas which they are indicating

**Actual results**
The hotspots appear to be floating or in arbitrary locations around the vehicle

**Screenshots**
![Preview hotspots](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/8cf0d7ce-5f99-4937-b002-5b456f709313)
![Live hotspots](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/a0e35a39-b6ef-4157-92e3-c80489ad5fd8)

**Comment by Andrei-Boiangiu** [comment]
still present on macktrucks.com

<img width="1611" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/572a8952-d9c3-4127-a324-3a04c68057ac">

**Comment by SantiagoHomps-NC** [comment]
> still present on macktrucks.com
> 
> <img alt="image" width="1611" src="https://user-images.githubusercontent.com/127409602/250128078-572a8952-d9c3-4127-a324-3a04c68057ac.png">

forgot to publish but now its done

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed on Live

<img width="1565" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/42df236a-8697-474b-92a4-9306bff5f0ce">
