### ISSUE TITLE
NFR: Implement Mack Hotjar Code

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-macktrucks-com#331]
Mack Code:

<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:597204,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by shirin27** [comment]
To be tested as a performance cookies related script

**Comment by manuel-vara** [comment]
@Joesturbo @BeckyMedlin this issue is still open due to the fact Hotjar script is loaded without performance cookie consent, please confirm we still need to load only when performance cookies are accepted.

**Comment by Joesturbo** [comment]
@manuel-vara -=- YES it should be loaded on ALL sites as part of the Performance cookies!

Adding @Kannan-CM

**Comment by girishdigrajkar** [comment]
Validated after code merge, When user enables Performance cookies then hotjar script can be identified in Dev tools > Network tab and when user disables performance cookies then the hotjar script is no longer present.   
Able to get the correct results hence, marking this ticket to done status.

**Performance cookie: ON**:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/37019cf2-b462-4ecb-b68c-6c8568a63ab5">

**Performance Cookie: OFF**:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4f6a7f89-3639-43ed-bc34-fbee420c7548">
