### ISSUE TITLE
Bug Minor: Our Facilities points to 404 page

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#333]
**URL:** https://www.macktrucks.com/about-mack/
**Browser:** Chrome 114.0

**Steps to reproduce**
1. Go to https://www.macktrucks.com/about-mack/
2. Scroll down the page to Our Facilities
3. Click on the Our Facilities CTA

**Expected results**
The Facilities page is shown

**Actual results**
A 404 page is shown

**Screenshots**
![Our Facilities CTA](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/8446f42b-89d8-4356-8299-69fc153e44e0)
![Our Facilities 404](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/985f2ed1-358e-41f5-921d-e3b524da6eb5)

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4ffc5b3d-c607-450e-a1eb-35f56443ad6e">
