### ISSUE TITLE
Bug: Critical - Mobile view - Homepage - Text of the Explore block from homepage not correctly displayed in Mobile view

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#338]
When opening the homepage of macktrucks.com on Mobile view - the Explore block is not correctly displayed and the text is cutoff

**Steps to reproduce:**
01. Open macktrucks.com on Mobile view
02. Scroll down and notice the Explore block

**Expected result**
Explore block from Homepage should be correctly displayed

**Actual result**
Explore block from Homepage is incorrectly displayed- the text is cutoff

<img width="769" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/0d820cda-5b66-4973-87f0-b2769ab10b05">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed :

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/3d952756-eda1-47d3-bee5-2b189ef971fb">
