### ISSUE TITLE
[Post Go Live] Bug: Major - All Text Alignment issues that cause the text to be unreadable

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#346]
This ticket is created with the purpose to document the instances in which text alignment issues cause the text to be unreadable (for example white text on a light white background hero image)

to be updated with examples..

01. Text from Columns (info) on the Trucks page in Mobile view
https://www.macktrucks.com/trucks/ 

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/58dc4d92-0700-4387-a715-19ee215eb9da)

02. Android Mobile view for Pinnacle Series Trucks page

https://www.macktrucks.com/trucks/pinnacle-series/

<img width="993" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/519c030f-9448-4060-bebc-31463e3ac07e">

<img width="993" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/9e91c5c1-6b8d-4323-b635-2d2232bb530d">

03. Text on Trucks: LR Series on Mobile view
https://www.macktrucks.com/trucks/lr-series/ 

<img width="789" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/fbaec950-ee33-4e3b-ae73-2bba00e3106f">

and in Android Mobile view

<img width="789" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/6ad8e86c-4ad6-4e42-86bd-aa22f18805ca">

04. Hero image text from Powertrain -> Engines on Android Mobile view

<img width="862" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/b38824ec-d8b0-49d1-879e-afe7c730179b">

05. Text from Columns (info) on Powertrain: Engines: MP8HE

<img width="1282" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/0946358d-7e38-4bf0-adb9-fb85c2a63fd7">

**Comment by girishdigrajkar** [comment]
Reopening the defect: 
1.Seems fix is not merged as pull request URL passed retest however, not the macktrucks.com URL
2: Confirmed as Fixed
3.1 : Not fixed
3.2: Confirmed as Fixed
4: Not Fixed
5: Not Fixed

**Comment by girishdigrajkar** [comment]
Earlier retest comments still valid; Republishing of pages needed ?

**Comment by girishdigrajkar** [comment]
Retest summary: 
1: confirmed as Fixed
3.1 : Not fixed
4: Confirmed as Fixed
5: Not Fixed

**Comment by Andrei-Boiangiu** [comment]
06. Text from the first Card on Buy Mack -> Certified Used Trucks page
 https://www.macktrucks.com/buy-mack/mack-certified-used-trucks/
 
 
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/55faebfe-578a-4459-9872-2f5d9c2111e2)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed: 01, 02, 04, 05, 07, 08, 09

still present: 03, 06

@jonatan-lledo-netcentric would you like a separate ticket for the still present ones and have this one closed as Fixed? or you would rather keep this parked here for any other updates?

**Comment by jonatan-lledo-netcentric** [comment]
I prefer to put this on hold status and open a new one with the remaining ones, please. Thanks

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd Please follow up on this on hold work to see if we can get it moving again. Thank you!

**Comment by DanielaPedrochevd** [comment]
@Gonzalo-CG please check last comment :)
