### ISSUE TITLE
[Post Go Live] Bug: Major - Mobile view - Anthem: Features - Title on the Hero is cutoff

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#347]
On Mobile View, the Title text on the Hero image from Anthem: Features page is displayed incompletely and cutoff

**Steps to reproduce:**
1. Open  https://www.macktrucks.com/trucks/anthem/features/ in Mobile view
2. Notice the title on the Hero image

**Expected result**
Title text should be correctly displayed

**Actual result**
Title text on Hero image is cutoff

<img width="786" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/fa9d7321-59a0-49b3-aa30-f30432c23576">

**Comment by Andrei-Boiangiu** [comment]
same issue for Trucks: Pinnacle series: Features

https://www.macktrucks.com/trucks/pinnacle-series/features/

<img width="838" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/8d8c6f65-f0f6-45e6-937e-0c91a60e1b2e">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/bf361986-a21b-4f6e-842b-a743f35aa54e">


<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/32af9eed-af80-4209-ab0c-1115dde74142">
