### ISSUE TITLE
[Post Go-live] Bug: Major: Hero video/animation is not played

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#348]
Steps:
1. Navigate to https://www.macktrucks.com/trucks/lr-electric/
2. Validate the Hero video/animation 

Expected vs Actual:
The video/animation does not play

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/af33f086-3faf-432c-944e-f87ef9928eea">

**Comment by TomaszDziezykNetcentric** [comment]
Hi @girishdigrajkar 
I just retest the lr-electric page and it works for me. I tested it in Chrome, Firefox, and Safari.

Could you retest it?

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
