### ISSUE TITLE
[Post Go Live] Bug: Major - Mobile view - Trucks: Pinnacle: Features - Cookie button and Scroll up button are overlapping the bottom subnavigation menu

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#350]
In the Mobile View for the Pinnacle Trucks: Features page - the Cookie Button and scroll up button are overlapping the bottom subnavigation menu

**Steps to reproduce:**
1. Open https://www.macktrucks.com/trucks/pinnacle-series/features/ on Mobile view and scroll down
2. Notice the Cookie button and Scroll up Button overlapping the subnavigation bottom menu

**Expected result**
Subnavigation bottom menu should be removed (?)

**Actual result**
 the Cookie Button and scroll up button are overlapping the bottom subnavigation menu
 
 
<img width="820" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/5dad0f23-a967-417f-b091-6b71f2ab6f83">

**Comment by Andrei-Boiangiu** [comment]
same issue on Trucks: LR Series: Features
https://www.macktrucks.com/trucks/lr-series/features/

<img width="971" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/3538b9dc-3601-4dd1-87a4-d79c465a2db0">

**Comment by TomaszDziezykNetcentric** [comment]
I created the PR with fix, where the cookie and scroll to top buttons are moved slightly to the top.

<img width="382" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/937608b9-b7cf-4038-bf9c-01b1799ed62a">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed :

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/050aa7d9-c54d-4658-997c-fef07bbfd828">


<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/29854ec1-d2fd-4314-8429-a7ba9bf40961">
