### ISSUE TITLE
[ Post Go Live] Bug: Minor - Trucks: LR Series - Title on third Card on Cards block is not bolded correctly

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#351]
The Title on the third card on the Cards block from Trucks: LR Series page is not correctly styled

**Steps to reproduce:**
1. Go to https://www.macktrucks.com/trucks/lr-series/ and scroll down to the Cards block
2. Notice the title on the third Card

**Expected result**
Title should be stylend like the other two cards

**Actual result**
<img width="1488" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/c7018471-191a-498d-b121-32f7b74071df">

**Comment by TomaszDziezykNetcentric** [comment]
Content issue. Fixed. Moved to revalidation.
