### ISSUE TITLE
[Post Go Live] Bug: Major - Trucks: LR Series: Features - Features block overlaps the Cards (cta) block below

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#352]
On the Trucks: LR Series: Features page - the last two block Features and Cards (cta) overlap

**Steps to reproduce:**
1. Go to https://www.macktrucks.com/trucks/lr-series/features/ and scroll down
2. Notice the last two blocks

**Expected result**
The two blocks should be correctly displayed

**Actual result**
The last two block Features and Cards (cta) overlap

<img width="1539" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/02ff766b-c81e-49b7-a039-fcbd923949f4">

**Comment by TomaszDziezykNetcentric** [comment]
I can't reproduce the issue. Probably already fix in the scope of another issue.
Move to retest.

**Comment by girishdigrajkar** [comment]
Bug is reproducible, Please investigate :

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/baf5f893-cf9f-47cc-b8b1-4b306f4796ef">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
