### ISSUE TITLE
Performance Optimisation: Improve CLS: Explore block initial rendering + others

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#353]
<img width="1460" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/13e49c10-b8b9-4701-8353-8deae9455c6a">
https://pagespeed.web.dev/analysis/https-www-macktrucks-com/y38vknoykw?form_factor=mobile

**Comment by jonatan-lledo-netcentric** [comment]
Test Page in pagespeed:
https://pagespeed.web.dev/analysis/https-353-cls-explore-block--vg-macktrucks-com--hlxsites-hlx-page/4nwqicemyl?form_factor=mobile

**Comment by Andrei-Boiangiu** [comment]
Currently the performance numbers for this branch are 97 for Mobile and 94 for Desktop

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/29aca0a9-8b49-4932-98c3-3e38bd0f0fdc)

<img width="1696" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/d03f4599-e083-4bfa-ab9d-7d56e52fb176">


as discussed with @manuel-vara and @jonatan-lledo-netcentric we are aiming to achieve 100 but we can consider this specific point as done and then to open another one with additional improvements that can allow us to reach 100
marking this as Done and feel free to open the ticket for the additional improvements
