### ISSUE TITLE
Youtube link displayed in carousel

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-macktrucks-com#354]
https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8/

<img width="1448" alt="Screenshot 2023-06-30 at 14 24 00" src="https://github.com/hlxsites/vg-macktrucks-com/assets/2250964/7dcf79ff-83e5-4cb1-898f-3404aea7ef2c">

**Comment by TomaszDziezykNetcentric** [comment]
The doc content is updated. The preview is working, publishing is left.

**Comment by synox** [comment]
works now

**Comment by girishdigrajkar** [comment]
Confirmed as fixed:

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/d16cc859-cf51-4b9c-b3c3-ed704605ddaa">
