### ISSUE TITLE
Post Go Live Bug Major: Fragments not loaded

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-macktrucks-com#355]
https://www.macktrucks.com/parts-and-services/support/body-builders/wiring-diagrams/

<img width="1322" alt="Screenshot 2023-06-30 at 14 27 01" src="https://github.com/hlxsites/vg-macktrucks-com/assets/2250964/5e361dc0-781e-4683-ba0a-89ea60b27cd2">

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/bf8fb4b0-5155-41da-b75d-15cf447e712e">
