### ISSUE TITLE
News RSS Block

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#36]
There is a need for a News RSS block: 

![image](https://user-images.githubusercontent.com/126146302/227196120-0f92f28f-9ee9-4b2a-8e40-a8a92d57c3f7.png)

It can be used with two different indexes and feeds. 

1. https://www.macktrucks.com/parts-and-services/support/body-builders/news-and-events/ 
2. https://www.macktrucks.com/mack-news/

**Comment by synox** [comment]
Looks similar to https://github.com/hlxsites/vg-macktrucks-com/issues/38, maybe the style can be reused.

**Comment by synox** [comment]
I created https://github.com/hlxsites/vg-macktrucks-com/issues/36 to add an additional RSS feed
