### ISSUE TITLE
[Post Go Live] Bug: Minor - Powertrain: Engines: MP7 - Title for "Related Products" is missing

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#366]
On Powertrain: Engines: MP7, the title for the last Cards (cta) component for "Related Products" is missing

**Steps to reproduce:**
1. Go to https://www.macktrucks.com/powertrain-and-suspensions/engines/mp7/ and scroll down to the last Cards (CTA) block
2. Notice that the "Related Products" title is missing

**Expected result**
Last Cards (cta) block should have title "Related Products"

**Actual result**
Title "Related Products" is missing for the last Cards (cta) block

<img width="1494" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/a9fb966e-9916-4094-b6df-4309e593024a">

**Comment by Andrei-Boiangiu** [comment]
same issue on Powertrain: Engines: MP8
https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8/

<img width="1282" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/b72c1205-cdb5-41f1-8a39-bb79284e5e56">

**Comment by Andrei-Boiangiu** [comment]
same issue on Powertrain: Engines: MP8HE
https://www.macktrucks.com/powertrain-and-suspensions/engines/mp8he/

<img width="1608" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/da149265-7d5e-4073-9ef4-30da962d19de">

**Comment by ZoeBeykirch** [comment]
Closing this ticket as it has been corrected on production.
