### ISSUE TITLE
Bug: Minor - Download link opens in same browser window/tab

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#367]
URL: https://www.macktrucks.com/mack-connect/connected-support/
Browser: Chrome 114.0

**Steps to reproduce**
1. Go to https://www.macktrucks.com/mack-connect/connected-support/
2. Scroll down the page to the Over The Air (OTA) Software Updates section
3. Click Download Brochure

**Expected result**
A new tab or browser window opens to show the brochure

**Actual result**
The brochure is shown in the same window

**Screenshot(s)**
<img width="728" alt="Download brochure" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/a0d158fc-57c0-4d78-9517-5bceffa8c9c1">

**Comment by girishdigrajkar** [comment]
Bug is reproducible and hence, reopening it.
