### ISSUE TITLE
Post go-live: Bug: Medium: Suggested reading articles missing in Magazine section

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#368]
URL: https://www.macktrucks.com/magazine/articles/2022/august/expertise-in-action-preview
Browser: Chrome 114.0

**Steps to reproduce**
Go to https://www.macktrucks.com/magazine/articles/2022/august/expertise-in-action-preview
Scroll down the page until you reach "Based on your reading, you might like this..."

**Expected results**
Recommended reading results are shown for the reader to choose from

**Actual results**
No recommended articles are shown

**Screenshot(s)**
<img width="730" alt="Suggested Reading" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/f567c027-633a-4bf6-a2f6-cb5557f537b2">

**Comment by Kannan-CM** [comment]
Hi @SantiagoHomps-NC,

This article has the category fiels, but has multiple words "Technology at Work", Do we have it as part of the Tags?

**Comment by shirin27** [comment]
@ZoeBeykirch @Joesturbo : what should we do in the case when there is only one article in a specific category? Should we self-reference the same article, or hide the section completely?
Or is it a different logic to be taken into account?
I heard from Manuel there will be a new feature required related this, let's discuss it. :)

**Comment by shirin27** [comment]
From planning: Joe: it's ok to self-reference, for now, the use case is no longer present; ticket closed
