### ISSUE TITLE
Post Go Live: Bug: Minor - PartsASIST doesn't open in a new window or tab

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#369]
URL: https://www.macktrucks.com/parts-and-services/
Browser: Chrome 114.0

**Steps to reproduce**
1. Go to https://www.macktrucks.com/parts-and-services/
2. Click on the PartsASIST CTA
3. Once the page loads, click on the Login CTA

**Expected results**
A new window or tab opens to the Customer Portal

**Actual results**
The Customer Portal opens in the same window or tab

**Screen shots**
<img width="822" alt="PartsASIST cta" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/544df7e0-88ec-41db-877c-172ad33a813f">
<img width="829" alt="Login CTA" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/9ada1936-14e9-4469-b41d-2e4b8ecaecb6">
<img width="759" alt="Customer Portal" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/efe60695-5191-45a1-ac22-f8202c26de3d">

**Comment by girishdigrajkar** [comment]
Reopening the defect as the defect is reproducible; i.e. new tabbed window is not open when user clicks on Login CTA.

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
