### ISSUE TITLE
Download Block

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#37]
There is a need for a Download section as this one:
![image](https://user-images.githubusercontent.com/126146302/227197702-f929f6eb-c391-41cf-946f-7a2ef4ae555a.png)
https://www.macktrucks.com/parts-and-services/support/body-builders/tools/

**Comment by synox** [comment]
Please note we currently can't host excel files on sharepoint though Franklin. See https://github.com/adobe/helix-home/discussions/337
