### ISSUE TITLE
Bug: Medium: Mack-news limit of news lower than news to be published 

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#378]
Current limit is 200, but after the request to publish all news from 2018, now the number of news that need to be published is around 400.
An update of the current limit that accounts for existing and including some additional margin for more news to be published in the next years is needed.

**Comment by girishdigrajkar** [comment]
Hi @manuel-vara : As discussed, below are outstanding actions for this ticket :
1. The News RSS xml is incorrect as not all data is present in it ; UI has more data.
2. News items has '| Mack Trucks' which should not be present
3. News items in 2018 do not have description/summary of the news
4. Suggestion/Improvement: '**Overall**' link could be renamed to '**All**' to showcase all news till date( From 2023 to 2018  descending). There could be another link '**2023**' showcasing only **2023** year news items.

@synox : Kindly confirm on point 4 above.
cc: @verareljic 

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/936dfb5d-bb1f-4b93-b541-d10f47c49f76">

**Comment by synox** [comment]
I don't know if/when I have capacity for this.

**Comment by girishdigrajkar** [comment]
The bug is yet to be fixed hence, assigning it to dev team.

**Comment by shirin27** [comment]
@Joesturbo could you please check this point:

Suggestion/Improvement: 'Overall' link could be renamed to 'All' to showcase all news till date( From 2023 to 2018 descending). There could be another link '2023' showcasing only 2023 year news items.

**Comment by shirin27** [comment]
@Kannan-CM test with a redirect from mack-news to mack-news/2023, if it works, this can be closed.

**Comment by Kannan-CM** [comment]
Hi @manuel-vara ,
Redirect is set and workig.

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd  @manuel-vara @Kannan-CM Can this one be closed? It is still open and on hold.

**Comment by manuel-vara** [comment]
IMO, yes.

**Comment by DanielaPedrochevd** [comment]
@Gonzalo-CG please check last comment :)

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG @DanielaPedrochevd Please update the status. Thank you!

**Comment by girishdigrajkar** [comment]
For 2023, able to see correct results however, based on above comments few remaining actionable from dev team hence, keeping this ticket active.

**Comment by DanielaPedrochevd** [comment]
@girishdigrajkar why aren't we closing this? @manuel-vara says it can be closed.

**Comment by girishdigrajkar** [comment]
Please note that post 7 July( See comments in above trail)  only one action is completed rest actions are outstanding with Dev team/@manuel-vara.   

Below are outstanding actions for this ticket :
1. The News RSS xml is incorrect as not all data is present in it ; UI has more data.
2. News items has '| Mack Trucks' which should not be present
3. News items in 2018 do not have description/summary of the news

@DanielaPedrochevd @Gonzalo-CG @manuel-vara :
In case there has been decision of not proceeding on above actions which I am unaware then, please add comment to this ticket and close it.
