### ISSUE TITLE
Download Block Variation

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#38]
There is a need vor a Download Block variations like the one below:
![image](https://user-images.githubusercontent.com/126146302/227204790-04b1e1b9-4df8-434d-af63-70429b102179.png)

https://www.macktrucks.com/parts-and-services/support/body-builders/wiring-diagrams/

**Comment by synox** [comment]
Similar to https://main--vg-volvotrucks-us--hlxsites.hlx.live/block-library/blocks/document-list, but multiple documents can be marked as new. 

Block structure: I suggest to add a second column in the docx where the word `NEW` (case-insensitive) can be added. 
<img width="707" alt="Screenshot 2023-05-02 at 13 42 29" src="https://user-images.githubusercontent.com/2250964/235781344-fb2c0487-c5b2-4f55-8adb-a007cc914953.png">

**Comment by Andrei-Boiangiu** [comment]
Testing done with Minor bug open
#142
