### ISSUE TITLE
Bug: Major: Videos don't open after clicking the CTA

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#381]
**URL:** https://www.macktrucks.com/parts-and-services/support/body-builders/training/
**Browser:** Chrome 114.0

**Steps to reproduce**
1. Go to https://www.macktrucks.com/parts-and-services/support/body-builders/training/
2. Scroll down the page to the different cards with the CTAs "Watch The Video"
3. Click on one of the "watch The Video" CTAs

**Expected results**
A new window opens showing the YouTube video in YouTube

**Actual results**
A 404 error page is shown

**Screenshots**
<img width="742" alt="Watch the video" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/51581c68-0144-4151-b6bb-6f24b2958bcc">
![MicrosoftTeams-image (9)](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/8bae07b7-aedb-4d46-a92c-69dd67c34126)

**Comment by girishdigrajkar** [comment]
confirmed as fixed
