### ISSUE TITLE
[Post Go Live] Cards are cropped.

### ISSUE THREAD

**Issue by TomaszDziezykNetcentric** [hlxsites/vg-macktrucks-com#384]
Some of the cards are cropped. The text is coming out of the cards.

Example URL: https://www.macktrucks.com/powertrain-and-suspensions/engines/mp7/

<img width="497" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/5c4c324f-18f4-469c-84b0-14bcd7740775">

<img width="855" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/734db5a7-bb6b-489a-acdc-4cdb9cd2dd7e">

Expected results:
The card content shouldn't be cropped.

<img width="672" alt="obraz" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125962117/293d5c83-893c-42a4-8834-03b854647c76">

**Comment by girishdigrajkar** [comment]
Confirmed as fixed for cards however,  extra space observed below section title 'Related Products' :

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/9a77b9b7-8214-40ae-bb13-78dc60c033a1">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/5c24a88e-17fd-4d8c-8279-d4ae131c1e34">

**Comment by girishdigrajkar** [comment]
Confirmed as fixed

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/2baea325-faaf-43cd-8de8-e4c46a7946ba">
