### ISSUE TITLE
Post go-live: Bug: Medium: Button Color issue

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#386]
When we use Italicized font style for the links it is changing the style to transperant and turns to gold on hover.
But this is currently working only on the Columns block.

This needs to work on all other blocks as well, like Hero, Text etc..

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/126496977/8ec00b5c-6cc0-4b02-8d65-5daf16325c55)

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/cf60a466-b9e7-4012-b53a-a0a2537a1c91">

==================


<img width="942" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/ab756a38-3965-4164-9361-0e13501e273f">


==================

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e4b37373-39f7-49e2-84fd-ed2caa34aff5">
