### ISSUE TITLE
Post Go live: Medium: Trucks > LR  does not have LR-Electric subtab

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#389]
Steps:
1. Navigate to https://www.macktrucks.com/trucks/lr-series/
2. Validate the sub menus

Expected vs Actual:
Trucks > LR  does not have LR-Electric subtab
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/7e51575c-50d8-4ea7-982c-0e46469a2c0c">

**Comment by jonatan-lledo-netcentric** [comment]
is already fix, please re-test

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:


![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e1bc7e6e-c933-4f45-be08-7399b72e37af)
