### ISSUE TITLE
Post Go live : Bug : Medium - Font style of text content not consistent

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#391]
The font size of the text content within Accordian component is not consistent and differes when bullet points are added.
Expect the Font size remains consistent.

Example Page:
https://main--vg-macktrucks-com--hlxsites.hlx.page/negotiation/

Screenshot:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/126496977/56922982-e96f-468c-b85c-35fdaaccc2a4)

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/49f3e757-d2a3-4588-9f88-0e09c805e73c">
