### ISSUE TITLE
[Post Go Live] Bug: Medium - Trucks: LR Series: Extra blank space observed between Features block &  Cards (cta) block 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#401]
**Steps to reproduce:**

1. Go to https://www.macktrucks.com/trucks/lr-series/features/ and scroll down
2. Notice the last two blocks

Expected vs Actual:
Extra blank space observed between Features block &  Cards (cta) block 
Note: Root cause seems the fix of https://github.com/hlxsites/vg-macktrucks-com/issues/352 

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/9f7cde2f-4718-4e09-8daa-9dbd754b25ab">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/9a55778f-aef5-450a-8596-b8aec62b63b4">

**Comment by ZoeBeykirch** [comment]
Closing ticket as the PDP redesign has changed the page to no longer use these blocks.
