### ISSUE TITLE
Post Launch: Bug: Magazine article is not allowing us to use diffetent blocks

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#402]
Hi Team,

We have requirmnet to have Carousels, Columns, Videos on the Magazine article pages.
Today it doesn't allow us to do them.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as tested on https://402-magazine-blocks--vg-macktrucks-com--hlxsites.hlx.page/drafts/shomps/magazine/articles/2023/january/document
