### ISSUE TITLE
Post Launch: Bug: Columns (info) styling issue

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#404]
The Columns (info) component the styling of the content on the first component is different from the other 2.

Example page:
https://www.macktrucks.com/trucks/sustainability/

ScreenShot:

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/126496977/5a9b87aa-1951-4792-acef-f80b3d51816a)

**Comment by jonatan-lledo-netcentric** [comment]
https://www.macktrucks.com/trucks/lr-electric/ also another possible bug related also with columns info
