### ISSUE TITLE
Bug: Major: Implement OneTrust css class consent to manage GTM tracking (Mack)

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#406]
Add a class=“optanon-category-C0002” into loading script to allow OneTrust handle GTM script loading Performance cookies (Analytics).

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

Do not accept cookies and verify: GTM should not load : Passed
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/32f5ba49-826e-41f2-b308-f72bf6ca02b3">

Accept all cookies: GTM should load : Passed
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/ee24eab7-1915-467f-9eeb-3a9eca762cb7">

Reject all cookies: GTM should not load : Passed
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/f781fd7d-56ce-44cc-9d9a-5b503847e998">
