### ISSUE TITLE
[Post Go Live] Bug: Critical - Parts and Services: Parts: Mack Parts: Material Safety Data Sheets - Material Safety Data sheets page is missing

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#407]
The Material Safety Data Sheets page on https://www.macktrucks.com/parts-and-services/parts/mack-parts/material-safety-data-sheets/ is missing

**Steps to reproduce:**
1. Go to for example: https://www.macktrucks.com/parts-and-services/parts/mack-parts/engine/
2. Scroll down to the Safety Data Sheets button
3. Click the button 
4. Notice the missing page

**Expected result**
Material Safety Data Sheets page should be correctly displayed  (  https://www.macktrucks.com/parts-and-services/parts/mack-parts/material-safety-data-sheets/ ) 

**Actual result**
Maaterial Safety Data Sheets page is missing

**Comment by manuel-vara** [comment]
Added entry to redirects file to the right URL (without `/`). Tested other links (like footer) pointing to right page URL already.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
