### ISSUE TITLE
Magazine articles template

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#41]
Create template layout and necessary block to build Magazine articles:
template --> magazine-article
index --> magazine-articles.json

Identified candidates for new blocks:

- Recent Articles
   - Main 
   - List 

- Recommendations (Based on this reading, you might like this)
- AddThis  (Social Media sharing toolbar)
- Includes Categories tagging as well, please see below 'In the News' on Hero block.

Ref link: https://www.macktrucks.com/magazine/articles/2023/january/pets-partner-for-the-ride/
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/116451851/227971552-ebd287ca-fb40-4fad-9853-69fde2cfbba5.png">

**Comment by Andrei-Boiangiu** [comment]
moving to Done with above (this thread) mentioned issues
#193 #194 #195 #196
