### ISSUE TITLE
[Post Go Live] Bug: Major - Text on Image background causes the text to be unreadable

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#414]
As mentioned in #346 

there are some cases of Text with Image Background that can cause the text to be unreadable:

01. Text on Trucks: LR Series on Mobile view
https://www.macktrucks.com/trucks/lr-series/

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/d3abffdb-8979-4d08-8838-72f178e090c8)

02. Text from the first Card on Buy Mack -> Certified Used Trucks page
https://www.macktrucks.com/buy-mack/mack-certified-used-trucks/

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/3e88129f-4fba-4092-a8b2-872b79d53e12)

**Comment by shirin27** [comment]
@ZoeBeykirch could you check with the designers what would be the expected behaviour, to avoid having unreadable text over images? There are various possible solutions we could apply.

**Comment by shirin27** [comment]
No further development needed for now, the re-design should account for this use case.
Images to be swapped for now.

**Comment by ZoeBeykirch** [comment]
This is a content issue, so we can close on Github and move to an internal team (@WendyKruger should we make an asana task?) some of the background images don't work well for the white text especially seen on mobile and should be swapped out.
