### ISSUE TITLE
Bug: Major: Contact a Emobility Specialist link isn't configured

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#421]
**URL:** https://www.macktrucks.com/trucks/lr-electric/vehicle-as-a-service/
**Browser:** Chrome 114.0

**Steps to reproduce**
- Go to https://www.macktrucks.com/trucks/lr-electric/vehicle-as-a-service/
- Scroll down the page to "The Future Ahead." section
- Click on the CTA called Contact a Emobility Specialist

**Expected behavior**
The Vehicle as a service page appears with the "fill out the form below to connect with your mack emobility specialist" form

**Actual behavior**
Taken to a "This site can't be reached" page. localhost refused to connect

**Screenshots**
<img width="701" alt="Contact a Emobility Specialist broken link" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/2f99c23c-61ef-43c6-a6da-0e343e590422">
<img width="610" alt="Localhost error" src="https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/97db6e56-4490-4e33-8d78-1c7d1014603d">

**Comment by jonatan-lledo-netcentric** [comment]
button link updated, previewed and published, ready to test

**Comment by girishdigrajkar** [comment]
Confirmed as fixed:

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e0d0bd79-45d3-4116-ad4c-b2403538f35a">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/096c2c9d-8fff-46b9-94bf-7a5d2f769d54">
