### ISSUE TITLE
Post Launch: Enhancement: Add the publish date to blog article

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#431]
**Description**
Need to have option to add publish date to magazine pages to allow us to sort.
Today the latest published is added to the bottom of the list of the magazine explore pages.
Sorting function of blogs is already addressed in issue [606 ](https://github.com/hlxsites/vg-macktrucks-com/issues/606)
This ticket will only address inserting publish date to the article 

**Agile Requirement**
As a content editor or author, I want to be able to add the published date on any bulldog magazine article, so that the articles can be sorted chronologically. 

**Acceptance Criteria**

- Publish date appears below the title and above the author name (same format on computer and mobile)
- Publish date can be present on all magazine articles
- All markets follow date format spelt out  ex. March 4, 2024

**Questions**

- What format is the date in (March 4, 2024 / 03/05/2024 / etc)
  - Answer: Spell out Month date (March 4, 2024)
https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2210-65358&mode=design&t=sNhhqGKjGkQxlUZd-0
<img width="484" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/158284953/a5e9d787-bc0c-49e0-b3d9-1c2fd27c7599">

**Comment by BeckyMedlin** [comment]
@Kannan-CM Is this for Mack, Volvo, or both?

**Comment by ZoeBeykirch** [comment]
This ticket is only referencing the Mack website for Bulldog Magazine.

**Comment by BeckyMedlin** [comment]
@WendyKruger wants to address this with the Bulldog Magazine template. @mollyaljenkins Please ensure that the ticket includes this information as well. This work will be for the redesign template. No changes for the live site necessary at the moment.
