### ISSUE TITLE
Bug: Major: ELOQUA cookie not displayed / Content issue observed

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#432]
Steps:

Scenario 1:
1. Navigate to macktrucks.com
2. Do not accept cookies; reject them
3. navigate to Buy Mack > Request a Quote
4. Validate the message displayed 

Scenario 2:
1. Navigate to macktrucks.com
2. Accept all cookies
3. navigate to Buy Mack > Request a Quote
4. Validate the cookies in dev option >> Application 

Expected vs Actual:
1. The message is not as expected:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/decc175a-ef28-457f-844c-91aebd8adf82)

2. The ELOQA cookies are not displayed(?);  Even after submitting form no change in cookies list observed .
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/cd116da3-ebcf-4451-9f8b-7d932c23fc91">

**Comment by Kannan-CM** [comment]
We don't need to block Eloqua now. Eloqua will be displayed by default irrespective of user accepts the cookies or not

**Comment by BeckyMedlin** [comment]
Also noticed that "no eloqua message" displays at the bottom of the page, too.



![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/142249558/f4667599-ca26-4259-a07e-7d44ee42b444)

**Comment by manuel-vara** [comment]
@BeckyMedlin message has been fixed. Defined message is now visible.
<img width="1607" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/b507592d-9c64-473c-a614-a90814aacbe8">

Do you want us to unblock Eloqua anyway? Please confirm.

**Comment by BeckyMedlin** [comment]
@Joesturbo Please see the message from @manuel-vara re the Eloqua block. What needs to be done here to resolve correctly?

**Comment by Joesturbo** [comment]
Yes this is fine to roll out - previously it was an eloqua message.

**Comment by Varunvolvo** [comment]
Hi Manuel, 

I am sharing you the updated code for the two Bulldog Magazine forms attached. 


[Bulldog Magazine Subscription 2022 new.txt](https://github.com/hlxsites/vg-macktrucks-com/files/12702435/Bulldog.Magazine.Subscription.2022.new.txt)
[Bulldog Magazine Feedback New 2022.txt](https://github.com/hlxsites/vg-macktrucks-com/files/12702440/Bulldog.Magazine.Feedback.New.2022.txt)

BR/Varun
