### ISSUE TITLE
BUG: "404 Not Found" error text in OneTrust component

### ISSUE THREAD

**Issue by WendyKruger** [hlxsites/vg-macktrucks-com#435]
There is error code in the OneTrust component, and this h1 text is actually being pulled into some pages during website scrapes as an h1 tag. :

'<div class="ot-optout-icon">

    <title>404 Not Found</title>
    <h1>Error 404 Not Found</h1>
    <p>Not Found</p>
    <h3>Error 54113</h3>
    <p>Details: cache-iad-kiad7000066-IAD 1692133276 668804055</p>
    <hr>
    <p>Varnish cache server</p>
</div>'

Here is a list of the pages I found during a scrape:

https://www.macktrucks.com/buy-mack/find-a-dealer/
https://www.macktrucks.com/magazine/articles/2022/august/closer-look-mack-md
https://www.macktrucks.com/magazine/articles/2022/august/in-the-news-mack-defense
https://www.macktrucks.com/magazine/articles/2022/august/in-the-news-onecall
https://www.macktrucks.com/magazine/articles/2022/august/mack-pov
https://www.macktrucks.com/magazine/articles/2023/january/crmp-inc
https://www.macktrucks.com/magazine/articles/2023/march/mack-trucks-unveils-the-md-electric-medium-duty-truck
https://www.macktrucks.com/magazine/categories/customer-profiles
https://www.macktrucks.com/magazine/categories/in-the-news
https://www.macktrucks.com/buy-mack/
https://www.macktrucks.com/buy-mack/mack-leasing-system/
https://www.macktrucks.com/magazine/bulldog-magazine
https://www.macktrucks.com/parts-and-services/uptime-solutions/mack-certified-uptime-centers/
https://www.macktrucks.com/parts-and-services/uptime-solutions/protection-plans-and-maintenance-plans/
https://www.macktrucks.com/powertrain-and-suspensions/
https://www.macktrucks.com/powertrain-and-suspensions/engines/scr/
https://www.macktrucks.com/powertrain-and-suspensions/exhaust-aftertreatment-systems/cleartech-system/
https://www.macktrucks.com/powertrain-and-suspensions/transmissions/
https://www.macktrucks.com/powertrain-and-suspensions/transmissions/mdrive-hd/
https://www.macktrucks.com/public-privacy-policy/
https://www.macktrucks.com/trucks/anthem/inventory/
https://www.macktrucks.com/trucks/events/
https://www.macktrucks.com/trucks/lr-electric/
https://www.macktrucks.com/trucks/pinnacle-series/
https://www.macktrucks.com/trucks/pinnacle-series/specs/
https://www.macktrucks.com/trucks/terrapro-series/
https://www.macktrucks.com/trucks/terrapro-series/features/
https://www.macktrucks.com/trucks/terrapro-series/specs/

**Comment by jonatan-lledo-netcentric** [comment]
The problem is in the `otBannerSdk.js` when it tries to load the logo,  it transforms a correct URL into a wrong one. 
Please check the oneTrust configuration to try to fix the issue @Kannan-CM @Varunvolvo

**Comment by girishdigrajkar** [comment]
Validated by visiting each page and checking Dev tools >> Elements for non availability of above error code mentioned in above description of defect. Marking the defect to done as results are as expected.
