### ISSUE TITLE
DL 1: Dealer Locator - Export, AU/NZ

### ISSUE THREAD

**Issue by BeckyMedlin** [hlxsites/vg-macktrucks-com#439]
Dealer Locator data should come from a spreadsheet for AU/NZ markets. They're not connected to master data. 
Spreadsheet needs to match up with Dealer POD master data (e.g., Name, address, and other available data).

**Comment by manuel-vara** [comment]
https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BDF784AFF-12F7-4E01-8690-08F1A5DF549F%7D&file=Book.xlsx&action=default&mobileredirect=true
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/export-market-dealer-locator/book.json

**Comment by manuel-vara** [comment]
Solution design + Data source preparation: 1SP
URL update and service parameter update to fetch right file from Sharepoint/Franklin: 1SP
Client call to fetch results update: 2SP

- Update based on the change of the incoming json payload

- Element types update:  Hours and Services from object to Array handling

- Developer tests

QA Testing: 1SP

**Comment by SantiagoHomps-NC** [comment]
@girishdigrajkar test on this branch:
https://439-dealer-locator-au--vg-macktrucks-com-au--hlxsites.hlx.page/buy-mack/find-a-dealer/

**Comment by girishdigrajkar** [comment]
Hi @SantiagoHomps-NC :  Below are the outstanding issues for AU find a dealer, as decided approach no separate bugs are raised for below  :

**Outstanding issues:**

1. undefined is being displayed in dealer information which needs to be addressed
2. ‘Head office’ filter is not working although the source Excel has record inserted for head office data
3. Bydefault all dealer list is shown in case of AU  unlike in case of US
4. All the dealer has "Closed" status and does not show open (checked for Perth time 4:38PM and all dealers were showing Closed); Added separate record with open hours as 00:00 to 23:00 yet that dealer too was displayed as Closed

**Comment by Gonzalo-CG** [comment]
As discussed on 20/Oct - If the user enables location in the browser, the dealers should be sorted by distance. If location permissions are not granted, the dealers should be sorted alphabetically.

**Comment by girishdigrajkar** [comment]
Validated and observed that although location is turned off the dealer list is not alphabetically arranged:


<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/0b0a5925-a725-4dff-9272-619c3fe0c5ed">

**Comment by girishdigrajkar** [comment]
Validated and below is summary :

1.  Bydefault if location is not allowed by user then the dealer list is displayed in alphabetical order as expected : PASSED
2. When User allows the location for the first time then the dealer list remains in alphabetical order; 
    User need to explicitly refresh the page to get the dealer list sorted based on the distance from user location 
 --   **Observation to be approved by business**

@Gonzalo-CG :   Kindly confirm with business if we can proceed going live with this outstanding observation. If not then, let us reopen this ticket to work further on it.
cc: @jonatan-lledo-netcentric , @manuel-vara

**Comment by Gonzalo-CG** [comment]
Hi @ZoeBeykirch @BeckyMedlin could you review point #2 of Girish's comment above? Are you ok to go ahead with this small functionality detail?

**Comment by BeckyMedlin** [comment]
@girishdigrajkar @Gonzalo-CG I confirmed with @Joesturbo that the list should be by location. Alpha order has zero impact or desire. It needs to display whatever is closest to the user. Please continue working on it.

**Comment by girishdigrajkar** [comment]
@jonatan-lledo-netcentric : Based on above confirmation, marked bug to 'In development'
