### ISSUE TITLE
Hero block design

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-macktrucks-com#44]
As per client decision, Hero block will be the same as the standard one from here: https://www.macktrucks.com/trucks/ ,  with the following feature: 
1. Add ability for video vs. image – auto play like here: https://www.macktrucks.com/trucks/lr-electric/
2. Eyebrow text, H1 text, paragraph text and cta like here: https://www.macktrucks.com/parts-and-services/
3. Video CTA on middle of hero - https://www.macktrucks.com/powertrain-and-suspensions/axles/ (delete the video CTA (red play button) – use standard button, text cta should say “watch video”. Same pop up module.
4. Slider/carousel add as a feature – add bubbles at the bottom and have arrows to go left or right.
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/126146302/229765006-75ead935-ddc7-4a5d-ae89-91f9451ae992.png">

**Comment by synox** [comment]
from the experience from volvotrucks.us, I recommend to disable auto-blocking for hero. The `Hero` block should be created intentionally.

**Comment by Andrei-Boiangiu** [comment]
Testing has been finished and with a minor ticket open at #147 

Note: as discussed with @jonatan-lledo-netcentric the Slider/carousel add as a feature is deprecated and will not be used anymore. Testing has been performed for the other three designs static image, video button and video
