### ISSUE TITLE
Bug: Critical: Bulldog Magazine Subscribe Not Working (Eloqua integration) 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#441]
On the "Subscribe to Bulldog" form on the Bulldog Magazine website [https://www.macktrucks.com/magazine/](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.macktrucks.com%2Fmagazine%2F&data=05%7C01%7Czoe.beykirch%40volvo.com%7Ccd714811cad14e9399e308dbb61ffa7f%7Cf25493ae1c9841d78a330be75f5fe603%7C0%7C0%7C638304020743859777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xFn%2FG0TVYezRQHU07cwA1RQxLxG6yzK1zlJ7Q6fWQOY%3D&reserved=0)

We have tested new form submission data is not being received in Eloqua, it appears something is broken and attached is the Eloqua code needed that should hopefully correct the issue. Form ID 249
[bulldog magazine opt-in form.txt](https://github.com/hlxsites/vg-macktrucks-com/files/12653489/bulldog.magazine.opt-in.form.txt)

**Comment by Kannan-CM** [comment]
Also the background color of the title drop down needs to be adjusted:

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/126496977/87b48d94-4df5-4f67-b017-441ba15637f2)

**Comment by Kannan-CM** [comment]
The text needs to be black by default and change to white with blue background on hover

**Comment by manuel-vara** [comment]
It seems to be the default styling issue on Windows OS, on Mac the styling default is visible.
<img width="1031" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/55ae0e1a-7bfb-474b-935c-40d5d71d883e">
