### ISSUE TITLE
Bug: Minor: Form dropdown selection illegible

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#442]
On the "Subscribe to Bulldog" form on the Bulldog Magazine website https://www.macktrucks.com/magazine/ 
The "Title" picklist stylesheets are not functioning correctly. As shown in the attached screenshot, both the text and background colors of the picklist options are white, making them illegible. 
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/d24bc3da-38a2-4308-bebb-2f3518217b4e)

**Comment by manuel-vara** [comment]
Fixed in #441
