### ISSUE TITLE
Update: Eloqua forms HTML code update (Bulldog Magazine: Subscription and Feedback)

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#448]

**Comment by manuel-vara** [comment]
[Magazine Forms.zip](https://github.com/hlxsites/vg-macktrucks-com/files/12738622/Magazine.Forms.zip)

**Comment by manuel-vara** [comment]
Eloqua HTML forms code updated, @Kannan-CM and/or @Varunvolvo, when possible, could you please test and let me know if that's ok?

**Comment by Kannan-CM** [comment]
Hi @manuel-vara ,

The form behaviour is still not stable. While filling the form it is getting disappeared.

**Comment by Kannan-CM** [comment]
Also the styling for the dropdown is gone back to the old one.

**Comment by Kannan-CM** [comment]
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/126496977/9aca3834-5d3e-4eac-a3eb-0f772a67dc4a)
