### ISSUE TITLE
Repurpose NHTSA blocks with Mack Branding

### ISSUE THREAD

**Issue by mlee001** [hlxsites/vg-macktrucks-com#452]
**User story**

As a developer I want to repurpose the blocks used to create the recall page within the Volvo repository and make them available within the Mack repository

**Acceptance criteria**

1. Repurpose the blocks used to create the recall page from Volvo to Mack to reuse the elements as much as possible
2. Add Mack branding to the blocks to keep to the Mack design principle

Assumption
There is no difference in functionality between Volvo and Mack

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
