### ISSUE TITLE
Setup content structure with Sharepoint and final page location

### ISSUE THREAD

**Issue by mlee001** [hlxsites/vg-macktrucks-com#460]
**User Story:**

As a editor of the recall page I want to have a content structure in place that allows for editing the different recall pages individually. This will enable me to easily manage and update the content of each page without affecting the others.

**Acceptance criteria**

Setup the content and page structure for
[www.volvotrucks.us/recalls/](http://www.volvotrucks.us/recalls/)
[www.volvotrucks.ca/en-ca/recalls/](http://www.volvotrucks.ca/en-ca/recalls/)
[www.volvotrucks.ca/fr-ca/recalls/](http://www.volvotrucks.ca/fr-ca/recalls/)
[www.macktrucks.com/recalls/](http://www.macktrucks.com/recalls/)

**Comment by BeckyMedlin** [comment]
@Joesturbo What URL needs to be implemented? Name of page?

**Comment by manuel-vara** [comment]
@BeckyMedlin @ZoeBeykirch @Joesturbo 
I've created several sections in Sharepoint that will map to the following URLs:

- www.volvotrucks.us/recalls/
- www.volvotrucks.ca/en-ca/recalls/
- www.volvotrucks.ca/fr-ca/recalls/
- www.macktrucks.com/recalls/

Are you missing any additional recall page URL or this would be it?
