### ISSUE TITLE
NFR: Cross reference search should only use the OEM_Num in the cr-data file

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#491]
Non-Functional Requirement: 

The cross-reference search should only use the OEM_Num (column D in the cr-data file). If a user searched a part number listed in column D, then the expected behavior is that they should see a resulting RC part number (from column G in the cr-data file)

Example: 

When putting WBS18B as a [cross ref search](https://main--vg-roadchoice-com--hlxsites.hlx.page/search/?q=WBS18B&st=cross), there should be no results since this is a RoadChoice part number. However, when the user searches the cross ref search with 40718, then the Road Choice part number WBS18B should show up since that is the cross listed in the cr-data file.

Expected Results: 
This is the correct use case: https://main--vg-roadchoice-com--hlxsites.hlx.page/search/?q=40718&st=cross

**Comment by SantiagoHomps-NC** [comment]
this is done [HERE](https://github.com/hlxsites/vg-roadchoice-com/issues/187)

**Comment by girishdigrajkar** [comment]
Validated and below observations are outstanding except which search works fine:

1. Search for  "11-312" , It shows 4 results and then page refreshes itself and shows 2 results; Instead, it should show correct results at once. 

2. Search for single space  or  ‘- ‘ I.e. for a common character or for string which yields in large results  then validate the screen, The search results alignment is different :
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/92a98146-fd05-425c-9009-f97ca19077e4">

3. Search for **‘ABP ‘** (with trailing space) and validate the search results :  Excel has 2934 count whereas, UI has 1338
However, when searched with ABP( without trailing space) gives correct result.

**Comment by girishdigrajkar** [comment]
Validated and above outstanding bugs are resolved hence, marking this ticket to done status.
