### ISSUE TITLE
Bug: Critical - Bumper filters are not loading all result options

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#492]
Under the [Bumpers category for Road Choice ](https://www.roadchoice.com/part-category/?category=bumpers  ) the Filters seem to only load the results for the first 12 products on the page, and when the user clicks on "show more results" the Filters do not update, they seem to still only display the initial 12 results. This is happening for all filter values Make, Model, Fog light provision, step holes, tow provision, vent holes, material, end style code, end style description, option 1 

For example, under the Filters the Make only shows 2 results for Autocar and Ford, when before the migration, the user had the full list of Make options they could select from the filter. 

Current Result: 

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/8ca48117-106e-47c6-a6fa-ed844d46df1c)

Desired Result: 

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/32e1964f-195d-40e7-a65c-f57122c6d6c2)

**Comment by manuel-vara** [comment]
@SantiagoHomps-NC FYI and assigned to you, perhaps related with something raised by @girishdigrajkar

**Comment by Gonzalo-CG** [comment]
Fixed by [#204](https://github.com/hlxsites/vg-roadchoice-com/issues/204)
