### ISSUE TITLE
High Priority: Dealer Locator - Missing Google Logo and Copyright Text

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-macktrucks-com#500]
Duplicate of the Volvo Trucks ticket #488

**Comment by ZoeBeykirch** [comment]
@cogniSyb He meant to reference this ticket - https://github.com/hlxsites/vg-volvotrucks-us/issues/488

**Comment by manuel-vara** [comment]
@Joesturbo , can you check this https://500-google-logo--vg-macktrucks-com--hlxsites.hlx.live/buy-mack/find-a-dealer/ please?

**Comment by ZoeBeykirch** [comment]
Looks good!

**Comment by girishdigrajkar** [comment]
Validated for missing google logo and copyright text and able to see it hence, marking the ticket to done status.
<img width="1792" alt="Screenshot 2023-11-16 at 2 06 50 PM" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/d1b4ab7b-7e15-41b2-aaad-c648c3a135e0">
