### ISSUE TITLE
Bug Minor: Axels link points to a 404 page

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#508]
**Link:**
https://www.macktrucks.com/trucks/anthem/specs/

Browser: Chrome v. 119.0.6045.105

**Steps to reproduce**
1. Go to https://www.macktrucks.com/trucks/anthem/specs/
2. Scroll down the page until you get to Axels
3. Click on Mack

**Expected behavior**
Axels page loads and displays the relevant information

**Actual behavior**
Axels link opens a 404 page

**Screenshots**
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/4777dfa6-5d6e-4690-94d9-79a351fabefa)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/b34f4a2c-0bac-4a2d-a3e8-da900d693540)

**Comment by BeckyMedlin** [comment]
Per @Kannan-CM  This is resolved.
