### ISSUE TITLE
Bug: Major: Find a dealer sidebar overlaps the header dropdown

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#509]
**Link:**
https://www.macktrucks.com/buy-mack/find-a-dealer/

Browser: Chrome

**Steps to reproduce:**
Click on "Find My Dealer"
Review the page that opens https://www.macktrucks.com/buy-mack/find-a-dealer/

**Expected behavior**
The header dropdown is not showing and the collapsed state of the header is present

**Actual behavior**
The header dropdown is shown behind the "Find a dealer" sidebar

**Screenshots**
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/5d5547cb-e196-4d08-b421-d7659c1ac602)
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/395040ac-aac2-41e2-b87c-f242db9feaf9)

**Comment by Andrei-Boiangiu** [comment]
bug confirmed

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://509-header-vs-dealer-sidebar--vg-macktrucks-com-rd--netcentric.hlx.page/buy-mack/find-a-dealer/

**Comment by manuel-vara** [comment]
@KJohnsn Fixed on macktrucks.com repo --> https://www.macktrucks.com/buy-mack/find-a-dealer/
