### ISSUE TITLE
Major - Mobile - Trucks: Features - Incorrect line of Text displayed on the Mobile menu on Trucks: Features page

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com#529]
--- Copy of [MackTrucks Redesign #175](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/175), as it will be picked up by the Franklin team ---

On Mobile, when going to the Features page of any of the trucks - an incorrect line of text is displayed in the menu below

**Steps to reproduce**:
 01. Open for example https://main--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/features/ on Mobile
 02. Notice the incorrect line of text on the first tab of the bottom menu
 
**Expected result**
Text in the first tab of the bottom menu should be correctly displayed

**Actual result**
The Features page for any of the Trucks, when opened on Mobile displays an incorrect line of code in the text of the first tab

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/a527859a-494e-45e7-b6d7-c55f3b398376)

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/54648862-767b-45f7-beba-ebc817429d1d)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, closing the defect.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/286fce77-597b-48b8-951c-88bcdcb4680a">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/49da2fa6-9bd0-4a58-bd85-44d917478fe3">
