### ISSUE TITLE
Dealer Locator - Content for every market

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com#531]
### Description
The Excel file with the list of all dealers needs to be present and up-to-date in the Sharepoint of every market for the dealer locator to work properly.

### Acceptance Criteria
The list of all dealers is present and correctly configured for each market, namely:

- [ ] New Zealand
- [ ] Australia
- [ ] Canada
- [ ] Mexico
- [ ] Chile
- [ ] Colombia
- [ ] Ecuador
- [ ] Peru
- [ ] Argentina
- [ ] Venezuela
- [ ] Panama
- [ ] Dominican Republic
- [ ] Costa Rica
- [ ] Honduras
- [ ] Nicaragua
- [ ] El Salvador
- [ ] Guatemala
- [ ] Bolivia
- [ ] Trinidad & Tobago
- [ ] Guyana
- [ ] EMEA
- [ ] Nigeria
- [ ] Bahamas
- [ ] Haiti

**Comment by BeckyMedlin** [comment]
Per @Kannan-CM work is complete.
