### ISSUE TITLE
Dealer Locator Issues

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-macktrucks-com#542]
On the dealer Locator the Close and Open timing of dealers are not calculated properly.
Looks like it shows closed by noon US hours.

The Dealer type selection toggle is filtering all the dealers except for the one the lies within the user location

Also noticed some places don’t show as EV certified or full line dealership

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/126496977/1fb6a009-54d0-4628-8138-a32ef5f456c9)

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd Please inject this into the current sprint as it is impacting production.
