### ISSUE TITLE
Bug: Major: Magazine categories items are not sorted from newest to oldest

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#549]
By default the **Recommendations block** used in **Magazine Categories** listing pages (Customer Profiles, Features, etc.) shows a number specified by the editor as for example: Recommendations(limit-5) or Recommendations(limit-10). 

That means the limit of items to render is configurable but those items are not sorted upfront from the newest created to the oldest, meaning if we have more than 10 items for example, the latest ones will not be shown.

A fix to sort by descending creation date or created item should be implemented.

May be related to - and needs discovery https://github.com/hlxsites/vg-macktrucks-com/issues/654

**Comment by DanielaPedrochevd** [comment]
#431

**Comment by BeckyMedlin** [comment]
@SantiagoHomps-NC Is this for Mack, Volvo, or both?

**Comment by ZoeBeykirch** [comment]
Closing this ticket after moving it to the new & improved Bug template in ticket - https://github.com/hlxsites/vg-macktrucks-com/issues/655
