### ISSUE TITLE
Atom/RSS Feed for body-builders

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-macktrucks-com#55]
https://www.macktrucks.com/parts-and-services/support/body-builders/news-and-events/
which is separate from https://www.macktrucks.com/mack-news/

**Comment by verareljic** [comment]
@synox please update the ticket according to the latest status. thanks!

**Comment by girishdigrajkar** [comment]
Hi  @manuel-vara ,This needs a fix as discussed

**Comment by synox** [comment]
https://github.com/hlxsites/vg-macktrucks-com/issues/63#issuecomment-1594459940

**Comment by manuel-vara** [comment]
RSS list Fixed:
https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/support/body-builders/news-and-events/feed.xml

@girishdigrajkar
Can you confirm, please?

**Comment by girishdigrajkar** [comment]
Hi Manuel,
The feed and UI both has 14 records, below observations are noted:
1. No description available in feed
2. The published and record dates are same for all records 
3. News & event title has '| Mack Trucks' appended.

<img width="1766" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/634e6c80-7956-4644-b537-5816dd67e85c">

**Comment by synox** [comment]
I already described how to fix this in https://github.com/hlxsites/vg-macktrucks-com/issues/63#issuecomment-1597522826

**Comment by girishdigrajkar** [comment]
Hi @manuel-vara, As discussed please assign it to test once the actions on this ticket are completed.  thanks..

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
