### ISSUE TITLE
Bug: Missing Google logo in Dealer locator sidebar (Volvo and Mack Trucks) 

### ISSUE THREAD

**Issue by DanielaPedrochevd** [hlxsites/vg-macktrucks-com#553]
The Google logo is hidden behind the sidebar the only way see it is to collapse the sidebar. Should be visible when the sidebar is open. 

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/144998505/da8d2a45-44d6-4702-96c0-997cf9260b5a)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/144998505/b132852f-250b-4284-8f96-87ce29a6c1bd)

**Comment by DanielaPedrochevd** [comment]
To solve this issue we are going to shorten the height of the sidebar so that the Google logo is always visible.

**Comment by ZoeBeykirch** [comment]
Closing this as no longer needed - as long as Google is visible and displayed, we are meeting the requirement.
