### ISSUE TITLE
FR: Dealer Locator API Call reduction

### ISSUE THREAD

**Issue by DanielaPedrochevd** [hlxsites/vg-macktrucks-com#554]
**Agile requirement**
As a business owner, I want to decrease the number of API calls, to reduce the service cost of the API.  

**Description**
Starting in December we doubled our experience of service calls for the API service for the dealer locator. In turn our bill went up accordingly.
In order to keep our license cost down – we will change a small portion of functionality on the locator.
Hours will be adjusted to show the direct content and time frame.
Today the locator shows you if a Dealer is open based on your geo location.
If you looked up a dealer from California and it was 8PM – it would dynamically say a dealer was closed on the east coast that closed at 6PM EST.
Tomorrow the time will display statically with the time showing 8-5 with context of that dealer is in X time zone (not specifically your time zone being taken into account.
All department hours will be combined.

**Acceptance Criteria**
- The API call is done when a user clicks on the "more" button of a specific dealer from the dealer locator list sidebar. 
- When a user clicks on the "more" button the open or closed information of the dealer is displayed along-side its working schedule in only one line (e.g. "8am-5pm") combining all the department hours. 
- If there is no schedule information a message that reads "No schedule information available" is displayed.  
- The open or closed info isn't displayed in the dealer list from the dealer locator sidebar. 
- This is applied to MT and Volvo Trucks.

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd @Gonzalo-CG Is there another way to calculate the time zone without using the API?

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd @Gonzalo-CG Discussed this issue with @Joesturbo. If simply displaying the business hours (e.g., 8am-5pm) to the user can be a quicker and easier fix, then let's do that. Keep it as simple as possible, but we need to stop using the API asap. Thank you!

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd @SantiagoHomps-NC Let's go with that solution, please. Thank you for your quick response!

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG @DanielaPedrochevd Let's also plan to deploy this as a hot fix in the next sprint.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the ticket to done.
Please see attached document in case additional details are required ... 

[Test Summary 524.docx](https://github.com/hlxsites/vg-macktrucks-com/files/14111025/Test.Summary.524.docx)
