### ISSUE TITLE
Bug - Minor - Chrome browser - Trucks: Anthem: Specs - Line above the Base Configurations slightly overlaps the Truck image

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#557]
(This ticket has been copied over from the [Redesign Board](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/97))

### Issue Type

Bug

### Summary

[hero] height is set incorrectly 

### Priority

Critical

### Description
On the Trucks: Anthem: Specs page, the line above Base Configurations slightly overlaps the truck image. This happens because the Hero with variant 'specs' is set to `max-height: 70vh`. Therefore, on wide viewports the image (set to `width: 1000px;`) will overflow the block.

### Affected Device Classes
Tablet, Desktop – on wide viewports

### Affected Browsers/Devices and Versions
All

### Steps to reproduce:
01. Open https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/specs/ on Chrome browser
02. Notice the line overlapping the image

### Expected result:
Line should be just below the image

### Actual result:
The line above Base Configurations slightly overlaps the Truck image

<img width="1516" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/728d6780-ff9a-43db-8293-1e3e9ae1eb1b">

**Comment by ZoeBeykirch** [comment]
This ticket seems to now be resolved, I see everything rendered without overlapping the truck image on production: https://www.macktrucks.com/trucks/anthem/specs/

**Comment by ZoeBeykirch** [comment]
@girishdigrajkar do you have time to test this and confirm if we can close out this ticket?

**Comment by girishdigrajkar** [comment]
Validated and able to see the correct results and hence, marking the ticket to done status:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e20cf7df-b2c6-47de-bc2a-ddf1c6452e5f">

**Comment by girishdigrajkar** [comment]
Kannan faced issues on small desktop size (landscape mode) hence reopening

**Comment by WendyKruger** [comment]
We can deprioritize to a 2.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZoeBeykirch** [comment]
Closing ticket as specs section design has changed with redesign, therefore this wont be needed.
