### ISSUE TITLE
Task: Mack LA Export Configurator Launch Effort (Mexico test)

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#558]
### Description
For this ticket we will test only the Mexico market configurator.

Leveraging the work that has been done for the [USA Mack truck configurator ](https://github.com/hlxsites/vg-macktrucks-com/issues/717)and the recent [spike investigation](https://github.com/hlxsites/vg-macktrucks-com/issues/790), this ticket is a placeholder to visualize the work to be done by the Dev team for the Latin America market sites configurator launch for Anthem and Granite models.

### Acceptance Criteria for Front End

- [x] Configure the configurator for Mexico and test
- [x] Review and improve/refactor the loading of the configurator 
- [x] Check that the correct emission standard query parameter (euro3 euro5 ghg) depending on the country is added to the desired link. Excel sheet for reference: https://projects.netcentric.biz/wiki/x/Y9vHHg. Update 05/09/2024: Kalle will add an option in the configurator to set the emission level inside the powertrain section.

### AC Content
- [ ] Content team to update the new URL in MX site (new export market multi tenant URL) (Currently from the drop down menu on the MX homepage, the Anthem "Build Yours" links to the main configurator and not the Anthem truck on the configurator

**Markets for configurator:** 
| Country | Language | Locale | Emissions Options |
|----------|----------|----------|----------|
| 1. Argentina | Spanish | es-AR | Euro 3, Euro 5 | 
| 2. Bahamas | English | en-BS | Euro 3, Euro 5 |
| 3. Bolivia | Spanish | es-BO | Euro 3, Euro 5 |
| 4. Chile | Spanish | es-CL | Euro 5, GHG|
| 5. Colombia | Spanish | es-CO | Euro 5, GHG |
| 6. Costa Rica | Spanish | es-CR | Euro 3, Euro 5 |
| 7. Dominican Republic | Spanish | es-DO | Euro 3, Euro 5 |
| 8. Ecuador | Spanish | es-EC |  Euro 3, Euro 5 |
| 9. El Salvador | Spanish | es-SV | Euro 3, Euro 5 |
| 10. Guatemala | Spanish | es-GT | Euro 3, Euro 5 |
| 11. Guyana | English | en-GY | Euro 3, Euro 5 |
| 12. Haiti | English | en-HT | Euro 3, Euro 5|
| 13. Honduras | Spanish | es-HN | Euro 3, Euro 5 |
| 14. Mexico | Spanish | es-MX | GHG |
| 15. Nicaragua | Spanish | es-NI | Euro 3, Euro 5 |
| 16. Panama | Spanish | es-PA |  Euro 3, Euro 5 |
| 17. Peru | Spanish | es-PE | Euro 3, Euro 5 |
| 18. Trinidad & Tobago | English | en-TT |  Euro 3, Euro 5  |
| 19. Venezuela | Spanish | es-VE | Euro 3, Euro 5 |

### Notes for QA:

Links to test:

anthem - https://main--vg-macktrucks-com-mx--hlxsites.hlx.page/trucks/anthem/build/#/anthem
granite - https://main--vg-macktrucks-com-mx--hlxsites.hlx.page/trucks/granite-series/build/#/granite

### Old Acceptance Criteria 

**How to test the Latin America market:**
If your page has a meta tag in the header with name "locale" and a value corresponding to one of the latin markets, the configurator will load Spanish localized data. You can also override it using the query parameter ?market=la

Main Links:
1. Anthem link: https://truckbuilder-mack-100031.onecx.prod.rapidimages.net/#/anthem
2. Granite link: https://truckbuilder-mack-100031.onecx.prod.rapidimages.net/#/granite
3. Truck selector link: https://truckbuilder-mack-100031.onecx.prod.rapidimages.net/

Example of adding locale and emissions:
- https://truckbuilder-mack-100031.onecx.prod.rapidimages.net/#/anthem?market=la?el=euro3
- https://truckbuilder-mack-100031.onecx.prod.rapidimages.net/#/anthem?market=la?el=euro5
- https://truckbuilder-mack-100031.onecx.prod.rapidimages.net/#/anthem?market=la?el=ghg

**The bundles needed to link are called:**

 - configurator.bundle.js
 - configurator.css

**Some features to test:**
- The leads form should now use different form handlers when on the Latin market (needs to still be properly though!)
- More country options in the form, should be all markets
- Market-specific options: DEF tanks, black fenders, and mining dumper
- Email feature hidden on Latin markets
- Localized content for most fields (still waiting for some from Catelyn that we sent in late)
- Filter by emission level by adding the query parameter ?el=x to the URL, where x is either euro3, euro5, or ghg.

**These are the remaining changes Rapid Images should finish by August 27th:**
- Adding support for a language field in the leads form
- Making sure that the jobRole and industry fields send their non-localized values in the form

**These things are not yet included and coming soon:**
- English localization for Guyana, Bahamas, and Trinidad & Tobago markets (it will just load the US market data for these)
- No language field in the leads form yet

- [ ] Update Constants file to add helix-truckConfigurator and helix-truckConfigurator Tabs to match the structure of the [USA Constants file](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B723FA665-4A8B-400F-AF89-02FF2B6DFABE%7D&file=constants.xlsx&action=default&mobileredirect=true). The URLs will be different - highlighted below in notes. (Not needed)
- [ ] Regression testing of all pages of the Truck Configurator
- [ ] Refactor the way of loading JS and CSS of Rapid Images (Check if it can be improved)
- [ ] Update URLs of JS and CSS to be loaded (Not needed)

**Comment by BeckyMedlin** [comment]
@shirin27 Please add this to the list of tickets to be refined.

**Comment by ZoeBeykirch** [comment]
@cogniSyb Thank you! Please include @amglebihan in your communications with Kalle too if he hasn't already been involved yet.

**Comment by ZoeBeykirch** [comment]
[Update from Rapid Images:](https://adobe-dx-support.slack.com/archives/C05JATBN087/p1719405980731329) Regarding the Latin America rollout, here is a rundown of the discussions me and Syb have had on this topic:
- We need a way to know that we're on the shared Latin American market, so that the configurator knows what locale data to load. The domain names vary wildly between these different markets though, so there is no straightforward way to use the URL for this.
- Syb suggested that we use the language attribute on the HTML document instead. Someone on the NetCentric side would have to make sure that this attribute is accurate across the markets.
- We also need to decide how to determine which values should correspond to the Latin America market. A simple way would be to hardcode the list into the configurator. Optionally, if you want to be able to control this from the NetCentric side, we could use some other meta attribute in the document to store this list. If we are to hardcode it, we need a list of the relevant language codes.

**Comment by amglebihan** [comment]
@ZoeBeykirch @Kannan-CM I created two pages where the configurator is set up: one for the [Anthem truck](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BE300B047-B959-4146-B7C2-AE15CF89F01B%7D&file=index.docx&action=default&mobileredirect=true) and one for the [Granite series truck](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BEDDE2708-190B-4D37-8594-C4E5AF7AFB5E%7D&file=index.docx&action=default&mobileredirect=true). However, I simply copied the content from macktrucks.com, so the content and metadata will need to be updated.
Additionally, Kalle will be adding an option in the configurator to set the emission level within the powertrain section. No action is required on our part, but we won't be able to test it until Kalle completes the task.

**Comment by ZoeBeykirch** [comment]
Metadata has been updated

**Comment by verareljic** [comment]
Remaining actions from Cognizant Netcentric side: testing.

**Comment by ZoeBeykirch** [comment]
Update from Kalle: We changed the way that emission levels are handled for the latin markets - now they are selected as an option in the powertrain step. This means you no longer need to use the el query parameter. Everything is live and available to test now in prod.

**Comment by ZoeBeykirch** [comment]
@girishdigrajkar updated the ticket, so only test the links under the Notes for QA: Links to test:

[Anthem truck](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BE300B047-B959-4146-B7C2-AE15CF89F01B%7D&file=index.docx&action=default&mobileredirect=true)

[Granite series truck](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BEDDE2708-190B-4D37-8594-C4E5AF7AFB5E%7D&file=index.docx&action=default&mobileredirect=true).

Thank you!

**Comment by silviulungu** [comment]
@Kannan-CM Validated about to documents/URL's and notice below issues that need your attention.

1. [Anthem truck](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BE300B047-B959-4146-B7C2-AE15CF89F01B%7D&file=index.docx&action=default&mobileredirect=true)

Should show Euro5 and GHG as emissions, instead is showing Euro5 and Euro3

2. [Granite series truck](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BEDDE2708-190B-4D37-8594-C4E5AF7AFB5E%7D&file=index.docx&action=default&mobileredirect=true).

Emission is not authored at all.

Please correct it and assign it for testing. 
Thank you!

**Comment by silviulungu** [comment]
Here are the observations after testing:

1. The "Financiamiento" page is blank for both Anthem and Granite.
![Screenshot 2024-09-18 at 1 13 54 PM](https://github.com/user-attachments/assets/cc3e2ebe-b07f-45f6-8b36-70b56540d68f)

2. The order of the emissions (Euro5 and GHG) is not displayed correctly on the page for Anthem. 

3. The RapidImage for "Interior" specifications is not loading and displays the following error: "Se agoto el tiempo de espera para la representacion" 
![image](https://github.com/user-attachments/assets/43941843-28b8-49e7-9c31-a1788a03f1a6)

4. The PDF document that customer have to download at the end of the configuration is in english instead of spanish.
<img width="1262" alt="Screenshot 2024-09-18 at 13 02 09" src="https://github.com/user-attachments/assets/fcf1d1b0-1f69-4bbb-8eea-250eb4f02963">

I also need the requirements for the PDF document to check what should contain.

Thank you!

**Comment by ZoeBeykirch** [comment]
Kalle from Rapid Images has been contacted to make the emissions changes (this is now no longer handled by the document and is handled by RI). I have also sent the other QA findings to the Mack Export product team.

**Comment by ZoeBeykirch** [comment]
Emissions have now been corrected

**Comment by ZoeBeykirch** [comment]
Ready for re-testing! 

Granite interiors not loading -> this has been fixed
Remove financiamento -> Done. Also removed "Service Contracts", as this should be available either

**Comment by silviulungu** [comment]
I encountered these errors on truck builder on mexico. I need Kalle intervention in order to move forward.
<img width="1723" alt="Screenshot 2024-09-24 at 15 12 07" src="https://github.com/user-attachments/assets/1a777cc2-db23-4cdc-b7ac-3700d01cf92f">

**Comment by ZoeBeykirch** [comment]
@silviulungu It has not been published yet, that is why you are seeing those errors. We can only test the pre-production links: 

anthem - https://main--vg-macktrucks-com-mx--hlxsites.hlx.page/trucks/anthem/build/#/anthem
granite - https://main--vg-macktrucks-com-mx--hlxsites.hlx.page/trucks/granite-series/build/#/granite

**Comment by silviulungu** [comment]
Testing has been completed and everything has been fixed and works accordingly.
However i would like to know in what language the PDF document should be.
Thank you!
<img width="1672" alt="Screenshot 2024-09-25 at 09 40 49" src="https://github.com/user-attachments/assets/5bd2e16d-01a0-4bf5-82d4-2697f60e821b">

**Comment by ZoeBeykirch** [comment]
PDF should be in Spanish, but business team needs to translate it. Not a blocker for go-live.

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly.

**Comment by ZoeBeykirch** [comment]
@silviulungu did you test the form submission too? That piece is ready now if you haven't already tested it

**Comment by silviulungu** [comment]
After completing the truck builder form and fill the blanks with personal data, the user does not receive any mail of confirmation.

**Comment by ZoeBeykirch** [comment]
Plan is to go live with Mexico configurator first thing on Monday Oct 21

**Comment by ZoeBeykirch** [comment]
Closing as we are now live! 
https://www.macktrucks.com.mx/trucks/granite-series/build/#/granite
https://www.macktrucks.com.mx/trucks/anthem/build/#/anthem
