### ISSUE TITLE
Bug: Hidden pages with nofollow noindex showing in on-site search results

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-macktrucks-com#560]
As a customer I want to be able to type any keywords in the search bar and enter the search request so that all items that are related to the keyword in the website will be retrieved and displayed on the search results page and I can find the information that I was looking for. 

URL: https://www.macktrucks.com/search
Browser: Chrome

**Steps to reproduce**
- Go to https://www.macktrucks.com/search
- Type in incentives
- View the search results page

**Expected results**
See all items related to incentives.
No pages with "no follow, no index" metadata should be returned via on-site search. 

**Expected Outcomes on All EDS Domains**
The solution to this bug should be applied not only to the Mack USA site, **but to all Mack market sites, Volvo Trucks USA and market sites, and Road Choice website to ensure this bug is not happened across any other domain we manage.** 

**Actual results**
A hidden page shows up in the results: https://www.macktrucks.com/nav-current

**Screenshots:**
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/4a1c5558-94a9-4682-a546-584408b32926)
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/126615590/e700f9ca-098a-41d8-b114-d7391ca725b0)

**Comment by BeckyMedlin** [comment]
@mollyaljenkins @shirin27 Please add this to refinement session. Thank you!

**Comment by girishdigrajkar** [comment]
Search team needs to come up with SPs to fix this bug ( Testing input : 2SPs)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/834b155d-84d7-418e-9fd7-b588edf9bdc0">
