### ISSUE TITLE
NFR: Deploy new form handler code on Footer for Subscribe Box

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#561]
**Non-Functional Requirement Description:** 

On the footer of macktrucks.com the "Stay in touch" text box for users to submit their email address in order to subscribe to Mack Truck marketing automations requires code push changed so that we can change the backend system from sending email submissions from Eloqua to the new Salesforce Marketing Automation Account Engagement (MCAE) system. 

Add JSON for this component:

Endpoint URL for form: https://go.pardot.com/l/1038343/2024-02-02/3m76gq
Form handler code: < form action="http://go.pardot.com/l/1038343/2024-02-02/3m76gq" method="post"> 
*Note in the above form handler code there shouldn't be any spaces between the < icon - in Github it will not display the code without a space between characters

**Acceptance criteria:** 
- Tested/Reviewed by Mack Trucks Marketing Team to verify new email prospects fields are correctly coming in MCAE
- Changes should be applied to global footer present on all pages for Mack USA. 

**Open point:**
- Can we remove the checkbox? If so, we can re-use the Volvo block for this, and just re-skin it for Mack, which would make it much easier. - @ZoeBeykirch @BeckyMedlin confirmed we can start without the checkbox in this ticket, and have a follow up ticket if it's a must have.

**Comment by BeckyMedlin** [comment]
@mollyaljenkins @DanielaPedrochevd @shirin27 Please refine this ticket asap so that work can begin. We're migrating off of Eloqua to Account Engagement and need this completed before Feb. 15.

**Comment by BeckyMedlin** [comment]
@ryanropero Can assist with testing. @jonatan-lledo-netcentric @girishdigrajkar

**Comment by girishdigrajkar** [comment]
Validated and able to see correct UI changes :

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/8f77decb-c7e2-4939-87c8-dc02accb768a)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/8f77decb-c7e2-4939-87c8-dc02accb768a)

**Comment by girishdigrajkar** [comment]
@ryanropero :  Please confirm for AC 1 ;  Kindly let us know in case of any UI test data to be created for your tests. thanks

**Comment by BeckyMedlin** [comment]
Released in Release 7 on 03/12/2024:  https://github.com/hlxsites/vg-macktrucks-com/releases/tag/v.1.0.6
