### ISSUE TITLE
NFR: Add all repositories to the VolvoGroup - Franklin sites (PRODUCTION) project

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#562]
**Today**, we are actively using two projects:
- [VolvoGroup - Franklin sites (PRODUCTION)](https://github.com/orgs/hlxsites/projects/8)
- [Volvo US & Mack Trucks Redesigns](https://github.com/orgs/Netcentric/projects/2)

**Tomorrow**, we would like to only use [VolvoGroup - Franklin sites (PRODUCTION)](https://github.com/orgs/hlxsites/projects/8).

**Acceptance criteria:**

- [ ] All the labels and milestones used on the previous project are part of the new project
- [ ] All the issues assigned to the previous project are migrated to the new project, in their correct state, and with all the information attached to them

**Comment by shirin27** [comment]
@BeckyMedlin fyi - the ticket to migrate the re-design project to this one.

**Comment by BeckyMedlin** [comment]
@shirin27 Please add to refinement

**Comment by shirin27** [comment]
@shirin27 set a date and let the team know tickets are being moved.
