### ISSUE TITLE
NFR: Bulldog Magazine "Subscribe to Magazine" Anchor Link Button Functionality 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#563]
**Non-Functional Requirement Description:** 
As a content editor, I want to change the "Subscribe to Magazine" CTA button functionality that is part of the sticky Bulldog Magazine hamburger menu on the [Bulldog Magazine ](https://www.macktrucks.com/magazine/) so that when a user clicks it will bring them to fill out a form the bottom of the page: https://main--vg-macktrucks-com--hlxsites.hlx.page/magazine/#subscribe-to-bulldog-magazine 

**Swap Bulldog Magazine Eloqua form with Pardot form code:**
Link: http://go.pardot.com/l/1038343/2023-12-12/3m4w2c
<iframe src="http://go.pardot.com/l/1038343/2023-12-12/3m4w2c" width="100%" height="500" type="text/html" frameborder="0" allowTransparency="true" style="border: 0"></iframe>

**Screenshots:**
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/8124e0b1-ba81-48bf-8b61-81786879bf1f)

**Form fields (if needed):**
First Name (r) [Default Field: First Name]
Last Name (r) [Default Field: Last Name]
Company (r) [Default Field: Company]
City (r) [Default Field: City]
Phone (r) [Default Field: Phone]
Job Role (r) [Custom Field: Job Role]
Email Address (r) (a) [Default Field: Email]
[Custom Field: Marketing Opt-in]

**Acceptance criteria:**
- [ ] Tested/Reviewed by Mack Trucks Marketing Team to verify new email prospects fields are correctly coming in MCAE
- [ ] Form should be updated on all markets
- [ ] For all instances that the user clicks on the "subscribe to Bulldog" - including all the hamburger menu Magazine sections (Homepage, [Explore all articles](https://www.macktrucks.com/magazine/explore-articles), each of the 8 category pages (Customer Profiles, Features, In the Know, In the News, Product Updates, Technology at Work, Calendar, Viewpoint, [archives](https://www.macktrucks.com/magazine/bulldog-magazine), the new expected behavior would be to bring the user back to this same section: https://main--vg-macktrucks-com--hlxsites.hlx.page/magazine/#subscribe-to-bulldog-magazine 
- [ ] Update the CTA in the subnav to work with the new anchor link instead of the flyout (example: https://main--vg-macktrucks-com--hlxsites.hlx.page/magazine/#subscribe-to-bulldog-magazine)

**Comment by BeckyMedlin** [comment]
Dependency on Mack Marketing team to provide the previous list from Eloqua to migrate to MCAE.

**Comment by BeckyMedlin** [comment]
Per @ryanropero Casi has provided the list he needs.

**Comment by BeckyMedlin** [comment]
@shirin27 Please add to list of tickets to refine. Thanks!

**Comment by CasiMcDaniel** [comment]
> Dependency on Mack Marketing team to provide the previous list from Eloqua to migrate to MCAE.

This was complete weeks ago in MCAE.

**Comment by girishdigrajkar** [comment]
**Open Issues/Observations:**
1. Expected pardot code (iframe ) and actual one differs
2. Below AC is failed as branch URL only works for Bulldog Magazine page CTA ... Other section CTAs are not clickable:
"Form should be updated on all instances that the Bulldog hamburger menu is displayed on the Magazine sections (Homepage, [Explore all articles](https://www.macktrucks.com/magazine/explore-articles), each of the 8 category pages (Customer Profiles, Features, In the Know, In the News, Product Updates, Technology at Work, Calendar, Viewpoint, [archives](https://www.macktrucks.com/magazine/bulldog-magazine), etc. The new expected behavior would be to bring the user back to this same section: https://main--vg-macktrucks-com--hlxsites.hlx.page/magazine/#subscribe-to-bulldog-magazine"

**Comment by girishdigrajkar** [comment]
Validated and now below are outstanding observations:

1.  Navigate to URL  https://563-magazine-button--vg-macktrucks-com--hlxsites.hlx.page/magazine/bulldog-magazine 
   Click on 'Subscribe to Bulldog'  and observe,  Initially it does not go to subscribe form section ... In Later attempts it takes 
    to correct section.
2.  Clicking twice on 'Subscribe to Bulldog' takes user back to top of the page which is incorrect.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, marking this ticket to done status.

**Comment by BeckyMedlin** [comment]
Released in Release 7 on 03/12/2024:  https://github.com/hlxsites/vg-macktrucks-com/releases/tag/v.1.0.6
