### ISSUE TITLE
FR: MT Truck configurator - og tags

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#567]
As a user sharing my configuration on social media, I want my post to include a nice image, title and text when I share it.

**Today**:
When sharing your configuration on social media, my post looks like this:

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/135319298/6a876c14-b081-4d0a-beef-37d8c1403172)

**Tomorrow**:
@WendyKruger please help us define the future state. Post should include a generic image, a generic title and a generic description.

**Comment by BeckyMedlin** [comment]
@shirin27 Please advise on the measurements. Thank you!
