### ISSUE TITLE
FR: MT - Pardot form block

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#568]
**Description**
Forms to be moved to Pardot (@BeckyMedlin @ZoeBeykirch @KJohnsn can you confirm?)

https://www.macktrucks.com/ -> footer form for Stay in touch
https://www.macktrucks.com/buy-mack/request-a-quote/ -> already a Pardot form, but with eloqua references in the code
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/135319298/674f7d67-5931-4ec9-8e51-9fb141939dc6)
https://www.macktrucks.com/about-mack/contact-us/contact-us-form/ -> already a Pardot form, but with eloqua references in the code

**Acceptance criteria**

- The pardot form block is available on MackTrucks, following the brand's identity in terms of styling
- If cookies are not accepted, the form is not loaded on the page

**Open points**

Q: What do we show instead, when the user has not accepted the cookies
A: Check what is already done for Eloqua, and also align with the Config OneTrust approach in the corresponding ticket

**Comment by BeckyMedlin** [comment]
@mollyaljenkins Need description of ticket, please.

**Comment by BeckyMedlin** [comment]
@mollyaljenkins Forms should display even if cookies aren't accepted per @WendyKruger.

**Comment by KJohnsn** [comment]
This ticket is not needed and it can be closed @mollyaljenkins
