### ISSUE TITLE
FR: MT Solutions Engine Row All trucks variant

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#580]
From vg-macktrucks-com-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-macktrucks-com-rd#137  

**Agile Requirement**
As a business owner, I want to display different engines in a list form as in the design -> https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=1968-227762&mode=dev

It’s related to #55; the All Trucks page.

**Description:** 
- three background colour states 
  - row dark
  - row light
  - row hover
- Image is to the left, hovering over dots background image
- Text elements to the right
  - Title, details of product, 'explore' button
- Explore button can be primary buttons as in All Trucks

**Solutioning**
Existing code should be refactored a bit to reuse the same block on both pages.
- Rename block from `v2-all-trucks` to something more generic, `v2-product-listing`
  - Renaming block would entail also to rename variables and classnames (like `truckElement`, `truckImageWrapper` `v2-all-trucks__truck-image`)
- Functionality for filtering should only be executed when the variant `with-filter` is applied to the block.
  - [Roughly the last part of the code](https://github.com/Netcentric/vg-macktrucks-com-rd/blob/main/blocks/v2-all-trucks/v2-all-trucks.js#L40-L161) should only be executed when variant `with-filter` is enabled
  - The All Trucks page will be updated to contain this variant
- When hovering the product image, white background should show
- When hovering the primary button, the product background image and white background should show

![Image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/158284953/0f636829-87d0-4e7f-a74a-0def4445f62b)

**Comment by shirin27** [comment]
propose design change to use the same solution https://github.com/Netcentric/vg-macktrucks-com-rd/issues/136

**Comment by shirin27** [comment]
Questions:
- Secondary buttons are used in this listing, could we make them primary, as in All Trucks?
- GT America is used in the headings. in All Trucks Helvetica Neue LT Pro is being used. On both pages these headings will be H2 level. Could we change the headings in All Trucks to GT America?

**Comment by shirin27** [comment]
@WendyKruger can you answer Syb's questions please?

**Comment by shirin27** [comment]
> * Secondary buttons are used in this listing, could we make them primary, as in All Trucks?
> * GT America is used in the headings. in All Trucks Helvetica Neue LT Pro is being used. On both pages these headings will be H2 level. Could we change the headings in All Trucks to GT America?

Questions have been answered with a 'yes' during the last meeting

**Comment by shirin27** [comment]
- Ability to show block without filtering (the block on diesel engines page doesn’t filter)
- Should be able to include v2-pencil-promo, #108 (as [per design](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2231-57714&mode=dev))
  - Filtering interaction should work on the pencil-promo block that is included

Zoe to work with Wendy to create this ticket

**Comment by girishdigrajkar** [comment]
Validated and only below observation is outstanding : 
**Desktop:**
Details section padding is 45 (Left) 5(right) None(top, bottom)  whereas expected is  40 (top, bottom)X 88(Left, Right)

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/74972683-7784-4b90-8436-5102d3282640">
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/d0151358-dc3a-4939-a391-b10ebf8c98c5">

**Comment by girishdigrajkar** [comment]
Validated the changes and able to get the correct results and hence, this ticket could be closed :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/110075f9-0543-4b75-acc9-ede3567eb650">
