### ISSUE TITLE
Content Task - Mobile view - Magazine page - The styling of the Explore Past Issues button makes it unreadable in Mobile view

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#584]
From vg-macktrucks-com-rd created by [Andrei-Boiangiu](https://github.com/Andrei-Boiangiu): Netcentric/vg-macktrucks-com-rd#98  

On the Magazine page, the Explore Past Issues button is unreadable in Mobile view

**Steps to reproduce:**
01. Open https://www.macktrucks.com/magazine/ on Mobile view and scroll down to About Bulldog Magazine section
02. Notice the Explore Past Issues button

**Expected result**
Styling of Explore Past Issues button makes it unreadable on Mobile view

**Actual result**
Explore Past Issues button is unreadable in Mobile view

<img width="291" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/b8479f4c-cf63-467c-a973-4df4cb8e5c46">

UPDATE: also on Tablet view

<img width="451" alt="image" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/127409602/e763f50b-cdb7-4112-85f3-1456d2f6626f">

**Comment by shirin27** [comment]
#92

**Comment by shirin27** [comment]
@cogniSyb @DanielaPedrochevd since this is a bug on the live website, can we move it to the Franklin board?

**Comment by shirin27** [comment]
We will discuss it with the team tomorrow this is major so I put it to priority 1 an plan it for sprint 7, for the moment and we'll see what team picks it up in tomorrow's refinement.

**Comment by shirin27** [comment]
@ZoeBeykirch We’ve discussed this before, I’ve looked up my comments from a chat:
> We didn’t touch anything of Bulldog Magazine. Though it could be regression. Either way it wouldn’t be a P1 issue. I think it’s rather a content issue. There is no other button style that can be used out of the box, so changing the background image would help here

I did take a look again at the code, there’s no change from the redesign that changed the buttons here. The fact that the block below has a button with white colours is due to it being styled specifically. I recommend to change the background image

**Comment by shirin27** [comment]
still present as described above

**Comment by shirin27** [comment]
@ZoeBeykirch Can this be taken by a content editor to change the background image as suggested?

**Comment by ZoeBeykirch** [comment]
Yes we can close this issue and I've assigned [an asana](https://app.asana.com/0/0/1206709221319427/f) task for @WendyKruger to help swap out the background images.

**Comment by Kannan-CM** [comment]
This section will not be in use. So, we are good to close the ticket
