### ISSUE TITLE
Content: MackTrucks Content Issues 

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#586]
From vg-macktrucks-com-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-macktrucks-com-rd#105  

After ticket https://github.com/Netcentric/vg-macktrucks-com-rd/issues/92. Posting here content ( or possible content) issues for visibility and review.

on Trucks -> Anthem
https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/trucks/anthem/
all videos on the page are error 403

On Magazine articles
https://develop--vg-macktrucks-com-rd--netcentric.hlx.page/magazine/articles/2023/may/savage-keeps-california-moving-with-mack-anthem
Thumbnail images on the sidebar article links are not displayed

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/144998505/913d138f-03fc-4745-9907-9fef25681243)

**Comment by shirin27** [comment]
@DanielaPedrochevd this isn't a redesign-related issue, should it be here?

**Comment by shirin27** [comment]
@shirin27 @DanielaPedrochevd Please move this issue to Franklin (Production) board. Thank you!

**Comment by shirin27** [comment]
Also could you please let me knwo if this is still an issue content team needs to address.

**Comment by Kannan-CM** [comment]
Hi @shirin27 ,

This issue is not related to the Production site.. on Production site images are appearing.

**Comment by BeckyMedlin** [comment]
Per @Kannan-CM this is not needed.
