### ISSUE TITLE
FR: video in hero (#3 of 4)

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#589]
From vg-macktrucks-com-rd created by [cogniSyb](https://github.com/cogniSyb): Netcentric/vg-macktrucks-com-rd#151  

Must be completed after https://github.com/hlxsites/vg-macktrucks-com/issues/607

### Context/Description
Update [v2-hero] to include video. Analogue to [v2-hero] of Volvo Trucks

**Agile Requirement** 
As a business owner I want to have a Hero block that will autoplay video content, which includes a pause button, so that users have the ability to let the video play while they interact with the page or stop it if they want to. 

**Related Tickets:** https://github.com/hlxsites/vg-roadchoice-com/issues/238

### Acceptance Criteria
**User AC:**
- The [v2-hero] block contains a video background that autoplays when a user enters the page 
- A pause button is located at the top right corner overlapping the media content of the hero block and is visible the entire time

**Editor AC:**
- Able to place an AEM video link in the header instead of an image

**Non-functional AC:**
- The pause button must be discernible from other controls and be clearly labeled and icon that indicates its functionality
- The pause/play button should be accessible to users navigating via keyboard, meaning it should be focusable and actionable using keyboard inputs. The focus style should be the same as for the scroll to top button
- Upon pressing the pause button, the autoplay video should immediately stop playing
- Once the video is paused, the [pause button should change to a play button]

(https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=566-2770&mode=dev)

**Questions** 

**Notes** 

- Created button https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/156
- Hero block https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/41
- There is no sound in the hero video blocks. 
- Hero videos will be under 2 mins. 

<img width="617" alt="Screenshot 2024-05-14 at 15 14 36" src="https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/bd07920a-1e1c-4741-a614-f0b68f893fe6">

![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/158284953/42de8130-8d9e-4561-96f6-c2d810265bc6)

Previous notes: 

Extend the hero by allowing an autoplay video as well for the hero.

Pause button to be created, see https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/156.
Blocks with an autoplay video should have a pause button, to comply with accessibility standards. Specifically, we’re mitigating [Failure 93 of Success Criterion 1.4.2](https://www.w3.org/TR/WCAG20-TECHS/F93.html).

Designs have been adjusted to show a pause button. For now, we’re focusing on the hero https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/41, [the design is available](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=6568-48961&mode=design&t=Rr7XpNdhodaMcgfL-4).

The video player for autoplay videos should have a visible pause button when the video starts playing
The button must be discernible from other controls and be clearly labeled and icon that indicates its functionality
The pause/play button should be accessible to users navigating via keyboard, meaning it should be focusable and actionable using keyboard inputs. The focus style should be the same as for the scroll to top button
Upon pressing the pause button, the autoplay video should immediately stop playing
Once the video is paused, the [pause button should change to a play button](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=566-2770&mode=dev)
The button should be large enough to be easily tapped on touch devices without accidentally pressing adjacent controls

**Comment by shirin27** [comment]
@cogniSyb Is this considered an enhancement?

**Comment by shirin27** [comment]
Yes @BeckyMedlin, this came out of a call recently with business and design.

**Comment by BeckyMedlin** [comment]
@verareljic @mollyaljenkins Why is this item flagged as blocked?

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, closing the issue.
