### ISSUE TITLE
FR - MT Card Row Block (4 cards row variant)

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#593]
From vg-macktrucks-com-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-macktrucks-com-rd#187  

**Agile Requirement**
As a business owner, I want to display content so that it follows the design, to achieve a more dynamic site: 

- [4 Cards Row](https://www.figma.com/file/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?type=design&node-id=478-32530&mode=dev)

**Description**

Create a new Card Row Block that contains a variant (4 Card Row block) that follows the above-mentioned design. 

**Acceptance Criteria**
1. As an editor, I can add a new "Card Row" block to any page. 
2. As an editor, I can add images and links to these cards so that users are redirected to them upon click. 
3. As an editor, I can select the 4 cards row variant (default variant).
4. For tablet viewport, need a 2-column grid with 2 cards per row. 
5. Editors responsible for selecting the correct variant.

**Comment by girishdigrajkar** [comment]
Validated using this [figma](https://www.figma.com/design/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?node-id=4774-20483&m=dev)  and able to get the correct results hence. closing the ticket.

Please see below screenshots for more information:
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/52740390-ad09-40d7-8b25-0f428ba07405)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/50a65e17-2e99-439c-872b-e83688d69ff0)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/087c5a60-bd0e-42c3-809b-034b0ed6f17b)
