### ISSUE TITLE
FR - MT Card Row Block (3 Card Product Variant)

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#594]
From vg-macktrucks-com-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-macktrucks-com-rd#189  

**Agile Requirement**
As a business owner, I want to enhance the product content display using an updated 3-row card block that adheres to our new design, thereby creating a more dynamic website.

**Description**

Create a new Card Row block variant (3 Product Cards) that follows the below-mentioned design.  The 3 Product Cards variant should include content presented in a textual list format, and on mobile devices, the cards should stack vertically for optimal viewing.

**Acceptance Criteria**
1. As an editor, I can select the new (3 Product Cards) variant from the Cards row block. 
2. The new variant follows the figma design and style mentioned below. 
3. The cards are stacked vertically in the mobile viewport.
4. On Tablet, we will maintain the desktop card size and horizontal layout. 
5. As an editor, I can configure this new variant by adding an image, a title (that works as a link) and some content displayed in a list form. 
6. As an editor it is my responsibility to add 3 cards and images following 7:5 aspect ratio. 

**Figma/Attachment**
Desktop: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2243-137822&t=YBNuoD7kznnR07FV-1

<img width="310" alt="image" src="https://github.com/user-attachments/assets/28773133-641f-456b-a6c7-9d843dbb9b6c">

Mobile: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2243-136446&t=YBNuoD7kznnR07FV-1

<img width="56" alt="image" src="https://github.com/user-attachments/assets/de7924ea-cfd2-49f2-be23-94d96561c545">

**Comment by AsmitKMishra** [comment]
1. Design matches with Figma.
2. It acts as expected for desktop, tablet and mobile.
3. Aspect Ratio is within the margin.
4. Could not confirm if the title can have a link as per requirement.

**Comment by santi-homps** [comment]
> Testing Completed. All seems good:
> 
> 1. Design matches with Figma.
> 2. It acts as expected for desktop, tablet and mobile.
> 3. Aspect Ratio is within the margin.
> 
> Except: Couldn't confirm if the title can have link as mentioned in the requirement.

@AsmitKMishra added the link functionality and linked it to the arrow. Nice catch!

**Comment by AsmitKMishra** [comment]
Cross Checked the link in title feature. It is available now. All the requirements are met now.
