### ISSUE TITLE
FR: V2 Hero block half-height variant

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#596]
From vg-macktrucks-com-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-macktrucks-com-rd#146  

**Agile Requirement**
As a business owner, I want to display a Hero-like design that contains a button so that my clients can easily access the page that allows them to buy my product. 

**Description** 
Create a new "half-height" block that allows editors to achieve the [figma design ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101618&mode=dev) buy adding a background image, a header and a button. 

**Acceptance Criteria**
1- As an editor, I can add this new block to any page. 
2- As an editor, I can configure this block by adding an image, a header and a button. 
3- As a user, when I click on the button I'm redirected to the link the editor configured. 
4- The height of the image varies depending on the height of the header, which should always be aligned to the left. 
5- As an editor, I can upload separate images for the different viewports. 
6- The solution follows the figma design specs: 

- [Desktop](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101618&mode=dev)

- [Mobile](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-102299&mode=dev)

- Tablet (same as mobile).

**Comment by shirin27** [comment]
@DanielaPedrochevd see comment on [issue 145](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/145)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, closing the ticket:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/88a26cd6-1f18-471d-abf9-f1338455510b">


<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/9c398455-ae9e-43d7-9a4b-4bd8a4968fa0">
