### ISSUE TITLE
FR: MT Image with Card Solutions Block

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#597]
From vg-macktrucks-com-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-macktrucks-com-rd#124  

**Agile Requirement**
As a business owner, I want to display an image with some descriptive text and related links so that my client can get more information on my products and its technical advantages. 

**Description**
Reusing testimonial block 

- Creating a new block with a different name, starting with testimonial block as a base for the code
- Name will be [v2-navigation-hub]
- Title, Descriptive text, button, links below

Create an image with card block that will allow editors to add it to any page and configure it by adding an image, a header, text, a button and a maximum of 6 links, this block will have 2 variants (left image or right image) 

**Acceptance Criteria**
1- As an editor, I can add the new "image with card" block to any page. 
2- As an editor, I can place the content to reflect either the left or right design. 

- Left Image (default)
- Right Image

3- As an editor, I can configure any of the above-mentioned variants by adding an Image, a header, text, a button, a subtitle and a maximum of 6 links (which will be displayed in 2 columns in desktop version and one under the other in the mobile version). It's the editor's responsibility to stay within the 6 links limit. 
4- The new block and its variants follow the Figma design for mobile and desktop: 

[- Left Image (desktop)](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101489&mode=dev)
[- Left Image (mobile)](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-102215&mode=dev)
[- Right Image (desktop) ](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-101534&mode=dev)
[- Right Image (mobile)](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-102235&mode=dev)

Design to be used as reference for button and link styling

- Will be an adaptation of the testimonial block 

**Technical hint**

The positioning of the images and cards (overlapping diagonally) is something that was also used in the V2 testimonial block.

Design Question: 

- Can the testimonial block be used? (Would require code alterations) 
  -  Answer: Yes can be used, as long as the button and links will remain.

**Comment by shirin27** [comment]
adding screenshots of Figma file here for my reference:
![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/dbe30bad-a8d3-41b4-b448-0f1373e0f2aa)
![image](https://github.com/Netcentric/vg-macktrucks-com-rd/assets/134631810/a18bff95-0b87-4844-ab76-328f82e86039)

**Comment by shirin27** [comment]
To be re-discussed to split it.

**Comment by girishdigrajkar** [comment]
Testing summary:
**Desktop:**
Margin is not as expected :    **[No fix needed]**
**[SV]** _The visual issue with v2-testimonial in practice was that the content would be larger than the picture. This would result in an uneven outcome* if we followed top: 100px as per Figma design. Our solution was to position the picture at the bottom of the block instead_

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/63ac0f0f-427e-4b77-a260-ecf9432262c9)

**Mobile:**
Padding is not as expected , Please see below:  [ **Changes in progress**]

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/0c0346d4-626c-40d1-9b47-531f21573ab7)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/3b62b3ba-707d-410d-9b18-4d2528d8b9c3)

**Comment by girishdigrajkar** [comment]
For padding Issue 2 in Mobile:   Fixed and able to get the correct results hence, closing the ticket. Thus, MT Image with Card Solutions Block is ready for prod:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/82ecb87a-5929-4fba-8b93-aba2afc4ee12">
