### ISSUE TITLE
Sub-navigation block for Bulldog Magazine

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#599]
From vg-macktrucks-com-rd created by [Gonzalo-CG](https://github.com/Gonzalo-CG): Netcentric/vg-macktrucks-com-rd#116  

### Description
The [Bulldog Magazine Blog page](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2210%3A65358&mode=dev) contains a sub-navigation in order to navigate the different blog categories.

This component is called [In-Page Navigation](https://www.figma.com/design/URJhT8pkntqc6h6v5wSLqx/Mack-Core-Design-Kit?node-id=478-73450&t=9QxI4QNVPcPoF7fN-0) in the Figma designs. We’ll have to create a new block for this context named [v2-sub-navigation]

Design:
<img src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/139977780/80a4eeb8-8d83-46cb-b37f-c12375b2fa6d" width="100%">

### Acceptance Criteria
- The sub navigation has the same design for Desktop & mobile as shown in Figma.
- Authors can set it up by creating a Word file in SharePoint that contains the links to be shown in the sub navigation, and the button (one for mobile and one for desktop).
- The sub navigation can be shown on a page by adding its URL (column URL), and the URL of the document to the configuration of the sub navigation (column V2 Sub Navigation) in the [metadata](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7Bca53d476-f493-46be-9978-141e77d808d6%7D&action=edit&activeCell=%27Sheet1%27!H51&wdinitialsession=6a801d7b-93c0-6b39-efc2-86639eb8491c&wdrldsc=3&wdrldc=1&wdrldr=AccessTokenExpiredWarningUnauthenticated%2CRefreshin) file.

### Notes
- The styles and some logic from [PDP - In-page navigation block](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/26) could be partly reused.

**Comment by shirin27** [comment]
@Gonzalo-CG Per @WendyKruger, this should be tag based as it should filter based on user's filter selection. Needs to be similar to how we filter the All Trucks segment (when you select electric, it'll only show electric vehicles).

**Comment by shirin27** [comment]
@Gonzalo-CG All Bulldog magazine items need to be developed together: #116 (this one), #117, #129, #130, #131, and #132.

**Comment by girishdigrajkar** [comment]
Validated and able to get desired results hence, closing the ticket

**Comment by WendyKruger** [comment]
@mollyaljenkins @BeckyMedlin @ZoeBeykirch I have a couple questions about this. 

---
First, I tried to test it on [this page](https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/magazine/bulldog-article-template) with this [subnav](https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/magazine/sub-nav) 

I followed the instructions to add the URL of the page and the subnav to the [metadata spreadsheet]

(https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BCA53D476-F493-46BE-9978-141E77D808D6%7D&file=metadata.xlsx&action=default&mobileredirect=true) 
![image](https://github.com/user-attachments/assets/ad375f86-a37a-45c0-b9c5-ee88a608b6f0)

Nothing is coming up on the page, but there is an empty section where the sub-nav should be

![image](https://github.com/user-attachments/assets/817276bf-f268-4229-b043-a4c2825757a1)

Same result if I add Magazine to the page metadata under Template and the metadata spreadsheet in the Category column.

Please explain exactly how this should work, and provide a page where I can see it in action.
---
Second, per the design the sub-nav should adjust to indicate the category of the current article by underlining it in red. Hope this was done.
![image](https://github.com/user-attachments/assets/f677cbfa-d6cd-469b-b074-6436141c10c1)

**Comment by amglebihan** [comment]
@WendyKruger There is a link that is mandatory that wasn't defined. "The subscribe button must be configured for both mobile and desktop, in that order." I've fixed it on your page. I see that it's overlapping with the hero now because a height isn't defined properly when no image is set in the sub-nav. We can fix that in a bug ticket.

**Comment by bfvolvo** [comment]
@BeckyMedlin Zoe and I have a scheduled meeting with Alan and Wendy Tuesday 10/22 to review the blocks.

**Comment by BeckyMedlin** [comment]
@ZoeBeykirch @bfvolvo If additional changes are needed, please create a new ticket. Thank you!

**Comment by bfvolvo** [comment]
> @ZoeBeykirch @bfvolvo If additional changes are needed, please create a new ticket. Thank you!

Sure, there is a likelihood that there may be a need for better instruction conveyed for the blocks use.

**Comment by ZoeBeykirch** [comment]
I have added this to the https://github.com/hlxsites/vg-macktrucks-com/issues/783 ticket to add clear instructions for content editors to use this new block in the sidekick library
