### ISSUE TITLE
FR: Magazine Tabbed Carousel (#1 of 4)

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#604]
From vg-macktrucks-com-rd created by [Gonzalo-CG](https://github.com/Gonzalo-CG): Netcentric/vg-macktrucks-com-rd#144  

### Description
A new block, similar to the [Tabbed Carousel Block](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/25) will be developed in order to achieve the design named in Figma as [Group 700](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2222-50879&mode=dev).

> The option to add a video to tabs and the auto-scrolling of tabs will be handled separately on issue Netcentric/vg-macktrucks-com-rd#208 

The design is the following:
<img  width="75%" alt="Screenshot of design" src="https://github.com/Netcentric/vg-macktrucks-com-rd/assets/133873665/3cb65bdf-8d33-4e33-9e54-62543be708f2">

### Acceptance Criteria
- [ ] The Dark variant of the Tabbed Carousel Block is available for authors to use on any page.
- [ ] The Dark variant of the Tabbed Carousel Block has the same design for Desktop & mobile as shown in Figma.
- [ ] As an author, I can configure the link that's displayed on every tab. (The Driven By Design text overlapping the media is a link). This text is manually added by the author
- [ ] The block is one tabbed carousel component - Not split into two blocks 
- [ ] Each item links to a magazine article
- [ ] The category and title of an article are pulled from the metadata
- [ ] If the title of an article is too long, it gets truncated with an ellipsis (to be defined when this happens)
- [ ] The first step of this block is to contain images and not video, which will get taken up in #607 

### Open Questions
- ~~Is this a tabbed carousel, or 2 separate components (a hero and some buttons below)?~~ **--> This is just one "tabbed-carousel" component.**
- ~~Is the "Driven by Design" text a link?~~ --> **Yes**
- ~~Does every tab of the carousel have the "subscribe" button overlayed on the top-right corner?~~ **--> Yes**
- ~~Does this block auto-scroll?~~ --> **Yes**

**Comment by shirin27** [comment]
Color contrast of inactive items is not sufficient for the small text. The contrast ratio of 3.9 can only be used for 18px+ text. It’s #000 at 50% opacity, which results in #808080. With 55% opacity we’ll end up with #747474 and an acceptable contrast ratio of 4.6.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, closing the ticket:

**Desktop:**
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/5ba4644d-2aff-4c0a-8050-b0337b604b21)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/53a307e2-302b-4f02-be11-4ff13741471d)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/e7a158c4-6778-41af-8d29-2d5f8435b2cb)
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/fa774e4a-0144-402a-b582-0e0545a207ed)

**Mobile:**
<img width="1728" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/cb09c70a-7ebd-4362-abf5-86fbc6d6cc4e">

**Tablet:**
<img width="1728" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/279fc4c8-db36-48d0-b85b-5891deb87185">
