### ISSUE TITLE
FR: Category Collage Block (1)

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#605]
From vg-macktrucks-com-rd created by [Gonzalo-CG](https://github.com/Gonzalo-CG): Netcentric/vg-macktrucks-com-rd#149  

### Description
The [Bulldog Magazine Blog page](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2210%3A65358&mode=dev) contains an image collage-like component that displays elements following a grid pattern on desktop viewports (on mobile, the structure is simply one image below the other as seen on [Figma](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2222-52229&mode=dev))

Each element consists of an image with text overlayed on its bottom-left corner and an arrow on the bottom-right corner.

Design:
![categories](https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/90af5c88-f738-4fd9-9ba4-b6270f2fffc2)

![categories-mobile](https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/a6d3173c-9221-4416-b057-a4167db90588)

### Acceptance Criteria (TBD)
- [ ] The Media Collage Block is available for authors to use on any page.
- [ ] The Media Collage Block has the same design for Desktop & mobile as shown in Figma.
- [ ] Same hover as #601 
- [ ] The media can be video or image
- [ ] If the category uses a video - it will autoplay 
- [ ] If the category uses a video - it will have a pause / play button on the top right corner
- [ ] Images have an aspect ratio instead of a fixed size
  - [ ] On mobile, the images have an aspect ratio of 4:3
  - [ ] On desktop, the images have an aspect ratio of 4:3, 8:3, and 6:5

Notes 

- Issue #602

**Comment by girishdigrajkar** [comment]
As per figma https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=15073-47376&m=dev **Blog Category** design all changes are as expected including added fix for video so closing this ticket :

<img width="1825" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/083707fe-7fed-4b77-847d-fa634588f599">

<img width="1825" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/ced10da6-f02c-4deb-a0c3-3ad915509480">
