### ISSUE TITLE
Refactor news.js to also support body-builder-news

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-macktrucks-com#63]
With https://github.com/hlxsites/vg-macktrucks-com/issues/36 the `News List` block was created. However the shared library `news.js` currently only fetches from `/mack-news.json` and not from `/body-builder-news.json`. 

Also note that the state is set on the global `window`, which currently prevents loading multiple different indexes.  

**news.js** 
https://github.com/hlxsites/vg-macktrucks-com/blob/d96c647e0aeb542d8b8e29386bc6f3e558e1c925/scripts/news.js#L9

**Indexes:**
 - main news index: https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-news.json  
   - (maybe should be merged with https://main--vg-macktrucks-com--hlxsites.hlx.page/mack-news/feed.json) 
 - body builder news index: https://main--vg-macktrucks-com--hlxsites.hlx.live/body-builder-news.json 
   - (to be created in https://github.com/hlxsites/vg-macktrucks-com/pull/51)

**Comment by synox** [comment]
The ticket is up to date. I am not working on this.

**Comment by girishdigrajkar** [comment]
Thanks @manuel-vara for a detailed call and below is the summary of outstanding actions you identified for this ticket to work. Thus, reopening the defect.

**Summary of  actions:**
1. Feed.xml  at "https://main--vg-macktrucks-com--hlxsites.hlx.page/parts-and-services/support/body-builders/news-and-events/feed.xml " is not updated ( ? missing job)
2. https://main--vg-macktrucks-com--hlxsites.hlx.live/body-builder-news.json   is missing info like description, publication date. 
<img width="1682" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/001e64f8-f4af-41bd-b91a-7738ac694ca6">
3. The UI does not show the description
<img width="1778" alt="Screenshot 2023-06-16 at 3 47 45 PM" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/c9b10c6d-aadc-436b-8500-d14a7dea6d1b">

**Comment by synox** [comment]
@manuel-vara a few hints: 
1. the file not being committed is addressed in https://github.com/hlxsites/vg-macktrucks-com/pull/252
2. in https://main--vg-macktrucks-com--hlxsites.hlx.page/body-builder-news.json the summary and publishDate are empty. That is because the `summary` and `date` fields are not set in the articles. You need either to set the metadata fields in the documents, or update the index. 
3. Once the metadata is updated and the index is published, you will see it reflected in the UI.

**Comment by girishdigrajkar** [comment]
Hi @manuel-vara, As discussed please assign it to test once the actions on this ticket are completed.  thanks..

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/7f36cf2f-be12-44d0-b38e-0f8f27abd3db">
