### ISSUE TITLE
Deactivate the OT check in our initial load script

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-macktrucks-com#638]
**Description**
On every export market, the cookie check needs to be removed to let OneTrust scan them. after the scan, the cookie checks have to be added again

### Cookies disabled
- [x] MT CA cookies desabled
- [x] MT HN cookies desabled
- [x] VT MX cookies desabled

### OneTrust Scan
- [x] MT CA scanned
- [x] MT HN scanned
- [x] VT MX scanned

### Cookies enabled
- [ ] MT CA cookies enabled
- [ ] MT HN cookies enabled
- [ ] VT MX cookies enabled

@jonatan-lledo-netcentric and @Kannan-CM to align on the timeframe for deactivation and please add it to the ticket.

**Comment by BeckyMedlin** [comment]
Per discussion w/ @Kannan-CM, this is already in progress.

**Comment by jonatan-lledo-netcentric** [comment]
@Kannan-CM Mack CA is ready for scan

**Comment by jonatan-lledo-netcentric** [comment]
@Kannan-CM Volvo MX also ready for scan

**Comment by jonatan-lledo-netcentric** [comment]
@Kannan-CM Mack HN also is ready for scan

**Comment by Kannan-CM** [comment]
@jonatan-lledo-netcentric ,

Here is the cookie code for HN:
18961cc8-1604-4bea-8e69-a5e7879e56c5

**Comment by Kannan-CM** [comment]
and for MackTrucks CA:
bbf7a698-6707-4c02-8cee-8cfa4d077625
