### ISSUE TITLE
Bug: Bulldog Magazine Categories Items Are Not Sorted From Newest to Oldest

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#655]
### Issue Type

Bug

### Summary

Recommendations and Recent Articles Blocks in Magazine Categories. 

### Priority

Critical

### Description

The Bulldog Magazine articles are not being displayed in chronological order. By default the Recommendations block used in Magazine Categories listing pages (Customer Profiles, Features, etc.) shows a number specified by the editor as for example: Recommendations(limit-5) or Recommendations(limit-10).

That means the limit of items to render is configurable but those items are not sorted upfront from the newest created to the oldest, meaning if we have more than 10 items for example, the latest ones will not be shown. Additionally, the recommended articles are displaying the 2 oldest articles from the category instead of the 2 newest. 

A fix to sort by descending creation date or created item should be implemented.

### Related Tickets
https://github.com/hlxsites/vg-macktrucks-com/issues/654
https://github.com/hlxsites/vg-macktrucks-com/issues/431

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Seems to be affected on all browsers and devices: Tested in Chrome, Edge, and Safari

### Steps to Reproduce

1. Navigate to https://www.macktrucks.com/magazine/
2. Click on any category
3. When the user views the list of articles, they are not being displayed in chronological order. 
4. If there are more than 10 articles published in a category, the most recent article will not appear at all in this list and only the oldest articles are displayed. 
5. Additionally, when the user clicks on any article and scrolls on the bottom, they are recommended to read the 2 oldest articles from the same category instead of the 2 newest articles. 

Examples:
https://www.macktrucks.com/magazine/categories/customer-profiles
https://www.macktrucks.com/magazine/articles/2024/february/coastal-waste-recycling-adds-mack-lr-electric-truck-to-fleet
https://www.macktrucks.com/magazine/explore-articles
https://www.macktrucks.com/magazine/categories/in-the-know
https://www.macktrucks.com/magazine/categories/features

Note: This bug is happening across all Mack export sites, and the solution should be applied not only to the USA Mack site but to Australia, Mexico, etc.

### Expected Results

Users should see the most recent articles in chronological order of newest to oldest articles. No matter if the user is browsing the Explore All article section, reading an article with the 'Recent Article' and 'Recommended' sections, so that users are seeing the newest and most relevant content. 

### Actual Results

Users are only seeing the oldest articles, which gives the impression that that no new articles are being published to the Bulldog Magazine. Additionally, if they are viewing an article list of more than 10, the newest articles will not be visible at all. 

### Attachment

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/687cc9f4-2271-4ba8-b9ca-d31a685e6709)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/1bf43891-0471-4a32-aad1-b186a44d86cb)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/48308be3-8f5e-4999-a322-6e3019b8e71a)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/7160f32c-ff40-4bb2-9704-d707fe0f7929)

**Comment by BeckyMedlin** [comment]
@mollyaljenkins Please refine in our next session. Thank you!

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/d0029e0c-c8c5-42d6-ab85-f25e8e78808e">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/51e8913f-e776-4790-afa9-189813c62737">
