### ISSUE TITLE
Bug: Bulldog Category and Product Filter is Not Working

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#656]
### Issue Type

Bug

### Summary

Explore Articles - Category and Product Tag Filters

### Priority

Medium

### Description

On the Explore Bulldog Magazine page, when a user selects either of the drop-down filter bars for Category or Truck model, when a new category or truck model is selected, the article content does not change and appears to be broken. No error message is present, but there is a lack of article content presented as the user would expect to see only their selected categories and/or truck models based on their selected criteria. This seems to be happening across all Mack export market sites and the solution will need to be applied to all exports in addition to the main USA site. 

Mobile only: The product filter bar is a lot wider than the category filter bar and makes for an award user experience as the drop down filter arrow is out of view, the user must scroll to the right to view the entire bar. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Seems to be happening across all devices and browsers. Testing in Chrome, Safari, and Edge using iPhone 15 iOS 17.3.1 and on iPad Pro (1024x1366), and desktop computer. 

### Steps to Reproduce

1. Navigate to: https://www.macktrucks.com/magazine/explore-articles
2. Select the "All Categories" filter bar on the left-hand side of the page and choose any category. 
3. Select the "All Trucks" filter bar on the right-hand side of the page and choose any product model. 

On mobile, the user sees the Truck model category bar is almost twice the width of the first category product filter bar and is an awkward user experience to select the truck models as the drop down arrow is out of view.  

### Expected Results

When the user selects a new Category or Truck Model filter, the expectation is that the articles displayed below shall update to only show the relevant articles based on the filtered selection. 

### Actual Results

The articles displayed below will not change or update, regardless of the categories/product models filters applied. 

### Attachment

Desktop:
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/3663bc8f-8ce1-46f2-a58a-2cd9750bacb4)
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/55f6a055-e0b9-4f9e-aca8-c1b650d1b100)

Mobile:
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/74bc453f-c33e-4549-8f27-7393c2c5c708)
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/4e5eecd1-6014-48be-ba76-a8d2ecf7c322)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results as Category and product filters are working now; Please see screenshots for more information.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/7ce2d649-04b7-4ef1-a373-13c17f1af5c4">

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/1ab4d4c1-4fbf-4632-b21c-c4676a1c8085)



Additional input to content team:  For Calendar articles the image has text which is cropped in mobile viewport; correct content needs to be updated.
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/efbb55d9-b898-46e6-9b22-5a66d8397002)
