### ISSUE TITLE
Header is missing logo when no submenu is defined

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#669]
### Issue Type

Bug

### Summary

[header] logo won’t render

### Priority

Critical

### Description

When the tabs are missing in the navigation, the logo won’t render

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Go to SharePoint and open nav.docx
2. Remove the submenu (table called 'menu')
3. Save/preview the document
4. Observe the footer not being rendered at all

### Expected Results

![Screen Shot 2024-03-28 at 12 49 46](https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/afcdf127-1703-470a-a5b9-e16ee74f5aa5)

### Actual Results

![Screen Shot 2024-03-28 at 12 50 00](https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/2be0dedc-4f87-46a1-90ac-c0e856237e32)

**Comment by girishdigrajkar** [comment]
iOS+ safari:
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/8db255cd-7e7c-44fb-ae04-2bd2bbe1bafb">
**Validated and able to see correct results :**
**iOS+chrome:**
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/c34b64c0-7eed-4ed6-9202-a6fa964010ad">

Android + Edge
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/259075cc-2963-431d-b6a6-4f2bf4e46ac2">

**Android tab:**
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4be3b2c4-fcc6-4480-9fc0-4511d810ed2c">

**iPad + safari:**
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/ca84568a-161d-4afb-b67d-d9ecda7fe438">
