### ISSUE TITLE
Display the search & login icon in Header on development/test environments

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#697]
### Issue Type

Defect

### Summary

[header] doesn’t show search or login icon on certain environments

### Priority

Low

### Description

The regression reported in #689 didn’t occur to us until we rolled out changes on production. This is because of changes made for #521. This was mentioned during SRB on 2024-04-16 and was noted as an action item during the retrospective of Sprint 1 (24B).

- The [configuration](https://github.com/hlxsites/vg-macktrucks-com/blob/main/blocks/header/header.js#L7-L14) needs to be changed and added to `constants.js`
- Instead of using `visibility: hidden;` or `display: none;`, a link shouldn’t be present

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to the website on development/test/staging (localhost, https://main--vg-macktrucks-com--hlxsites.hlx.page/, https://main--vg-macktrucks-com--hlxsites.hlx.live/)
2. Observe the Search and Login icon not being visible

### Expected Results

1. The search/login icon and link are present on development/test/staging environments; to reflect production state of the main website
2. The search/login link is not present on development/test/staging/production environments for certain markets (which should be configurable)

### Actual Results

 On none of the development/test/staging environments we see the search/login icon

**Comment by girishdigrajkar** [comment]
Early testing results:
Looks okay for desktop however, for Tablet and mobile viewport position of search icon is incorrect :

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/7836ee7c-9ed2-4fae-8ab7-c54d33b6a45b)

**Comment by amglebihan** [comment]
@girishdigrajkar I fixed the position of the search icon on mobile/tablet.

**Comment by girishdigrajkar** [comment]
Validated and able to see correct results; The raised observation is also closed now hence, closing the defect.

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4404f822-1c66-4d74-8a9c-e66584abfad7)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/d516ac1e-9a62-4c92-8409-7294d01702b9)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/62586f13-0a08-4883-b089-2ef2fe6acf80)

<img width="1728" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/f2e7d767-7ebb-4ead-97a5-ba3445f9b279">
