### ISSUE TITLE
Helix v5_decorateIcons leads to duplicated icons in sprite

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#700]
### Issue Type

Bug

### Summary

decorateIcons to be updated

### Priority

Low

### Description

During investigation on helix-v5 upgrade, I noticed this issue. If an icon is present multiple times on a page, it’s added that many times in the generated HTML. This is a performance issue.

See https://github.com/adobe/aem-boilerplate/issues/219; solved with https://github.com/adobe/aem-boilerplate/pull/220

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to a page where an icon is used more than once – this is any page
2. With browser devtools, look for `<svg id="franklin-svg-sprite">`
3. Observe some icons being present multiple times

### Expected Results

`franklin-svg-sprite` should be a unique list of icons

### Actual Results

`franklin-svg-sprite` contains duplicated icons, with duplicate ids, which I believe is not actually allowed because IDs must be unique

**Comment by BeckyMedlin** [comment]
#621, #704, and #700 use exact same code per @cogniSyb. Regression test plan needed to be efficient on testing the different instances of how we use icons. @girishdigrajkar

**Comment by girishdigrajkar** [comment]
Validated and able to see unique icons list in franklin-svg-sprite  hence, marking the defect to close status:

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b07b8b21-e79a-4a1b-940e-ef2b33626040)
