### ISSUE TITLE
NFR: add custom decorateIcons script for helix v5

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#704]
From vg-volvotrucks-us created by [cogniSyb](https://github.com/cogniSyb): hlxsites/vg-volvotrucks-us#621

### Context/Description

In PR hlxsites/vg-volvotrucks-us#604 we noticed issues with icons when upgrading to helix v5. This is reported in hlxsites/vg-volvotrucks-us#608. After investigation, we concluded that moving to the current version of the `decorateIcons` script of `aem.js` is impossible.

Our need of adapting icons to their context is of high importance. Migrating to another technique would mean:

- Architectural changes of redesign blocks
- Extra development work to cater for this
- More work for content editors, due to less automation
- More risk of incorrect (brand) color usage

Hence, it has been decided to move to one generic script for Mack Trucks and Volvo Trucks and use that instead of the function in aem.js

### Acceptance Criteria

**Editor AC:**
- Applying icons in pages remains unchanged

**Non-functional AC:**
- Create a version of the decorateIcons script with image sprite functionality in common.js
- This script will be the same for for all Volvo Group websites

### Note
Due to the MT script for loading icons is more efficient, overall performance will be improved. It might be that this change will have a positive impact on hlxsites/vg-volvotrucks-us#600

### Technical details
Copy the code of #700; apply the same change as in hlxsites/vg-volvotrucks-us#621

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, closing the issue.
