### ISSUE TITLE
NFR: Refactoring Buttons for Helix 5 Upgrade

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#713]
From vg-volvotrucks-us created by [mollyaljenkins](https://github.com/mollyaljenkins): hlxsites/vg-volvotrucks-us#625  

### Context/Description

Currently some buttons on the Mack Trucks sites are hardcoded. Following the Helix 5 upgrade buttons will be affected because the upgrade will allow for configuration and behaviour of the buttons to be customized. 

Blocks with hardcoded buttons will need to be updated.
Button variations will need to be defined in a clear and standardized way. 

### Acceptance Criteria

**Editor AC:**

- Placing a link on it's own paragraph will create a button 
- Variations will be selected via using Italic, or Bolding 
- Button styling is dictated by the emphasis of the text in the Word document 
- To use the marketing button a variant of the block needs to be turned on 
  - The name of this variant needs to be defined 
- The standard button will become the tertiary button  

### Note

Some blocks can maintain hardcoded buttons (TBD) 

**Button Options**

Button block collection from AEM:
(https://www.aem.live/developer/block-collection/buttons)

**Current hardcode buttons to be replaced**
https://docs.google.com/spreadsheets/d/13yqPktBPlojezO7enJjKG0n0rXxggl3SMutwEk_pe9o/edit?usp=sharing#gid=408989977

**Comment by amglebihan** [comment]
Mapping after the refactoring:
If you add a link to a page with:

- a strong emphasis: primary button
- an em emphasis: secondary button
- no emphasis: red button

The standalone-link remains added in the code.
