### ISSUE TITLE
Magazine has incorrect URL in Teaser Grid

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#743]
### Issue Type

Bug

### Summary

[teaser-grid] uses incorrect value for URL

### Priority

High

### Description

The block uses the text of the link that’s provided instead of the href attribute

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://www.macktrucks.co.nz/magazine/
2. Follow one of the links in the teaser grid

### Expected Results

The URL should be /magazine/articles/2022/october/hanson-s-metroliner-takes-mining-to-a-new-level

### Actual Results

The URL is https://main--vg-macktrucks-co-nz--hlxsites.hlx.page/magazine/articles/2022/october/hanson-s-metroliner-takes-mining-to-a-new-level

### Attachment

The URL correct in the source, but the text of the link was wrong:

<img width="1117" alt="Screenshot 2024-06-12 at 19 27 00" src="https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/d812c4a0-03be-492e-b721-0150626bbfe8">

**Comment by girishdigrajkar** [comment]
Validated by changing the display text other than the link and able to get the correct results i.e. href link is used for navigation hence, closing the issue.

<img width="1728" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/f266c758-3458-4f1c-a8fb-eee506d8c41c">
