### ISSUE TITLE
FR: [Magazine Hero] - Hero Variant

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#746]
### Context/Description

As a Mack Trucks content creator, I would like a variant of the hero block to use on my article pages so that my Bulldog Magazine articles stand out from other website pages. 

### Acceptance Criteria

**User AC:**
- [ ] As a user I see a simple hero image with white capitalized text.  

**Editor AC:**
- [ ] As an editor, I can use this block on any page. 
- [ ] As an editor, I can edit the text displayed on the hero so that it can be different than the metadata title. 
- [ ] As an editor, I can copy and paste this block from the AEM Sidekick Library. 

**Non-functional AC:**
- [ ] The block shall be named: Hero (Magazine)
- [ ] The aspect ratio for the hero image will be 5:2
- [ ] Block is as tall as its contents, with 80px padding vertically.
- [ ] Block image is viewport filling so that it shows the full width of the webpage that is responsive to be on any device.
- [ ] Text is white color.
- [ ] Text is displayed in the upper left-hand corner of image.
- [ ] Text font-family is "GT America." 
- [ ] Text transform is uppercase.
- [ ] Each word in the title shall cause a line break, no matter how many characters. 
- [ ] Block can be used in magazine template.
- [ ] The article text shall be completely content authorable and not automatically pull in the full article title. (This will be displayed below the hero image and be taken up in a separate ticket. 

### Attachment / link to Figma

Desktop: 
https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=14119-2366
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/63bce3f4-9069-4e3d-ab85-2ceaf5de6935)

**Mobile:** 
https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=2222-52867
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/60f8e15b-2312-46f1-a5d8-f0138a376ecc)

**Comment by AsmitKMishra** [comment]
Testing Completed.
1.Block has name Hero(Magazine).
2.Aspect ratio is within margins.
3.Block is as tall as content.
4.Text  is white and correct font and on the left corner.
5.Words get transformed to uppercase and each word has it's own line.

Specs match as per Figma and requirements and are within margins.
