### ISSUE TITLE
FR: Social Block

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#748]
### Context/Description

As a Mack Trucks content creator, I want to display social media icons so that users can easily share the website page they are viewing directly on their social media channels. 

### Acceptance Criteria

**User AC:**
- [ ] As a user, I can share a magazine article directly to my X, LinkedIn, or Facebook social media accounts simply by clicking on the icon displayed on the website page. 

**Non-functional AC:**
- [ ] Block shall be named [V2 Social Block]. 
- [ ] Icons are present for social media channels: X (formerly known as Twitter), LinkedIn, and Facebook in this order.
- [ ] Icons can be re-used from the footer if possible. 
- [ ] Icons will be black color.
- [ ] Block can be used in #603 
  - In the Magazine Template, block is present twice on articles:
  - [ ] First appears below the author byline on mobile devices, and aligned to the right of the article page margin on desktop as specified in the below Figma designs. 
  - [ ] Second appears at the bottom of the article body text above the related stories block. 

### Note

- Figma designs use outdated Twitter logo, the new X logo should be used instead. 

### Attachment / link to Figma

Desktop: 
1 - https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=2222-51372
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/edc46b5f-fa1b-4eb6-ae61-be1cec3b3750)
2 - https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=14119-2399
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/42fd2f50-d4e7-4e0b-a476-277adc8b5bc6)

Mobile: 
1- https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=2222-52877
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/2db2dd01-f240-4a5e-96d4-615b0628d2f2)
2 - https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=2222-52899
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/6a70b227-12a6-4053-80cf-16e4905e7454)

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly.
