### ISSUE TITLE
FR: Image Banner

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#749]
### Context/Description

As a Mack Trucks content editor, I want to have more visually appealing images on the website which can be displayed either in full size or as a banner in order to enhance the overall experience and capture user's attention. 

### Acceptance Criteria

**User AC:**
- [ ] As a user, I can view images that span the entire width of the screen within the magazine article text body.

**Editor AC:**
- [ ] As an editor, I can choose from two variants of this block that have image aspect ratios of 16:9 and 4:3.
- [ ] As an editor, I can use this block on any page.
- [ ] As an editor, I can use this block from the AEM Sidekick Library. 
- [ ] As an editor, I can use images from AEM Assets for this block. 

**Non-functional AC:**
- [ ] The block shall be named "V2 Image Banner (16:9)" and "V2 Image Banner (4:3)" 
- [ ] The block can be used in #603 
- [ ] The block shall have 64 px of padding above and below the image. 
- [ ] Aspect ratios are 16:9 and 4:3
- [ ] A 16:9 image will remain static on the page without any parallax effect. In contrast, a 4:3 image will feature parallax. The visible area for the parallax image will be 360px on desktop and 160px on mobile.

### Attachment / link to Figma

Desktop: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=14214-16244

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/e3138711-9a23-488b-ba41-a192896e25d4)

Mobile: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=14223-16180

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/a1b5d83f-17a5-4c1b-8d15-62fcbbb5e782)

**Comment by amglebihan** [comment]
Important note on how the [parallax](https://www.figma.com/design/oNwe2jHIICPMIe551EY62l?node-id=14214-16146&m=dev#919997816).

**Comment by silviulungu** [comment]
Testing Completed.
Everything works accordingly.

**Comment by girishdigrajkar** [comment]
Marking ticket to 'Testing Complete' status  as per your comments above by @silviulungu .
