### ISSUE TITLE
FR: [V2 Recommendations] New Block - Recommended Articles 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#750]
### Context/Description

As a Mack Trucks content editor, I want to improve the recommended stories block on my magazine article pages so that the look and feel is more consistent with the V2 cards block and increase the number of recommended stories from 2 to 3. 

### Acceptance Criteria

**User AC:**
- [x] As a user, I can view 3 articles related to the current magazine article I'm reading. 
- [x] As a user, if I click on one of the articles I will be redirected to the full magazine article. 

**Editor AC:**
- [x] As an editor, I can use this block on any magazine page. 
- [x] As an editor, I can find this block in the Sidekick Library. 

**Non-functional AC:**
- [x] The block will be named: V2 Recommendations
- [x] The block can be used in #603 
- [x] The block will dynamically display the 3 most recently published articles that have the same article category tag. 
- [x] If there are no similar article category tags, then the block should display the 3 most recently published magazine articles. 
- [x] The minimum articles displayed is 3. If there are less than 3 articles with the same article category tag, then it should display the most recently published. 
- [x] The block background color will be #F1F1F1
- [x] The image is coming from the metadata of the article
- [x] The default amount of articles is set to 3

### Out of scope

Video in thumbnail will be handled in a separate ticket. 
Adding more than 3 articles will not be active until a design revision is done

### Note

- Reference existing block [recommendations (limit-2)] 
- Reference existing block [V2 Cards]  

### Attachment / link to Figma

Desktop: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=14119-2407

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/4ad78d77-cc3e-456a-be2a-cf0cc3279914)

Mobile: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=2222-52906

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/f4e6e5e9-236a-408a-8467-c03b00f02ff9)

**Comment by AsmitKMishra** [comment]
Font size and font family isn't according to figma design.
<img width="339" alt="Screenshot 2024-10-15 154732" src="https://github.com/user-attachments/assets/b5cd8078-c793-4fe8-af44-98435192d521">
<img width="737" alt="Screenshot 2024-10-15 154115" src="https://github.com/user-attachments/assets/72f963af-1181-465e-a9cf-601162d5a47b">
<img width="425" alt="Screenshot 2024-10-15 154041" src="https://github.com/user-attachments/assets/5dcaca85-ef4f-4529-9614-17cdb4cf7856">

**Comment by AsmitKMishra** [comment]
Testing completed. Above issue was fixed and now the feature works as expected.
