### ISSUE TITLE
Bug: V2 Truck Lineup broken with Helix 5 upgrade

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#751]
### Issue Type

Bug

### Summary

[v2-truck-lineup] rendering broken

### Priority

Critical

### Description

As reported for #714: aem.js breaks rendering of v2-truck-lineup

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://714-spike-helix-v5--vg-macktrucks-com--hlxsites.hlx.page/drafts/syb/page/homepage
2. Observe block being rendered differently

### Expected Results

![develop--vg-macktrucks-com--hlxsites hlx page_drafts_syb_page_homepage(1920✕1080)](https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/e9494582-8139-4466-ae31-d067e5907a79)

### Actual Results

![714-spike-helix-v5--vg-macktrucks-com--hlxsites hlx page_drafts_syb_page_homepage(1920✕1080)](https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/5d8a4a2a-bc5a-4cfb-8457-9089237ba238)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, closing this bug.


<img width="1728" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/2bf5820c-0a74-4daf-983d-e42f22aa1210">

<img width="1728" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/90c02a3d-dea5-44ce-9b4e-f6b977e83984">

<img width="1728" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/abea6ed6-7012-4c85-bb92-b4112094f6e8">
