### ISSUE TITLE
Bug: Modal broken with Helix 5 upgrade

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#752]
### Issue Type

Bug

### Summary

[modal]

### Priority

Blocker

### Description

As mentioned in #714. Modal functionality should work the same as for Volvo Trucks

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://714-spike-helix-v5--vg-macktrucks-com--hlxsites.hlx.page/
2. Observe the modal not being loaded

### Expected Results

Modal present

### Actual Results

Modal not present

**Comment by verareljic** [comment]
Please check internally and provide an update @ZoeBeykirch

**Comment by ZoeBeykirch** [comment]
There are some video players using modals, and that is the only kind of modal required.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct result and hence, closing the ticket:

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/faf918f3-ee61-4a9a-a6d0-257e8f2a3a8f)

**Comment by BeckyMedlin** [comment]
@jonatan-lledo-netcentric This ticket wasn't included in the v20 release notes https://github.com/hlxsites/vg-macktrucks-com/releases/tag/v20 Is it possible to add it?

**Comment by jonatan-lledo-netcentric** [comment]
I updated the description, but this issue was already there. it's just I didn't see that I missed the number reference
