### ISSUE TITLE
Bug: Issue with Truck Builder Email Generation Link

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#761]
### Issue Type

Bug

### Summary

There's an issue after the user submits the form for the truck builder, the email that they are sent doesn't have the right link for them to review their truck configuration. 

### Priority

Blocker

### Description

There's an issue after the user submits the form for the truck builder, once they get an email that should have a link to their configured truck, in the email generation the link is not being attached to the CTA. You can't currently reach the configuration from the email.

For example, the Builder URL passed to us from Rapid Images:
https://www.macktrucks.com/trucks/pinnacle-series/build/#/pinnacle?config=eyJjIjpbMzcsMjE0LDkyNCwyMTUsOTI3LDI0MywxMDU3LDI0NCwxMDYyLDIxNiw5MzAsMjE3LDk1MSwyMTksOTU4LDIyMCw5NjMsMjE4LDk1MiwyMjEsOTY1LDIyMiw5NjcsMjIzLDk3MSwyMjQsOTc1LDIyNSw5ODEsMjQwLDEwNDYsMjQxLDEwNDgsMjQyLDEwNTIsMjM4LDEwMjQsMjM0LDEwMDcsMjMyLDEwMDQsMjMzLDEwMDUsMjM1LDEwMTQsMjM2LDEwMTYsMjQ2LDEwNzAsMjQ3LDEwNzMsMjQ4LDEwNzUsMjQ5LDEwNzcsMjUwLDEwNzksMjUxLDEwODFdfQ%3D%3D
 
Builder URL stores as the above link on MCAE prospect, Salesforce lead record, and the email. The issue appears to be the URL structure is not correct, as the main homepage opens upon click: https://www.macktrucks.com/trucks/pinnacle-series/build/#/pinnacle with no selections saved.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices

### Steps to Reproduce

1. Navigate to: https://www.macktrucks.com/trucks/build/
2. Complete all steps in the configurator and submit the form with your email that you can test
3. When the email comes through, there is a call to action to review the unique truck you had configured. Try to open this link - you will see that it's not the truck you had just created. 
4. The classic builder had a really short URL, for example: https://share.macktrucks.com/short.ashx/apdkuqg however, the link that is coming through in the email is broken, for example: https://www.macktrucks.com/trucks/pinnacle-series/build/#/pinnacle?config=eyJjIjpbMzcsMjE0LDkyNSwyMTUsOTI5LDI0MywxMDU3LDI0NCwxMDYzLDIxNiw5MzYsMjE3LDk1MSwyMTksOTU5LDIyMCw5NjQsMjE4LDk1NiwyMjEsOTY1LDIyMiw5NzAsMzE2LDEzMDgsMjIzLDk3MywyMjQsOTc2LDIyNSw5ODYsMjI2LDk4OSwyMzksMTAzOCwzMTcsMTMxMywyNDAsMTA0NiwyNDEsMTA1MSwyNDIsMTA1MywyMzgsMTAyNiwyMzQsMTAxMCwyMzIsMTAwNCwyMzMsMTAwNiwyMzUsMTAxNCwyMzYsMTAxNiwyNDYsMTA3MCwyNDcsMTA3MywyNDgsMTA3NSwyNDksMTA3NywyNTAsMTA3OSwyNTEsMTA4MV19

### Expected Results

The link that comes through the email should be the same as what the user had just configured. Example: https://share.macktrucks.com/short.ashx/apdkuqg

### Actual Results

The emails that are coming through with the link to your truck configuration have very long URLs that are broken, for example: https://www.macktrucks.com/trucks/anthem/configurator/#/anthem?config=eyJjIjpbMSwxNiwxLDU3LDI5MCw0NSwyNzUsNDYsODYsMTcsMTA2LDE4LDUsMjcsMzAsMjAsOCwyNiwyNyw4MiwzODEsODQsMzgzLDg1LDM4NSw4NiwzODcsMjgsMjMxLDMyLDIzNSwzMyw0NSw1MCw5Niw1MSw5OCw1MiwzNTksNTMsMjgzLDQyLDI2MSw3NCwzNTcsNzYsMzY2LDc4LDM3NCw3NywzNjgsNjEsMzAzLDY3LDMxNiw2NSwzMTIsNjYsMzE0LDY5LDMxOCw2NCwzMTBdfQ%3D%3D

### Attachment

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/8fed1af3-c2eb-4877-9501-a4d651f84b49)
![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/1dc6456b-26ee-4ca4-bd7f-1a19979d1311)

**Comment by amglebihan** [comment]
@ZoeBeykirch There is no logic on our end responsible for generating these links. For the truck builder, we simply load the [JavaScript and CSS](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B442A97A7-2584-4B43-82FF-210037A9E2F0%7D&file=truck-configurator.xlsx&action=default&mobileredirect=true&wdsle=0) provided by Rapid Images onto the page.

**Comment by ZoeBeykirch** [comment]
Thanks for looking into this, I have informed Rapid Images. We have a follow up call scheduled on Monday 6/24 at 8:30am EST for them to support this issue. Closing this ticket for now since it doesn't appear to be anything our team can do about it.
