### ISSUE TITLE
 Bug: Video in modal broken

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-macktrucks-com#763]
### Issue Type

Bug

### Summary

[modal] video creation broken

### Priority

Blocker

### Description

<img width="523" alt="Screenshot 2024-06-21 at 07 12 20" src="https://github.com/hlxsites/vg-macktrucks-com/assets/133873665/c178dd9b-8c49-4805-881e-16c047f6f555">

Refactoring of video-related functions for #589 broke existing functionality. I traced it back to this change: https://github.com/hlxsites/vg-macktrucks-com/commit/01641b8fa10451e398d12600d747469b5889f39a

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://develop--vg-macktrucks-com--hlxsites.hlx.page/drafts/syb/block/v2-testimonial-video
2. Click the video link in the second or third testimonial
3. Observe the modal not opening

### Expected Results

A modal is shown, with a video playing automatically.

### Actual Results

No modal is being shown

**Comment by girishdigrajkar** [comment]
Validated and now model opens and user is able to play all the three videos and no errors noted in console.
