### ISSUE TITLE
NFR: [Breadcrumbs] - content authorable

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#770]
### Context/Description

As a Mack Trucks content editor, I want the ability to edit the text displayed so that I can customize the breadcrumbs displayed on website pages in order to capitalize specific names and simplifying text for clarity. 

### Acceptance Criteria

**Editor AC:**
- [ ] As an editor, I can adjust the text that is displayed in breadcrumbs. For example, change capitalization and shorten title names to be different than what is saved in the metadata fields. 
- [ ] Example: mDRIVE HD in the breadcrumb, instead of Mdrive Hd

**Non-functional AC:**
- [ ] Change from automatically populating the breadcrumbs to be content authorable. 
- [ ] If there is content then links to all pages needed will create the breadcrumb so that they are authorable

Example: mDRIVE HD

### Note

Related ticket for original request - https://github.com/Netcentric/vg-macktrucks-com-rd/issues/44

### Example

Currently Breadcrumbs turn the word: mDRIVE HD to:
![Image](https://github.com/user-attachments/assets/8222cd6c-e017-45f5-a947-c87a6b21ddce)

**Comment by girishdigrajkar** [comment]
Outstanding observations:

1. Mobile:  Last link name is  not displayed unlike the desktop viewport:
![image](https://github.com/user-attachments/assets/a7c11b1b-7e5f-494d-913c-a748e6249e7c)
![image](https://github.com/user-attachments/assets/4b3b0e6b-448b-4bf5-ace0-c55d4214b3e4)

2. First example in above link has first link as different domain ( www.google.com) so when clicked on it shows new browser window.

**Comment by girishdigrajkar** [comment]
Ok with the comments above ans we can proceed closing this ticket...

**Comment by AsmitKMishra** [comment]
Testing Completed. Feature works as expected.
