### ISSUE TITLE
FR: Italics First Letter Text Enhancement

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#773]
### Context/Description

As a Mack Trucks content author, I want to improve the way "_m_ DRIVE" and "_m_ RIDE" are displayed on the website so that we can remove the errant space added with italicized letter between the "m" and next letter in order to meet our brand guidelines. 

### Acceptance Criteria

**User AC:**
- [x] As a website user, I can view "_m_ DRIVE" without any spacing between the italicized "m" and "DRIVE"

**Non-functional AC:**
- [x] Spacing is removed between an italicized letter when it is next to another text without italics. 
- [x] Run a script to check for italic letters and trim the additional space 

### Note

See example: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/bugs#italics

### Technical details

On the hero sections, if there is a superscript or not making a letter ittalisized it will add an extra padding.

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/122567401/6e323fbc-f048-4b24-8685-fafb3f4ff477)

**Comment by AsmitKMishra** [comment]
Testing Completed. The feature works. 
<img width="655" alt="001" src="https://github.com/user-attachments/assets/f7c258f5-1b89-422e-a4aa-01b59fe9cb14">
