### ISSUE TITLE
Bug: [V2 product listing] broken with Helix 5 upgrade

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#777]
### Issue Type

Bug

### Summary

The V2 product listing block is not working properly, likely due to the helix 5 upgrade

### Priority

Blocker

### Description

The V2 product listing is not displaying properly and may need to be refactored to work with the new helix 5 upgrade requirements. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices. 

### Steps to Reproduce

1. Navigate to example page: https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/index-new
2. This block was copied and pasted from the AEM Sidekick library and does not function the same way it is previewed in the block library. 

### Expected Results

See the V2 Product Listing block in Sidekick Library for expected results: https://main--vg-macktrucks-com--hlxsites.hlx.live/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-product-listing&index=0

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/a26454a1-f8b5-448b-aa44-f067242f642a)

### Actual Results

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/aa45589c-0338-492e-a2d8-c74b54261112)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/57b0cf7c-6c29-489c-be17-698cc75d3316)

**Comment by santi-homps** [comment]
Some content issues found here and fixed. 

- Incorrect format on the buttons. 
- Misplaced position for the images
- Wrong format on the link
- More than 3 items on each engine's list won't fit (see image) and will stretch text container over the height limits.

<img width="594" alt="Screenshot 2024-06-26 at 4 33 35 PM" src="https://github.com/hlxsites/vg-macktrucks-com/assets/68013336/2cc8e603-1e44-427b-af89-c26781ece4e8">

**Comment by BeckyMedlin** [comment]
@Kannan-CM Also reviewed this issue with the following findings:

[6:31 AM] Chinnamuthan Kannan
The section height is set to 400px by default and it doesn't adjust the height based on the content.
So, we need to probably limit the text.

On Big Screens:
 
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/142249558/7b0cf93b-c87b-4fe0-a1d6-e2e47527e91f)


On Laptop Screens:
 
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/142249558/c9f051f3-ed4b-48ed-9dd8-f3e30d2bbee4)


The heading is occupying the 2nd line which pushed the text and buttons down.
Advised @WendyKruger to submit tickets in Teams if she needs additional assistance from CMS or if she would like to submit an enhancment request.
