### ISSUE TITLE
FR: CSS Adjustment for Superscript

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#778]
### Description
As a Mack Trucks content editor, I want the superscript horizontal and vertical positioning formatting on the website to be enhanced for consistency across all pages, so that our registered trademarks or anything that uses superscript adheres closely to our brand guidelines.

### Acceptance Criteria

**User AC:**
- [ ] As a user, when I view the Mack Trucks website and see a registered trade mark, the size and vertical and horizontal positioning is always consistent no matter what text formatting is used or which block the superscript is in.

**User AC:**
- [ ] As an editor, I can use the superscript and expect it to display the same result across the website. 

**Non-functional AC:**
- [ ] A potential fix is to change line 681 of style.css from:

main sup {

font-size: clamp(var(--body-font-size-s), 12px, 1em);

padding-left: 3px;

}

**_Change to:_**

main sup {

font-size: clamp(8px, .337em, 24px);

padding-left: 1px;

position: relative;

top: -.75em;

vertical-align: top;

}

See more details to the above suggestion:  https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/bugs#superscript

### Attachment / link to Figma

See examples of how the superscript should look: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2220-92911&t=yj3X4LfrAhIT8SLs-1

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results:

![image](https://github.com/user-attachments/assets/eb7ad3c8-fe11-4694-a066-8c92030c26ff)


<img width="1724" alt="image" src="https://github.com/user-attachments/assets/53862ecf-5f04-4d16-be40-a25c99221faa">
