### ISSUE TITLE
Bug: AEM Asset Custom Thumbnail Issue

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#781]
### Issue Type

Bug

### Summary

[V2-Embed] block will break when a content editor uploads a thumbnail image.

### Priority

Blocker

### Description

Using the AEM Assets on the Volvo Trucks website allows content editors to upload a custom thumbnail, however when you use the same format on the Mack Trucks website it breaks the block. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to any test word document in the macktrucks.com site
2. Copy and paste any video from AEM Assets to use the V2-Embed block
3. upload a photo to the block above the video link (proper image size is 16:9)
4. Preview the word doc
5. See how the video player is broken

### Expected Results

Use the same block on Volvo site to see the expected results:

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/7532faa9-fc2c-497c-b246-b6e8af6c8e53)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/4d1754b8-6779-4049-baed-975e5fd16f3d)

### Actual Results

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/216efe63-488f-49b9-ae9d-b4f90d857a14)

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/d57db1b8-4333-4db8-bcb0-e19081f4d2f9)

**Comment by ZoeBeykirch** [comment]
Wait to refine after general AEM Asset overview discussion

**Comment by verareljic** [comment]
To be discussed with Satya Deep Maheshwari (Adobe Assets expert).

**Comment by ZoeBeykirch** [comment]
Update from Alan ([via slack](https://ncchat.slack.com/archives/C06LC1AUNCS/p1721231267063249)) this [ticket](https://github.com/hlxsites/vg-macktrucks-com/issues/795) fixed it, can you please verify? I created this [page](https://adobe.sharepoint.com/sites/HelixProjects/_layouts/15/doc.aspx?sourcedoc={b1d05525-9474-45a3-a928-9ff2f7a87fbb}&action=edit) to test it, here is the [preview link](https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/alan/v2-embed)

**Comment by BeckyMedlin** [comment]
@girishdigrajkar @mollyaljenkins This item is ready for testing. @ZoeBeykirch will need to provide access to the QA tester who will handle this verification. Please let her know who needs access. There are a limited number of seats available and she's unable to provide access to everyone on the team.

**Comment by girishdigrajkar** [comment]
@ZoeBeykirch : Please provide access to me primarily from QAs ; additionally to @AsmitKMishra ( in case possible & only after Devs have access)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, please proceed closing it. 

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/a70d98d2-f965-4e91-bbd9-6959d1077a67">

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/7c6b5b6b-286c-4e07-8770-9476ad24467c">

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/900bf706-ffdc-41f0-9aa0-8c8ebf25b97f">
