### ISSUE TITLE
Bug: V2 embed video broken

### ISSUE THREAD

**Issue by alexiscoelho** [hlxsites/vg-macktrucks-com#795]
### Issue Type

Bug

### Priority

Critical

### Description

V2 embed videos broken

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to: https://main--vg-macktrucks-com--hlxsites.aem.page/drafts/syb/block/v2-embed-multiple-config

### Expected Results

The embed videos should load and no related errors should appear on the console.

### Actual Results

None of the videos load

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, bug could be closed.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/756df4bd-bd89-4a07-b3d2-1183db660a43">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/84af3a71-8c27-467e-861d-d7f975022804">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/00e61800-18f6-4840-9ded-b77379446137">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/9339223c-c831-4039-a1a1-a858a3624f34">
