### ISSUE TITLE
Bug: Major - Cards with CTA over images - Some of the images are displayed incorrectly as cutoff or pixelated

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#80]
On the Cards with CTA over Images component on https://8-cards-with-cta-over-images--vg-macktrucks-com--hlxsites.hlx.page/trucks/ - the third image for Granite truck is displayed as cutoff and the last image for MD Series is smaller/pixelated

**Steps to reproduce:**
1. Go to https://8-cards-with-cta-over-images--vg-macktrucks-com--hlxsites.hlx.page/trucks/
2. Notice the image on the third Card for Granite truck
3. Notice the image on the last (seventh) Card for MD Series

**Expected result**
Images on Cards for the trucks should be correctly and clearly displayed displayed

**Actual result**
The image on the third Card for Granite truck is displayed as cutoff
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/bc560951-0bee-4888-88fc-492bb19c3e22)

The image on the last (seventh) card for MD Series is smaller / more pixelated than the rest
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/d99062ac-2b0e-4c64-b6c9-edbafe494001)

#8

**Comment by jonatan-lledo-netcentric** [comment]
fixed in the main branch https://main--vg-macktrucks-com--hlxsites.hlx.page/trucks/

**Comment by Andrei-Boiangiu** [comment]
issue confirmed as fixed in main branch as per above comment
