### ISSUE TITLE
FIX [Library Metadata] whitelist v2 check

### ISSUE THREAD

**Issue by santi-homps** [hlxsites/vg-macktrucks-com#813]
### Summary

[Library Metadata] add block to whitelist v2 check

### Priority

Medium

### Description

`Library-metadata` block should be whitelisted from the version check implemented so that the block library works properly and does not display an error when encountering this block in a `v2-redesign` page

### Value creation

Maintainability & scalability

### Cost of fixing

Low cost

### Technical complexity

XS

### References

![Screenshot 2024-07-30 at 1 27 16 PM](https://github.com/user-attachments/assets/62ae3ddd-66a5-450a-842e-b46d3740b6b0)

**Comment by girishdigrajkar** [comment]
Validated and no more warning displayed on the page (Since it was merged checked on main branch):

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/0c0ee338-140a-43be-ba51-c5730944699f">
