### ISSUE TITLE
Explore Magazine Articles 

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#82]
Explore Bulldog Magazine articles page:
https://www.macktrucks.com/magazine/explore-articles/

<img width="1441" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/4632fb0a-6436-4a89-9caa-1cc990d7dc2b">

**Comment by girishdigrajkar** [comment]
Confirmed as fixed
