### ISSUE TITLE
FR: Exclude Articles Without Images from Magazine Feed Pages

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#828]
### Context/Description

As a Mack Trucks magazine content author, I want articles without images to be automatically excluded from the magazine feed, so that the magazine feed only displays articles with visuals to provide the best user experience for my readers. 

### Acceptance Criteria

**User AC:**
- [ ] As a magazine reader, when I view the magazine feed each article displayed shows an image.

**Non-functional AC:**
- [ ] If an article is missing an image, in the [magazine-articles.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-macktrucks-com/[magazine-articles.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-macktrucks-com/magazine-articles.xlsx?d=wb2201e6b8c784eb7a2ebe2a58d352468&csf=1&web=1&e=e5JWDb)?d=wb2201e6b8c784eb7a2ebe2a58d352468&csf=1&web=1&e=e5JWDb) then it should be automatically removed from the magazine feed pages.
- [ ] Image URL is checked, if it is not present than the article does not appear in this block

### Note

Affected ticket - https://github.com/hlxsites/vg-macktrucks-com/issues/602

**Comment by girishdigrajkar** [comment]
Validated and able to see Validated and able to get the correct results hence, this ticket could be closed:

As part of checks, added one test row with no image and it is excluded from displaying on page ( Later the test data is removed).

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8e3aa4d9-c5c4-4ca3-b2e3-00d5bb01373c">
