### ISSUE TITLE
FR: Replace lib-franklin.js by aem.js

### ISSUE THREAD

**Issue by amglebihan** [hlxsites/vg-macktrucks-com#836]
### Context/Description

As part of the Helix v5 upgrade, the lib-franklin.js file needs to be replaced with the new aem.js file. We'll need to update the imports in the JavaScript files and conduct testing to ensure everything functions correctly with the new file in place.

### Acceptance Criteria

**AC:**

- Replace lib-franklin.js by aem.js, and update imports.
- Test that everything functions correctly with the new file in place.

**Comment by AsmitKMishra** [comment]
Testing Completed.
Everything functions correctly with new file in place.
