### ISSUE TITLE
NFR: Add Locale Column to MT Market Sites Metadata Files

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#842]
### Description
As part of the implementation plan outlined in [Issue #790](https://github.com/hlxsites/vg-macktrucks-com/issues/790), we need to update all Mack Trucks market sites' metadata files by adding a new column for Locale. 

### Acceptance Criteria

- [ ] Add a "Locale" column to the metadata files for the following MT market sites.
- [ ] Ensure the "Locale" column is populated with the correct locale information specified below in column 3:

| Country | Language | Locale | Status |
|----------|----------|----------|----------|
| 1. Argentina | Spanish | es-AR | [x] Complete | 
| 2. Bahamas | English | en-BS | [x] Complete |
| 3. Bolivia | Spanish | es-BO | [x] Complete |
| 4. Chile | Spanish | es-CL | [x] Complete |
| 5. Colombia | Spanish | es-CO |  [x] Complete |
| 6. Costa Rica | Spanish | es-CR | [x] Complete |
| 7. Dominican Republic | Spanish | es-DO | [x] Complete |
| 8. Ecuador | Spanish | es-EC |  [x] Complete |
| 9. El Salvador | Spanish | es-SV | [x] Complete |
| 10. Guatemala | Spanish | es-GT | [x] Complete |
| 11. Guyana | English | en-GY | [x] Complete |
| 12. Haiti | English | en-HT | [x] Complete |
| 13. Honduras | Spanish | es-HN | [x] Complete |
| 14. Mexico | Spanish | es-MX | [x] Complete |
| 15. Nicaragua | Spanish | es-NI | [x] Complete |
| 16. Panama | Spanish | es-PA |  [x] Complete |
| 17. Peru | Spanish | es-PE |  [x] Complete |
| 18. Trinidad & Tobago | English | en-TT |  [x] Complete  |
| 19. Venezuela | Spanish | es-VE | [x] Complete |

### Notes
- See [www.macktrucks.com](https://www.macktrucks.com/) [Metadata file](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BCA53D476-F493-46BE-9978-141E77D808D6%7D&file=metadata.xlsx&action=default&mobileredirect=true) example that has Locale set as en-US

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results except for outstanding observation related to Venezuela .

@Varunvolvo :  Please see below observation
**Observation:**
 Venezuela has  Locale value updated next to URLs  '/'    &   '/**'      
 It is unlike other markets hence, will be great to have it updated only for '/** '  

[Issue 842 validation.docx](https://github.com/user-attachments/files/16710096/Issue.842.validation.docx)

**Comment by ZoeBeykirch** [comment]
Thank you @girishdigrajkar! I have updated the metadata file for Venezuela to only have it on /**

**Comment by girishdigrajkar** [comment]
Retested and able to see correct single entry for Locale column in case of Venezuela export market hence, this ticket can proceed closure as passed :

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/92fc8120-3253-4320-ab6b-d0e824668850">

**Comment by ZoeBeykirch** [comment]
Thank you! I will close this now and send the Locale code data to Rapid Images. No PRs needed as the Metadata sheets are already published, the work is now completed.
