### ISSUE TITLE
NFR: Update Helix-Tools Tab in Constants Files for Market Sites

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#844]
### Description

As a systems administrator, I want to synchronize the constants files of all market sites with the parent USA site as part of the Helix 5 upgrade, so that the Helix-tools tab configuration is consistent across all market sites.

### Acceptance Criteria 

- [x] All 24 market site Constants files (both .xlsx and .json formats) must be updated to include the Helix-tools tab so that it matches the[ parent USA Constants file.](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-macktrucks-com/[constants.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-macktrucks-com/constants.xlsx?d=w723fa6654a8b400faf8902ff2b6dfabe&csf=1&web=1&e=GqXtbe)?d=w723fa6654a8b400faf8902ff2b6dfabe&csf=1&web=1&e=GqXtbe) The field `GIT_REPO` needs to be customised for each market.
   - [x] vg-macktrucks-bs
   - [x] vg-macktrucks-ca
   - [x] vg-macktrucks-cl
   - [x] vg-macktrucks-com-ar
   - [x] vg-macktrucks-com-au
   - [x] vg-macktrucks-com-bo
   - [x] vg-macktrucks-com-co
   - [x] vg-macktrucks-com-do
   - [x] vg-macktrucks-com-ec
   - [x] vg-macktrucks-com-emea
   - [x] vg-macktrucks-com-gy
   - [x] vg-macktrucks-com-mx
   - [x] vg-macktrucks-com-ng
   - [x] vg-macktrucks-com-ni
   - [x] vg-macktrucks-com-pa
   - [x] vg-macktrucks-com-pe
   - [x] vg-macktrucks-com-ve
   - [x] vg-macktrucks-co-nz
   - [x] vg-macktrucks-cr
   - [x] vg-macktrucks-gt
   - [x] vg-macktrucks-hn
   - [x] vg-macktrucks-ht
   - [x] vg-macktrucks-sv
   - [x] vg-macktrucks-tt

**Comment by santi-homps** [comment]
@alexiscoelho @ZoeBeykirch 
All sites have now available the `helix-tools` tab in `constants.xlsx` with the corresponding `GIT_REPO` value.
Tested in all cases except `vg-macktrucks-sv` where the constants configurations have not been implemented.
Marked as done ✅
