### ISSUE TITLE
NFR: Configure and retrieve necessary information to configure the new v2-dealer-locator

### ISSUE THREAD

**Issue by alexiscoelho** [hlxsites/vg-macktrucks-com#846]
### Context/Description

As a Developer I want to move the hardcoded configurations in each Mack Trucks market into a new page with the v2-dealer-locator configured in each market.
This will enable in the future the content editors to efficiently configure/setup the v2-dealer-locator component in each market.

### Acceptance Criteria

**User AC:**
- [ ] The new v2-dealer-locator component works as expected in all markets where the original dealer-locator component is currently configured in production.

**Editor AC:**
- [ ] As an editor I will have a test page that I can consult to configure the component for each Mack Trucks market

**Non-functional AC:**
- [ ] For each export markets the following field hardcoded configs need to be retrieved from the codebase and setup in a document with the v2-dealer-locator configured for each given market:
    - [ ] country
    - [ ] coords
    - [ ] amenities

### Out of scope

Configure the production page of the dealer locator
Publish the new demo pages.

### Note

[vg-macktrucks-com demo configuration for the .com default dealer locator](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB8A6853A-86E5-47D5-A9E5-7F28EEDA841F%7D&file=index.docx&action=default&mobileredirect=true)

[vg-macktrucks-cl demo configuration for the .cl (Chile) default dealer locator](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA5A69EFD-5BC1-4E2D-BD7A-973CAD752200%7D&file=index.docx&action=default&mobileredirect=true)

**Comment by santi-homps** [comment]
At the moment, `v2-dealer-locator` has only been implemented in **.com** repository.
On all other markets there is a file called **new-v2-index.docx** with the new block set and configured, that should replace the current **index.docx** as soon as (**and not before**) the changes implemented in the **Release-v24** (done 28 Aug) are syncd into all other markets or the migration to a single central repository is done.
It requires only to delete the current index.docx and renaming new-v2-index.docx for all countries.

**Comment by verareljic** [comment]
Once the release is completed CMS team needs to rename the documents and publish them. @Kannan-CM @Varunvolvo @BeckyMedlin @ZoeBeykirch
