### ISSUE TITLE
Bulldog Magazine listing page

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#85]
Bulldog magazine listing page
https://www.macktrucks.com/magazine/bulldog-magazine/
<img width="1433" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/1e8134f6-5fcd-4297-94c9-3bde8e007ba3">

Test page:
https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/andrei.balanescu/magazine/bulldog-magazine?view-doc-source=true

**Comment by girishdigrajkar** [comment]
Validated and raised below minor bug, agree to close this ticket:
https://github.com/hlxsites/vg-macktrucks-com/issues/174
