### ISSUE TITLE
Italicizing the text is creating a space

### ISSUE THREAD

**Issue by Varunvolvo** [hlxsites/vg-macktrucks-com#868]
### Issue Type

Bug

### Summary

An empty space is been occurred when the text is been italized

### Priority

Medium

### Description

In the magazine article when the text is made italic. There is a empty space in front of the letter. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices.

### Steps to Reproduce

1. Navigate to https://www.macktrucks.com/magazine/articles/2024/september/mack-mdrive-hd-brings-application-excellence-to-vocational-work
2. View the body text of the article, example text - mdrive = _m_ drive

### Expected Results

The extra space should be corrected

### Actual Results

The extra space should be corrected

### Attachment

![Capture](https://github.com/user-attachments/assets/69b090b0-7895-4285-864e-c274c55fa7c4)

**Comment by AmjedKhaled165** [comment]
This might help:This file might fix it

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by ZoeBeykirch** [comment]
Closing this ticket because this fix will be picked up in https://github.com/hlxsites/vg-macktrucks-com/issues/773
