### ISSUE TITLE
Bug: V2 Embed (AEM Asset Videos) formatting issues

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#870]
### Issue Type

Bug

### Summary

V2 Embed (AEM Asset Videos)

### Priority

Blocker

### Description

The V2 Embed block is now having formatting issues, it should be centered on the page and now the video player box is appearing smaller and left-justified. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

This is currently affecting production in all browsers + devices. 

### Steps to Reproduce

1. Navigate to any page that uses an AEM Asset V2 Embed block. Example: https://www.volvotrucks.us/trucks/vnr/interior
2. Scroll down until you see the text "Improved seating, instruments and controls are designed to put the driver comfortably and safely in command."
3. View how the video is no longer centered, and the video player box is smaller than it was before. 

### Expected Results

https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/zoe/v2-embed-test

![Image](https://github.com/user-attachments/assets/9e73dbe9-e3e9-4797-9d93-7604bc2a3fb7)

### Actual Results

![Image](https://github.com/user-attachments/assets/f1b5aa62-8d39-4b00-ba5e-d46427ea31db)

**Comment by BeckyMedlin** [comment]
@ZoeBeykirch with the PR from Yugandhar on 9/23, is this ticket still needed?

**Comment by ZoeBeykirch** [comment]
Closing ticket as bug is confirmed fixed
