### ISSUE TITLE
Bug: Website not loading on Apple devices

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#874]
### Issue Type

Bug

### Summary

the macktrucks.com website is not loading on Apple devices, affecting iPhones, iPads, and Macbook computer 

### Priority

Blocker

### Description

The Macktrucks.com website fails to load on Apple devices. Users are experiencing a blank screen without any content being displayed.

### Affected Device Classes

Mobile, Desktop, Tablet

### Affected Browsers/Devices and Versions

Chrome and Safari were tested and confirmed not working on iPhone 15 and iPhone 11 iOS Version 17.6.1
MackBook Pro 13-inch, M1, 2020 computer tested and confirmed not working in Safari and Chrome 
iPad has been tested and confirmed website is not loading in Safari and Chrome

Working:
Android device was tested and all is working as expected.
PC Desktop computers were tested and Windows computers load the site as expected 

### Steps to Reproduce

1. Using an apple device, go to https://www.macktrucks.com/
2. see the blank screen where content doesn't load. 

### Expected Results

Website should load content 

### Actual Results

Chrome on iphone: 
![Image](https://github.com/user-attachments/assets/75e63527-9411-4fb8-8b87-763c72efe47a)

Safari on iphone: 
![Image](https://github.com/user-attachments/assets/bedc1163-01b0-4b76-a30d-0debede27a46)

iPad tablet:
![Image](https://github.com/user-attachments/assets/7382e8b0-6fa1-4922-af42-d739c8e898ec)

MacBook Pro Computer: 
![Image](https://github.com/user-attachments/assets/145b0cb7-8098-40f4-9ae1-a2953e8413c8)

### Related Ticket
https://github.com/hlxsites/vg-volvotrucks-us/issues/762

**Comment by santi-homps** [comment]
This bug occurred due to a change in the preload of the `constants.json` file in `head.html`. This was done in order to check if this was being done from inside a different language site ( fe: `/fr-ca/` ) and apply that country specific file.

### This format:
`<link rel="preload" href="/constants.json" as="fetch" type="application/json" crossorigin="anonymous"/>`

### changes into this: 
```
<script type="module">
  import { getLanguagePath } from '/scripts/common.js';

  try {
    const dynamicUrl = `${getLanguagePath()}constants.json`;

    const link = document.createElement('link');
    link.rel = 'preload';
    link.href = dynamicUrl;
    link.as = 'fetch';
    link.type = 'application/json';
    link.crossorigin = 'anonymous';

    document.head.appendChild(link);
  } catch (error) {
    console.log(error);
  }
</script>
```
