### ISSUE TITLE
feat: Cards

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#88]
Implement rise-on-hover and porting volvotrucks.us cards functionality

**Comment by girishdigrajkar** [comment]
Confirmed with Lakshmi for PR : https://github.com/hlxsites/vg-macktrucks-com/pull/136

**Comment by girishdigrajkar** [comment]
Validate Cards and is working fine except for Minor defect https://github.com/hlxsites/vg-macktrucks-com/issues/167
