### ISSUE TITLE
Bug: v2-accordion with links to other content fragments broken

### ISSUE THREAD

**Issue by alexiscoelho** [hlxsites/vg-macktrucks-com#891]
### Issue Type

Bug

### Priority

Blocker

### Description

Accordion broken at:
https://www.macktrucks.com/trucks/granite-series/#specs
<img width="1116" alt="Screenshot 2024-10-10 at 16 06 14" src="https://github.com/user-attachments/assets/f35486d9-041f-4936-bc67-a61d2134fca7">

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Go to https://www.macktrucks.com/trucks/granite-series/#specs
2. Scroll to the bottom of the page
3. 
<img width="1116" alt="Screenshot 2024-10-10 at 16 06 14" src="https://github.com/user-attachments/assets/7dcc7d66-e0cb-4677-883e-9528ee740737">

### Expected Results

<img width="1201" alt="Screenshot 2024-10-10 at 16 07 05" src="https://github.com/user-attachments/assets/a700399f-bea2-4279-8837-8890db81470f">

### Actual Results

<img width="1116" alt="Screenshot 2024-10-10 at 16 06 14" src="https://github.com/user-attachments/assets/692800d3-1c0a-4436-a7db-a7e0a5d40cb6">

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, this bug could be closed:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/2377ed80-43ad-4ea3-ab4c-9191507a0c38">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/39ccd706-c55f-4637-9516-fe27aeb0b4e2">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/b690b476-1965-4f7b-8422-6cedd27da048">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/ca48c01a-58fc-4a21-a81d-798d497c2f39">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/964a9dbc-d4f8-45b4-967d-31bb9996838f">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/f2193906-dc0a-416d-9c9b-db4f8870885a">
