### ISSUE TITLE
Bug: Bulldog Magazine Article Publication Tag Field Issue

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com#903]
### Issue Type

Bug

### Description

Needed for MT Helix 5 Upgrade happening in Sprint 5 24D

When a new Bulldog magazine article is published, the tag field in column F of the [magazine-articles](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB2201E6B-8C78-4EB7-A2EB-E2A58D352468%7D&file=magazine-articles.xlsx&action=default&mobileredirect=true) Excel sheet fails to update correctly. Each time a new article is added, all entries in the Category column are cleared. If this field is left blank, it results in the production category segment pages on the website displaying no articles, including pages like the "[Customer Profiles](https://www.macktrucks.com/magazine/categories/customer-profiles)" 

Kannan has implemented a temporary solution by manually copying and pasting the magazine excel sheet fields after adding a new article to prevent the pages from breaking. However, this is not sustainable, and a permanent fix is needed. This ticket is to update the code to ensure that the magazine category and tags automatically populate from the Excel sheet, preventing any disruptions to the category functionality.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices. 

### Steps to Reproduce

Since this issue can only be seen when publishing a new magazine article, please reach out to Kannan for a demo of the issue happening to reproduce the steps. 

### Expected Results

When publishing a new article, the content in [column F ](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB2201E6B-8C78-4EB7-A2EB-E2A58D352468%7D&file=magazine-articles.xlsx&action=default&mobileredirect=true) should not be cleared out. Instead, it should dynamically pick up the tag for column F for Category based on the article-category metadata from the bulldog magazine. See example of[ article metadata. ](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BD8141F30-6410-4EA6-91E9-0944E2FAED8D%7D&file=choosing-mack-is-a-no-brainer.docx&action=default&mobileredirect=true)

### Actual Results

The article-category is not transferred over to Column F for category in the magazine [column F ](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB2201E6B-8C78-4EB7-A2EB-E2A58D352468%7D&file=magazine-articles.xlsx&action=default&mobileredirect=true), which breaks the bulldog magazine article pages that display articles by the categories.

**Comment by alexiscoelho** [comment]
Tested by @Kannan-CM  and it is working as expected.
