### ISSUE TITLE
feat: Download-list

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com#91]
Download block variation:
<img width="1537" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/116451851/38d182ff-cd88-4df1-afaa-d3652e3b38e8">

**Comment by Andrei-Boiangiu** [comment]
testing done with no outstanding issues

Note: on the helix website there is a limitation for opening/downloading the .pdf files. Adobe Sharepoint account and login will be required there, but on deploy these .pdf files should open/ download automatically
