### ISSUE TITLE
Bug: Minor: Fragment block has some text missing and font style is different than expected

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#92]
Steps:
1.  Navigate to https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/mack-news/2023/general-truck-sales-in-ohio-becomes-a-mack-certified-electric-vehicle-ev-dealer
2.  Validate the fragment section

Expected vs Actual:
1. Fragment block has some missing text as highlighted in screenshot
2. Font style is different

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/ab8551f3-ec58-40ab-b278-0e1d2185d172)

**Comment by manuel-vara** [comment]
Updated content

**Comment by girishdigrajkar** [comment]
@manuel-vara : unable to see changes done at below location hence, reopening defect.

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/41a6bde9-d18e-401d-a369-a778c3d39dc4)

**Comment by girishdigrajkar** [comment]
Validated on publish URL and able to get the correct results, Closing the defect.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/8d00cfe2-cab2-4f4c-9b2e-8ea8a0f447d4">
