### ISSUE TITLE
Bug: Minor: Fragment block : 'New RSS' label is not shown while in responsive mode, mobile, tablet viewport

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#93]
Steps:
1. Navigate following URL in page responsive mode:
 https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/manuel.vara/mack-news/2023/general-truck-sales-in-ohio-becomes-a-mack-certified-electric-vehicle-ev-dealer 
2. Validate the Fragment block in responsive mode
3. Validate the Fragment block in mobile, tablet viewport

Expected vs Actual :
![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/b7546942-5f5a-4b4d-9fd6-6e448830da0f)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/1f944175-6c90-47e7-955e-4f3eb6174b59)

![image](https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/5407c2eb-dfd7-4231-97aa-c92df8c1cb47)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
