### ISSUE TITLE
Bug: Major - Mobile view - Find a Dealer Locator - Filter by Distance screen has different styling and causes a side scroll on Mobile

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-macktrucks-com#95]
When opening the Filter on the Find a Dealer Locator on Mobile - the Filter by distance bar has a different styling and causes a side scroll in the holder of the mobile (user can scroll left and right instead of being completely wrapped )

**Steps to reproduce:**
1. Go to https://main--vg-macktrucks-com--hlxsites.hlx.page/buy-mack/find-a-dealer/ and open in Mobile view
2. Click on the Filter button next to the Search button
3. Notice that the Filter by distance element has different styling and it is not completely wrapped - a small side scroll is present

**Expected result**
Filter by distance should have the similar style and it should be wrapped and contained within the mobile view

**Actual result**
Filter by distance has different styling and it should be wrapped within the mobile view

<img width="1314" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/127409602/1ea20741-bf2f-42df-8b6b-db825d8b8626">

**Comment by Joesturbo** [comment]
This ticket /  item can be deprecated and removed. It is not essential for correction.

**Comment by Andrei-Boiangiu** [comment]
marking this ticket as Done (Will not fix) as per above comment
