### ISSUE TITLE
Bug: Medium: 'Find a Mack Dealer' section does not show any results when searched for valid zip

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#97]
Steps:
1. Navigate to https://5-dealer-locator--vg-macktrucks-com--hlxsites.hlx.page/drafts/jlledo/find-dealer-demo
2. Enter zip code in 'Find a dealer' section and press enter

Expected vs Actual:
The page does not show any results 
URL however, has the correct zip code

**Comment by synox** [comment]
@girishdigrajkar Which error message would you like to show? It's the same behavior on the old site.

**Comment by synox** [comment]
@girishdigrajkar Moreover, this was ported over (instead of a rewrite) from minified code. So it would be better to fix the original code instead of changing the code here. WDYT?
