### ISSUE TITLE
Bug: Major: Mobile: Block with Tabs shows image after the text

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com#99]
Steps:
1. Navigate to  https://42-block-tabs--vg-macktrucks-com--hlxsites.hlx.page/drafts/jlledo/tabs/tabs-demo
2.  Validate the block with the tabs in Mobile viewport

Expected vs Actual:
The block with Tabs shows image after the text ;  Also the tab names are having more spaces in between that it is not inline.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/8a424608-bffa-4be1-aeb6-40dc7e5676d9">

**Comment by jonatan-lledo-netcentric** [comment]
related with issue #98

**Comment by jonatan-lledo-netcentric** [comment]
fixed by #169
